### ISSUE TITLE
manage asdf version

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#102]
subcommand?
```
ros asdf install [version]
ros asdf use version/"system"
```

**Comment by eudoxia0** [comment]
I can write a tiny library for downloading/extracting/deleting ASDF versions from fare's GitHub (sort of what asdf.ros does).

Also, I've written a library for doing just that with Quicklisp instances, is it ok if I upload it to this organization? It's written in Common Lisp, so it's not going to be useful *right now*.

**Comment by snmsts** [comment]
no problem.

**Comment by eudoxia0** [comment]
Done https://github.com/roswell/asdf-manager
