### ISSUE TITLE
Suggestion: create a Roswell-specific organization

### ISSUE THREAD

**Issue by eudoxia0** [roswell/roswell#105]
Roswell has >1000 commits, many contributors, and is an established project that many people use. I think moving the code to an organization would help establish it as a community project rather than one person's Yet Another Implementation Manager.

Also, it would provide a central place to put Roswell-based projects, or Roswell's dependencies (I saw you just created [ql-checkout](https://github.com/snmsts/ql-checkout), I think that will be used in Roswell?).

It will also make it easier to factor code out of Roswell, into libraries that can be shared and tested separately.

And, most importantly, an organization makes it easier to manager a GitHub Pages repo, which is necessary to advertise the project.

If you decide to do this, I can also make the website since I have some experience with GH Pages (e.g., [Clack](https://github.com/clack/clack.github.com), [CommonDoc](https://github.com/CommonDoc/commondoc.github.io), [Ceramic](https://github.com/ceramic/ceramic.github.io)).

The obvious names like 'roswell' and 'ros' are taken, but 'roslisp' is available.

**Comment by snmsts** [comment]
:+1: 

ql-checkout will be distributed with ros script.

any comments? @fukamachi @guicho271828

**Comment by proofit404** [comment]
I don't think 'roslisp' is a good name. Maybe 'roswell-installer' or 'cl-roswell'.

**Comment by guicho271828** [comment]
I agree with @proofit404 , remember ROS is already an established name for Robot Operating System, a widely used infrastructure for controlling industrial and experimental robots like PR2, developed and used in CMU, MIT and more. It has (well, somewhat unsurprisingly) Common Lisp interface and it is also called [roslisp](http://wiki.ros.org/roslisp).

**Comment by proofit404** [comment]
Naming things is the most difficult task :smile:

**Comment by guicho271828** [comment]
Actually I have long dreamed of using roslisp in real robots, and reviving Common Lisp as the best developmental environment for writing a robotics program.

**Comment by snmsts** [comment]
hm...

**Comment by eudoxia0** [comment]
The roswell account might have private activity, or it might be inactive. In that case, [GitHub lets you email them to ask for the account][l]. I did that once and got a prompt reply, but sadly in my case the account had private activity ;)

[l]: https://help.github.com/articles/name-squatting-policy/

**Comment by snmsts** [comment]
OK. I'll ask first.please wait.

**Comment by snmsts** [comment]
got it! https://github.com/roswell

**Comment by eudoxia0** [comment]
:confetti_ball:

**Comment by eudoxia0** [comment]
Well, I guess I can close this one now.
