### ISSUE TITLE
documentation: internal functions

### ISSUE THREAD

**Issue by guicho271828** [roswell/roswell#106]

**Comment by snmsts** [comment]
I don't understand the needs.

**Comment by eudoxia0** [comment]
A few docstrings to help new devs, maybe.

**Comment by snmsts** [comment]
sure.

**Comment by guicho271828** [comment]
at least I need an API catalogue online (much like in quickdocs), without jumping to the source code.
Yesterday I found (quickload ...) and (defpackage ...) pair a very frequent combination that I use in the script, so I decided to check tomorrow (yes, today!) if roswell provides a combined API for this.
