### ISSUE TITLE
Random seed is fixed, maybe adding --seed option?

### ISSUE THREAD

**Issue by guicho271828** [roswell/roswell#110]
Problematic for people who need a good PRNG seed every time

```
[guicho papers]$ cat random.ros
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#
(defpackage :ros.script.random.3661518940
  (:use :cl))
(in-package :ros.script.random.3661518940)
(defun main (&rest argv)
  (declare (ignorable argv))
  (print (random 100)))
[guicho papers]$ ./random.ros

92 [guicho papers]$ ./random.ros

92 [guicho papers]$ ./random.ros

92 [guicho papers]$ ./random.ros

92 [guicho papers]$ ./random.ros

92 [guicho papers]$ 
```

**Comment by snmsts** [comment]
hm...

```
(defun main (&rest argv)
  (declare (ignorable argv))
  (setf *random-state* (make-random-state t))
  (print (random 100)))
```

**Comment by guicho271828** [comment]
of course it can be done on myself, adding a custom command line option to the script, but it has a sufficient generality to wide range of applications, and this default behavior is not intuitive.

**Comment by guicho271828** [comment]
and note that certain performance analysis also requires a fixed seed value in order to maintain the reproducibility. So, new random state for each invocation (default), and the specified seed value (optional) is desirable.

Well this is certainly not a CL feature (since make-random-state does not accept integer)

**Comment by guicho271828** [comment]
ugh, unsigned-byte argument returns error in SBCL 1.3.1 ...

**Comment by guicho271828** [comment]
SB-EXT:SEED-RANDOM-STATE does this

**Comment by guicho271828** [comment]
#116

**Comment by snmsts** [comment]
Thank you for your patch and your effort.I don't feel like taking it because I'm not sure this change always do good to everyone and there are plenty of way to fix this problem other than adding in init.lisp.

How about write the line in ``~/.roswell/init.lisp``

**Comment by guicho271828** [comment]
I don't have much preference here but at least the first commit (on CONTRIBUTION.md) would be still useful.

**Comment by snmsts** [comment]
Sure.
