### ISSUE TITLE
The bootstrap isn't found altogther

### ISSUE THREAD

**Issue by TheSlyWlf** [roswell/roswell#115]
this is the code i typed in for the installation, i am completely stumped and i have no idea how to find the bootstrap

slywlf@SlyWlf:~/roswell$ sh bootstrap
bootstrap: 2: bootstrap: aclocal: not found
bootstrap: 3: bootstrap: autoheader: not found
bootstrap: 4: bootstrap: automake: not found
bootstrap: 5: bootstrap: autoconf: not found

**Comment by snmsts** [comment]
It tells you absence of commands aclocal autoheader automake and autoconf.
I am stumped with your report's lacking information about your environment.
I have no idea what you can do at all.

**Comment by snmsts** [comment]
feel free to open if you find difficult and more information you can add.

**Comment by TheSlyWlf** [comment]
thank you but this is all i get for information when i get the the set where i am suppose to type in sh bootstrap thanks for trying though

**Comment by snmsts** [comment]
why I ask 'what is your environment question' which hardware which os which distribution (if it's linux) you are using are completely missing.
Do you know what package manager your system provides for you? I can't tell.
Do you think I can understand your environment?

I think it's not your fault but almost every developers are already fed up with followup questions like this.
I'm sorry if you don't like my attitude.

**Comment by snmsts** [comment]
Generally speaking.
the answer have done 'Please setup the missing set of commands you should've already know the names.'

If you want to know detail,Please add more information about your system.
I might be able to help if with the information.

**Comment by guicho271828** [comment]
@snmsts , time to sign yourself to https://github.com/dear-github/dear-github !

**Comment by TheSlyWlf** [comment]
It's fine really, it's my fault for not being able to provide more information, thanks for even responding so fast
