### ISSUE TITLE
Website (based on gh-pages)

### ISSUE THREAD

**Issue by guicho271828** [roswell/roswell#117]
possibly integrated with the man pages

**Comment by eudoxia0** [comment]
I should do this.

**Comment by guicho271828** [comment]
now that roswell is posted to reddit and it catched the attention, we should prepare it before the community feel disappointed (and diverges to the alternatives). I have been keeping from advertising roswell on reddit as a main article (although I mentioned it several times in my comments), because it might hurt with the current quality....

**Comment by snmsts** [comment]
...alternative?

**Comment by guicho271828** [comment]
when they misunderstood roswell as "an alternative of X" rather than superseding all of them, i.e., if we fail to convey our aim appropriately and convince them that "this is actually a good library worth migrating to", they would.

**Comment by Hexstream** [comment]
And in the face of disappointment, it's often tempting to defer to unknown future alternatives...

**Comment by eudoxia0** [comment]
I'm on the case :smirk_cat:

**Comment by vindarel** [comment]
Hello @eudoxia0, how's this website going ?

**Comment by guicho271828** [comment]
@vindarel anyone can take over :)

**Comment by eudoxia0** [comment]
Yeah I haven't done jack diddly squat w.r.t this

**Comment by guicho271828** [comment]
http://www.urbandictionary.com/define.php?term=jack%20diddly%20squat
> jack diddly squat
> the equivelent of nothing; something that amounts to nothing

@eudoxia0 yes, in fact, the github wiki is constantly modified by someone when something is wrong/updated, and considering the lack of manpower to maintain the page, the wiki seems very low-cost solution to provide a website...

@vindarel If you are interested, could you instead make the opening page of the wiki look a bit fancier? (how?) Maybe just a bit more descriptive/introductive.

**Comment by vindarel** [comment]
Since I'm pinged… hope you like the sidebar better now. The trick was to create a `_Sidebar.md` page. Now we can clearly organize the TOC on the side. You still have the list of pages (box above the sidebar).

I didn't really know how to enhance the home page though :D

**Comment by ta2gch** [comment]
Hi there, I think that the contents in Github Wiki is great, while the most of users will not visit this wiki than own website like https://roswell.github.io .

I wrote a generator from Github Wik to Github Page in CommonLisp. You can see this https://ta2gch.github.io/roswell/ . The code of this is https://github.com/ta2gch/roswell .

Would you like to use this?

**Comment by vindarel** [comment]
Wow, very nice.

The generator script is here: https://github.com/ta2gch/roswell with a template: https://github.com/ta2gch/roswell/blob/master/docs/page.tpl

I'd love to have them as an independent project ! And then I do agree this is way better than the actual wiki alone.

**Comment by guicho271828** [comment]
Interesting, how do you invoke that generator script?
you could add it to the travis release hook and update it regularly.

**Comment by snmsts** [comment]
I prefer using ``gh-pages`` branch.

**Comment by ta2gch** [comment]
> This script must be an independent project ! It's too useful not to be.

@vindarel Thank you. You said that we will create a repository roswell.github.io , didn't you? your comments have two meanings that are to make generator.ros an independent project or to create a repository roswell.github.io.

@snmsts gh-pages branch makes that script free from the project. However I propose you that we move this script to the repository roswell.github.io . When this script is in gh-pages branch, the domain is roswell.github.io/roswell. It is duplicates. 

@guicho271828 I had no ideas. I think the hook of TravisCI is good idea.

**Comment by snmsts** [comment]
@ta2gch Sound good. I made the repository and invite you as Collaborator.
If you wouldn't mind, would you put scripts there and show instruction how to update?
Then I'll take care CI part.

**Comment by ta2gch** [comment]
@snmsts I got it. I join the repository and put scripts as soon as possible.

**Comment by ta2gch** [comment]
@snmsts I added that scripts. We can see webpage at https://roswell.github.io/ when you turn on GIthub Pages featrue in Settings of the repository.

**Comment by guicho271828** [comment]
There are a few missing links.
+ How is Roswell different
+ Upgrading Roswell 
I am also thinking about integrating the man pages.

**Comment by vindarel** [comment]
> your comment has two meanings that are to make generator.ros an independent project or to create a repository roswell.github.io.

Indeed, I think this generator can be useful for many projects. If generator.ros was an independant project, one could add one line in a CI config and generate a nice website very easily.

**Comment by ta2gch** [comment]
@guicho271828 This generator use from `_Siderbar.md` with just replacing blanks to '-' same as a name of Github Wiki's markdown file, but not taking care the capital case and there aren't org-mode parser in CommonLisp. Some of these are written in org-mode.  We have to replace the documents and the titles.

@vindarel I'll make it and rewrite in Ruby that has Github's documents parser (org-mode, markdown etc) Thank you for your advice!

**Comment by guicho271828** [comment]
> org-mode parser in CommonLisp.
I see, I will replace those articles in markdown.

> rewrite in Ruby
For document conversion, pandoc is more straightforward, and you don't have to modify the internals.

**Comment by ta2gch** [comment]
Ah, in this issue and roswell.github.io I don't rewrite that because I think roswell must use own rosell script. Currently the script uses 3bmd as the markdown parser. I'm going to use ruby in **independant project** (https://github.com/ta2gch/wiki2pages) that @vindarel said.

**Comment by vindarel** [comment]
>  I'll make it and rewrite in Ruby

oh. As you wish (I understand the current limitation), though I liked the fact it is written in CL, it could make a little showcase of the language IMO.

**Comment by ta2gch** [comment]
> Indeed, I think this generator can be useful for many projects.

@vindarel I like it too, but your comment has letten me support any format for many projects. At this time, we has a chance to make document parsers in CL. When lispers will write almost documents parser for Github's README, I will change again from Ruby. Thanks.

@snmsts , @guicho271828 ,
Okey, we have few tasks.

- [ ] Make _Sidebar.md which has same capital cases of titles.
- [ ] Rewrite org-mode to markdown
- [ ] (Optional) Add a project icon in Home.md

**Comment by ta2gch** [comment]
Hi, there! I reports you the progress.

I switch to markdown.cl because 3bmd Markdown render has a issue about table syntax.

But markdown.cl doesn't support code block syntax and 3bmd said that he will fix this issue, so I'm going to change a parser again. Thank you.

**Comment by vindarel** [comment]
Hi, found an issue: the subsections are in reverse order. For example under "Getting started" the wiki has first "Installation" and last "How to setup a lisp dev…", but the website has them in reverse.

**Comment by ta2gch** [comment]
@vindarel Thanks. I got it. I will fix it within a day or two.

**Comment by ta2gch** [comment]
Fixed. https://github.com/roswell/roswell.github.io/commit/0865b84015dd525e3ddf076bbca03d6dc56472d8

**Comment by guicho271828** [comment]
It seems the syntax highlighting is not working correctly.
https://roswell.github.io/Roswell-as-a-Scripting-Environment.html

**Comment by ta2gch** [comment]
@guicho271828  Thanks! I has already known it.

According to my before comment.

> I switch to markdown.cl because 3bmd Markdown render has a issue about table syntax.
> But markdown.cl doesn't support code block syntax and 3bmd said that he will fix this issue, so I'm going to change a parser again. Thank you.

markdown.cl breaks code-blocks and 3bmd breaks tables. So I used the former.
BUT, I'm going to change to the latter again **in the feature** because of his comment.

**Comment by ta2gch** [comment]
I announce the news  that I changed the renderer from markdown.cl to 3bmd in roswell.github.io. 
We can use all features of markdown now. 

@snmsts, Would you like to close this issue?

**Comment by snmsts** [comment]
ok integrate with man would be other topic. I believe @guicho271828  would open issue for it.

**Comment by vindarel** [comment]
so do we advertise this website ? on reddit, the readme, github presentation sentence, etc ? https://roswell.github.io/

**Comment by ta2gch** [comment]
I cannot say 'Yes' because I'm not the owner of this project, but I agree. For users, this site has more information and tips than the README, while the README has them for developer such as source code and issues.

**Comment by guicho271828** [comment]
I'm trying to add a travis-CI script that automatically updates the website using its cron feature.

**Comment by snmsts** [comment]
@ta2gch you are officially the owner of the gh-page project (if you like to claim so).
You can say 'Yes'.
@guicho271828 I add ``ci`` branch for the purpose and I didn't do anything else yet.

I don't like mixing files for generate and generated files in a same repository, so I'd like use this ci to generate html and man as well then I'd like to delete everything from roswell/roswell/tree/master/documents.

**Comment by guicho271828** [comment]
> I don't like mixing files for generate and generated files

@snmsts yes I felt it odd as well.

**Comment by ta2gch** [comment]
@snmsts Thank you. For the propose, I have no opinion. If you work on that, I will wecome.

**Comment by vindarel** [comment]
Hello @asciian, in the end, where is the script ? Because https://github.com/ta2gch/wiki2pages doesn't exist anymore.

**Comment by asciian** [comment]
1, you can see the latest script in ci branch of roswell/roswell.github.io . 2, in these days I’m interested in the system which render the markdown in the browser. You can see it in asciian/cl-skkserv .

Thanks!
