### ISSUE TITLE
Lispworks support

### ISSUE THREAD

**Issue by spacebat** [roswell/roswell#119]
I'd like to use Roswell at work, but we use Lispworks. I haven't looked into what is required to support an implementation yet, but I figure it best to start by logging an issue.

**Comment by snmsts** [comment]
hm...

what you have to modify to support launch new implementation 

- modify src/cmd-run.c to register function for installation
- create src/cmd-run-xxx.c
- modify lisp/init.lisp

what you have to modify to support installing new implementation

- create lisp/install-xxx.lisp

I don't know how hard it is to support but It should be hard without license...
How about gathering $500 donation for me to support LW?(Hobbyist Edition?)

**Comment by Hexstream** [comment]
@snmsts If you're that interested in supporting Lispworks, they're known to give out free licenses in special circumstances. If you contact them at lisp-keys@lispworks.com and tell them that you'd like to (better) support their implementation for Roswell, I have little doubt that they would help you in that way.

**Comment by snmsts** [comment]
@Hexstream ok... I'll try.

**Comment by snmsts** [comment]
I've tried and am waiting for the response...

**Comment by Hexstream** [comment]
I guess I should clarify a few things (I might be overreacting a bit, I'm not sure if you sent the request 2 days ago and are now impatient for a response or are just signifying that you sent the request just now):

- I got the impression that Lispworks is relatively eager to give out free licenses to interesting projects' authors upon request mostly from Xach repeatedly mentioning it over the years (or at least it's been my impression).

- I don't really know anything about Lispworks (both the implementation and the company). (And if it weren't for the CLHS I basically wouldn't even know that they exist.)

- I don't know for a fact that lisp-keys@lispworks.com is the most practical and fastest way to contact Lispworks for license requests, it's just the most specific thing I found about it on their contact page: http://www.lispworks.com/support/contact.html Other venues such as their "lisp-hug" mailing list (which is said to be very friendly) might be more effective, I have no idea.

- In my bubble Roswell is relatively well-known by now, but I have no idea to what extent Lispworks would realize the importance of this project, since it's an open-source project _in development_ and I'm not sure to what extent they would track such things. So maybe they don't really have noticed this project yet, which might explain why they may not consider replying to your request a top priority. But maybe they just happen to be busy and don't consider a few days to be a long wait time. Or maybe the lisp-keys@lispworks.com address is not monitored that tightly. Or it could be any number of other factors. **I really have no idea how Lispworks operates since I have zero personal experience with them**.

In my opinion, I would guess that it would be appropriate to wait at least a week before trying to "escalate" in some way. Maybe someone more informed than me could try to expedite the process in some way...

Hope this helps!

**Comment by snmsts** [comment]
no response.

**Comment by Hexstream** [comment]
I find this very surprising and disappointing. :(

I guess one solution would be to stop caring about Lispworks... :/

**Comment by snmsts** [comment]
It's not surprising for me.
Supporting open source software project which has little(?) opportunity purchase their product might be not their focus.

Currently I can't highly prioritize this, but I want to support Lispworks someday.
I think it could be different license holders claim this.

**Comment by spacebat** [comment]
I've requested and just received an annual hobbyist license for the purpose of implementing LW support in roswell.

I'm not sure what can be done about the install functionality - the process involves authenticating to their website, downloading several files, interacting with a license agreement script, running the installer script, then running the installed binary with serial number and license key as command line arguments. Perhaps its best to leave all that for the user to do by hand.

**Comment by snmsts** [comment]
Thank you! Great achievement for us!

Personally I think it is better when it usable with CI.

``ros install impl`` could take options so I hope it could be automated.

I'm not sure about the what information are required.

1. authenticating to the website
2. download several files.
3. interact with a license agreement script
4. run installer script
5. run installed binary with serial number and license key.

questions related to process 1.

- the website(uri) is fixed?
- what kind of information are required for authenticate?

questions related to process 2.

- The files are found on the page authenticated or require traverse?
- What are several files?

a question related to process 3.

- should it be GUI? or ``yes`` command can automate it?

a question related to process 5.

- where the license key get from?

I hope if the install option for lisp works could be like below.

```
ros license-agreement=yes auth=XXXX install lispworks
```

BTW, Is the license permit disclose the information for roswell developpers?

**Comment by spacebat** [comment]
1. I believe website URI is fixed but parameterised based on the LW version number, version level (Hobbyist, Professional etc), the platform (linux, windows etc) and bitness (32, 64). It was HTTPS with HTTP auth, not sure if basic or digest.

2. The layout of the page followed this [attachment](https://github.com/roswell/roswell/files/323029/lw-download.txt). Links to files were sprinkled through it. In my case, I downloaded the lwl-license.sh, lwl-install.sh and two tarballs. Alternatively a set of RPMs can be downloaded depending on the version of LW you have.

3. It was completely a command-line affair.

4. The serial number and license key are obtained by purchasing the software. I think if it were to be automated, a file containing these would be the handiest way to get them into the script.

I think the number of links and steps means it would be easily broken by LW changing their website in minor ways. Perhaps a useful first step would be to raise a ticket for them to make the URL simpler to predict, and for a single shar file or similar to be provided. I'll have to read the license again, but having multiple installs under a single license is probably prohibited in which case facilitating that would be frowned upon. 

However I think it more practical for the ros install process to expect the user to make the files they downloaded and key information available so that there is no automation hitting the LW site. My instinct is to assume LW is installed legally and just require configuration to tell roswell where.

The license was provided to me alone and soley for the purpose of improving LW support in roswell. If I should fail to accomplish this, I'd be happy with the LW company's permission to transfer the license to you. I may have requested the wrong version though - the plain Hobbyist license I have does not include deliver, which means the compilation of dedicated binaries is not allowed, though images can be saved and restored. I figure that I'll do what I can and if/when I run into the need for the Hobbyist DV version, I'll raise it with them then.

**Comment by snmsts** [comment]
I see. It  seems there are nothing I can do for now.
I'll wait for your pull-request and If you want help I'm willing to help in any sense.

This is the first time someone other than me attempt to implement support new lisp.
I'd like to show you what step I'll follow when I do support new one. 
- [ ] prepare ``src/cmd-run-*.c`` (compare with other implementation support.)
- [ ] add the file on ``src/Makefile.am`` edit ``src/cmd-run.h`` ``src/cmd-run.c`` to register function ``cmd_run_*``
- [ ] edit ``lisp/init.lisp`` (find ``#+ccl`` and add support for the implementation)
- [ ] edit ``lisp/dump.ros``
- [ ] prepare ``lisp/install-*``
- [ ] edit ``lisp/util-install-quicklisp.lisp`` to register.

https://github.com/roswell/jscl might be helpful.

**Comment by snmsts** [comment]
How's it going?
@spacebat

**Comment by aneilbaboo** [comment]
I realize this is an old thread, but I want to put my two-cents in for Lispworks. They have by far the best debugger in the ecosystem. It would be really great to get Roswell working on it.

**Comment by Hexstream** [comment]
My personal stance is that if LispWorks wants to be properly supported by open source projects, then they should open-source their implementation, else why would we jump through hoops to support their inherently hard-to-support proprietary implementation?

If LispWorks went open source, then everyone would, and should, rush to give them first-class support, which is the opposite of the current situation.

**Comment by mdbergmann** [comment]
My two cents:
I think it shouldn't be necessary for LispWorks to open-source their product. This is what they sell after all.
But people from LispWorks should take care of the support for Roswell.

**Comment by Hexstream** [comment]
It may not be "necessary", but it is the fast path to solving all their problems and helping Common Lisp usher in a new era of dramatically increased relevance. It will happen faster with them than without them.

**Comment by mdbergmann** [comment]
> It will happen faster with them than without them.

That may be true.
But you realize that this is their model of business.
There is probably a lot at stake here. I At the least some people which require their salary.
Of course companies do open-source their stuff and settle on doing 'support' for their open-source products.
But I'm not sure that works here.

**Comment by Hexstream** [comment]
Well, what I don't get is why don't they just pull a RedHat and go open source while providing Enterprise support for large fees? Aren't most of their paying customers enterprises that require serious Enterprise-level support anyway? Why don't they just open-source and shift all their fees from stupid licensing to Enterprise support? Wouldn't they just get the cachet and relevance of being open source for free? Hell, they would probably make even more money!

Right now, they're just completely cutting themselves off from the open source marketing machine for no reason. And the Common Lisp Open Source world could certainly use THEIR marketing machine as well. I'm tired of this gratuitous division.

**Comment by mdbergmann** [comment]
Yeah. I would also welcome a different attitude. I guess there is a lot of maintaining status quo.
It would certainly be better if the two paid Common Lisp implementation could be more involved with pushing Common Lisp in general.
