### ISSUE TITLE
Typo in Travis CI Wiki?

### ISSUE THREAD

**Issue by noctuid** [roswell/roswell#120]
I notice that `- clisp` is listed under packages in the [advanced example](https://github.com/roswell/roswell/wiki/4.1-Travis-CI#advanced-travisyml) for the Travis CI `.travis.yml`. Travis will output `Disallowing packages: clisp`, and clisp is not listed below as a dependency in the explanation section. I just wanted to make sure that this is a typo before editing.

**Comment by snmsts** [comment]
I think ``sudo: false`` environment is not tested enough. so whatever it doesn't work it should be ``typo``
I'm sorry for inconvenience.

**Comment by fukamachi** [comment]
The example is okay because it's allowed failures below.

See https://github.com/roswell/roswell/wiki/4.1-Travis-CI#activating-the-container-based-infrastructure for using the Travis's container based infrastructure (sudo: false).
CLISP cannot be tested with the environment. ABCL and Allegro CL requires a few additional APT packages.

**Comment by noctuid** [comment]
> The example is okay because it's allowed failures below.

Is this in response to me? Having clisp under `packages:` doesn't break tests for any LISP, but it does nothing for any of them (always outputs `Disallowing packages: clisp`).

> CLISP cannot be tested with the environment. 

What do you mean? I haven't had any problems with clisp and `sudo: false`.

**Comment by snmsts** [comment]
> CLISP cannot be tested with the environment. 

This is definitely true when @fukamachi contributed installation script and until commit ecca5ea. But I don't remember is it tested with ``sudo: false`` environment after that?

@fukamachi 
Did you tried?

**Comment by noctuid** [comment]
It looks like it works for me. Clisp successfully installs and my tests pass [here](https://travis-ci.org/noctuid/cl-chronicler/jobs/106869637#L312) with `sudo: false`.

**Comment by fukamachi** [comment]
@snmsts Nope. Sounds great. I gotta try it.
2016年2月4日(木) 21:25 SANO,Masatoshi <notifications@github.com>:
