### ISSUE TITLE
Roswell and system installations

### ISSUE THREAD

**Issue by chuchana** [roswell/roswell#121]
I've noticed that roswell is separated from the system: it has no access to the lisps and quicklisp installed on the system, and the system has no direct access to the installations in roswell.

If that's by design, a mention in the readme file could make sense.

If isn't, wouldn't it make sense to have roswell check for system installations and to have a `binaries` folder inside the .roswell folder that contains symlinks to all installed implementations, which can be added to $PATH?

**Comment by guicho271828** [comment]
system-provided binaries tends to be too old, thats one reason.

Second, quicklisp or asdf installed on your system may be arbitrarly edited&configured, by your hand or by the maintainer of the system, or by the maintainer of the package manager (e.g. apt, yum). We simply lack such a capacity to support all those hustle and bustle.

**Comment by snmsts** [comment]
If you want use system installed sbcl
you can specify that by

```
ros use sbcl/system
```

I don't know it would work or not. I don't care. Manager should manage.

**Comment by guicho271828** [comment]
oh I didn't know that either. this should be documented in the man page.

**Comment by snmsts** [comment]
@guicho271828 :) of course /system is supported not only sbcl but abcl,acl,ccl,clisp,cmu and ecl as well.

@chuchana Do you want to have roswell as a compartmental lisp implementation installer and directly launch lisp?

**Comment by guicho271828** [comment]
updated the man page. Sorry for pushing the updates directly, but it seems somehow you have configured Github or travis to skip the CI, so it will do no harm.

**Comment by chuchana** [comment]
Thank you for the information!

Yes, I thought I could use it as a simple, system independent installer for Lisp implementations, i.e. on the Raspberry Pi. It is not as practical as I thought, but still more so than installing by hand, and I can create symlinks to the binaries' location manually.

Two other nitpicks:
You cannot use `ros use sbcl/system` (or any other lisp) unless a version of sbcl has already been installed roswell. If you try, you get

    Installing sbcl-bin...
    No SBCL version specified.
and it starts installing sbcl.


And you cannot `ros install ccl`:

    Unhandled SIMPLE-ERROR:
      'roswell-install-ccl' is not a valid target for 'install' -- It should be a name of either:
    + a quicklisp-installable system
    + a common lisp installation

`ros install ccl-bin` does work.

Now you do not claim that it should work, but the list of supported implementations does not seem clear to me. Wouldn't it make sense to create a table of supported implementations, i.e.:

implementation | default | -bin | versions
---------------------|-----------|-------|---------------
sbcl | x | x | x
ccl | |x|
… |||

**Comment by snmsts** [comment]
Thank you for the point.
Type  ``ros install`` will show

```
Usage: ros install impl [OPTIONS]

For more details on impl specific options, type:
 ros help install impl

Candidates impls for installation are:
sbcl-bin
clisp
ecl
ccl-bin
sbcl
```

Could it help?

**Comment by chuchana** [comment]
Thanks, it helps. I suppose the non-`bin` versions mean you can also install specific versions of that implementation?
