### ISSUE TITLE
easy upgrade as in `cim get`

### ISSUE THREAD

**Issue by guicho271828** [roswell/roswell#122]

**Comment by snmsts** [comment]
It might be unfair without asking the detail,but I don't like the idea in general.
I think I(we?) have to maintain distribution specific package or installer( for windows)

Would you show how to achieve it?

**Comment by guicho271828** [comment]
I just checked the feature list comparison I wrote before, and listed the missing features.

well, the first step might be just notifying the user of the new version, looking at the release version number in github. any web scraping method would be available.
the next step will be to download the new binary.
