### ISSUE TITLE
managing templates

### ISSUE THREAD

**Issue by guicho271828** [roswell/roswell#123]
I somehow thought it was already available at the time when I wrote https://github.com/roswell/roswell/wiki/0.-What's-the-Difference%3F because there is a directory `.roswell/template`. However, it does not seem the case. Is it available?

**Comment by snmsts** [comment]
Planned.

I'm not sure I'd say yes or no...
https://github.com/roswell/roswell/blob/master/lisp/init.ros#L31-L34

I think I'd use mystic for this part.

**Comment by guicho271828** [comment]
@eudoxia0 @snmsts 

I checked mystic, I know cl-project pretty well and I also have my own generator called eazy-project.
However, I recently feel all of them are overdeveloped (including mine) or that there are slight difference in *project template* and *script template*.

I mean, for example, I don't need :author field for generating a script for rendering a graph using eazy-gnuplot. I rather need much more lightweight templating framework, such as those implemented by a simple string replace.

Imagine for example, it is highly **UN** likely that a user who wrote a first version of some useful system-management script using roswell would write a plug-in for mystic. They would copy and paste the script if they need an alternative version (or they would extend the script with an argument, if possible). This applies to all kinds of one-time scripts (or batch script) which never goes beyond particular usage.

**Comment by guicho271828** [comment]
So my current idea is this:

Roswell templates proposal
=================

Usage: ros template add [OPTIONS] TEMPLATE {ARG}*

Read the file TEMPLATE and replace the string matching arg to an argument of the template.

The format of ARG is same as the lambda list except the following translation:

* each argument is separated by --, instead of being surrounded by parentheses.
* &key, &optional, &rest are converted to --key, --optional, --rest, respectively.
* Abbreviation as -k, -o, -r are available.

# Example

tmp.asd:

 (asdf:defsystem NAME :author AUTHOR :depends-on DEP :short-description \"library by AUTHOR.\")

$ ros template add tmp.asd NAME AUTHOR --optional DEP \"(:alexandria)\"
$ ros init --template tmp.asd bob-utilities '\"Bob\"' -- result.asd

result.asd:

 (asdf:defsystem bob-utilities :author \"Bob\" :depends-on (:alexandria) :short-description \"library by \"Bob\".\")

Notice the arguments are READ. Thus you may use \"#.\" readmacro in order to evaluate the
arguments when the template is instantiated. For example,

$ ros init --template tmp.asd bob-utilities '#.(uiop:getenv \"USER\")' -- result.asd

result.asd:

 (asdf:defsystem bob-utilities :author \"Bob\" :depends-on (:alexandria) :short-description \"library by AUTHOR.\")

# Options

* -f : Overwrites the existing template with the same name without asking
* -r : register the directory recursively. TEMPLATE should be a directory in order to make this option meaningful.
* --name=NAME : register the template with a given name, not the original filename.


# Misc

Registered templates are stored in directory $ROSWELL_HOME/templates/ .

**Comment by guicho271828** [comment]
#139

**Comment by guicho271828** [comment]
https://github.com/roswell/roswell/blob/templates/documents/ros-template.md

**Comment by snmsts** [comment]
Current 'ros init' takes only name-of-file.

to extend it.I don't like using ``--template`` and filename specified after ``--``.

|pattern|usecases|example|
|---|---|---|
|ros init template name-of-file args...| asd license| ``ros init LICENSE LICENSE MIT`` or ``ros init LICENSE COPYING GPL2`` |
|ros init template args...| Lakefile qlfile| ``ros init Lakefile``|
|ros init name-of-file| ros|``ros init tentative``|

Drawback of choosing this strategy would make impossible to ``ros init qlfile`` to make ``qlfile.ros``.

But I believe it is not difficult to learn and I can prepare ``default`` template for that.

**Comment by guicho271828** [comment]
started working on init.ros .

**Comment by guicho271828** [comment]
additional usecase : `ros init xxx ... > file`. I believe we can detect the stream type.

**Comment by guicho271828** [comment]
```
Usage: ros init [filename] [template_name] [args...]
```
`template_name` is defaulted to `default`.

**Comment by snmsts** [comment]
```
Usage: ros init FILENAME [TEMPLATE [ARGS...]]
```

Looks short and consistent enough and better than my idea for me.

**Comment by guicho271828** [comment]
Finished implementing the feature. Might require some future bug fixes, but at least it seems an MVP.
