### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#126]
design for roswell group (https://github.com/roswell)

**Comment by guicho271828** [comment]
just. idea. made in 4-5 minutes.

![idea-0](https://cloud.githubusercontent.com/assets/1321968/13188562/7fd5e778-d795-11e5-8eee-23e632a4d951.png)
![idea-1](https://cloud.githubusercontent.com/assets/1321968/13188563/7fd6cc7e-d795-11e5-97d3-b46134fdc60a.png)
![idea-2](https://cloud.githubusercontent.com/assets/1321968/13188565/7fdd84d8-d795-11e5-9817-b14f768ac045.png)
![idea-3](https://cloud.githubusercontent.com/assets/1321968/13188564/7fd88ee2-d795-11e5-9389-996387d2c633.png)

**Comment by eudoxia0** [comment]
A friend made this: http://i.imgur.com/SAGJZgU.png

**Comment by guicho271828** [comment]
I'm not sure those greys are the good fits to Lisp, but I like the styles and colors.

**Comment by snmsts** [comment]
@guicho271828 
Thank you.my image of Roswell is not stress on "tool" but "relation".
so 1st is the best among them.

http://rlv.zcache.com/vintage_science_fiction_astronaut_shake_hand_alien_poster-r7e7746f44c06468b84453032dfdf0e49_z26gp_8byvr_1024.jpg

@eudoxia0 
Is it ok just try it for tentative use?

**Comment by snmsts** [comment]
@guicho271828  @eudoxia0 

applied. do you like it?
