### ISSUE TITLE
ros setup

### ISSUE THREAD

**Issue by Chream** [roswell/roswell#134]
$ ros setup
Already have sbcl-bin.
Installing Quicklisp...
Skip downloading http://beta.quicklisp.org/quicklisp.lisp
Quicklisp is already setup.
Making core for Roswell...
Unhandled SB-INT:SIMPLE-READER-PACKAGE-ERROR:
  Symbol "UTIL" not found in the ROS package.

    Line: 22, Column: 9, File-Position: 507

    Stream: #<CONCATENATED-STREAM
              :STREAMS (#<SB-SYS:FD-STREAM
                          for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros"
                          {1003664743}>
                        #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>)
              {1003667613}>

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {100363F773}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10037250BB}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100372508B}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDERR* {1000172903}> :START 0 :FROM :INTERRUPTED-FRAME :COUNT NIL :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Symbol ~S not found in the ~A package." {100371FBC3}> #<unavailable argument>)
5: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Symbol ~S not found in the ~A package." {100371FBC3}>)
6: (INVOKE-DEBUGGER #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Symbol ~S not found in the ~A package." {100371FBC3}>)
7: (ERROR #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Symbol ~S not found in the ~A package." {100371FBC3}>)
8: (SB-IMPL::READ-TOKEN #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> #\r)
9: (SB-IMPL::READ-MAYBE-NOTHING #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> #\r)
10: (SB-IMPL::READ-LIST #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> #<unavailable argument>)
11: (SB-IMPL::READ-MAYBE-NOTHING #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> #\()
12: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> NIL (NIL) T)
13: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> NIL (NIL) NIL)
14: (READ #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> NIL #:EOF-OBJECT NIL)
15: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
16: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> NIL)
17: (LOAD #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}> #<SB-IMPL::STRING-INPUT-STREAM {1003667203}>) {1003667613}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
18: ((FLET ROS::BODY :IN ROS:SCRIPT) #<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" {1003664743}>)
19: (ROS:SCRIPT :SCRIPT "/usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" "main" "roswell-internal-core-build")
20: (ROS:RUN ((:SCRIPT "/usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" "main" "roswell-internal-core-build") (:QUIT NIL)))
21: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROS:RUN (QUOTE ((:SCRIPT "/usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" "main" "roswell-internal-core-build") (:QUIT NIL)))) #<NULL-LEXENV>)
22: (EVAL (ROS:RUN (QUOTE ((:SCRIPT "/usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros" "main" "roswell-internal-core-build") (:QUIT NIL)))))
23: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/init.lisp\"))") (:EVAL . "(ros:quicklisp)") (:EVAL . "(ros:run '((:script \"/usr/local/Cellar/roswell/0.0.4.57/share/common-lisp/source/roswell/+roswell-internal-core-build.ros\"\"main\"\"roswell-internal-core-build\")(:quit ())))")))
24: (SB-IMPL::TOPLEVEL-INIT)
25: ((FLET #:WITHOUT-INTERRUPTS-BODY-85 :IN SAVE-LISP-AND-DIE))
26: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting

----------------------------------------------------
Happens on clean install of ros on osx elcapitain through homebrew.

**Comment by snmsts** [comment]
May be it happens because I don't test version up from ``0.0.3.56`` to ``0.0.4.57`` sorry for inconvenience.

How about 

```
ros delete dump roswell sbcl-bin
```

then

```
ros setup
```

I hope it'll fix your problem.

**Comment by snmsts** [comment]
if ``ros delete`` doesn't work.

``rm ~/.roswell/impls/*/*/sbcl-bin/*/dump/roswell.core`` might work.

**Comment by Chream** [comment]
Thanks! `ros delete` did not work, but `rm ...` then `ros setup` worked.
