### ISSUE TITLE
Overriding configdir

### ISSUE THREAD

**Issue by dunn** [roswell/roswell#137]
Is it possible to change where the `.roswell` directory is created?  Roswell ignores `$HOME`, so this doesn't work:
```
HOME=/tmp ros init
```
And I couldn't find anything on how to change the `configdir`.  Is there a way to do it?

Thanks!

**Comment by snmsts** [comment]
ROSWELL_HOME might work.
I didn't test it seriously.
So might not work...

**Comment by dunn** [comment]
That seems to work, thanks!  Should I add it to the wiki?

**Comment by snmsts** [comment]
I'm appreciate if you add it.
Thank you. :)

**Comment by dunn** [comment]
OK! https://github.com/roswell/roswell/wiki/1.1-Initial-Recommended-Setup#configuring-the-environment

**Comment by snmsts** [comment]
Thank you very much!

**Comment by dunn** [comment]
This worked with 0.0.4.57, but doesn't work with 0.0.5.61.  Was that intentional?  If so, is there a different way to set the Roswell directory?

**Comment by snmsts** [comment]
Really? I didn't take care.

**Comment by snmsts** [comment]
fixed: https://github.com/roswell/roswell/commit/380434d229e82808588620c2b8558e1872fbe1b2

**Comment by dunn** [comment]
Thanks again!
