### ISSUE TITLE
CCL performance is degraded under Roswell

### ISSUE THREAD

**Issue by sjl** [roswell/roswell#141]
I'm using [sketch](https://github.com/vydd/sketch) to play around with some simple graphics stuff.  I've got a really trivial [sketch](http://paste.stevelosh.com/570d778c67478a00075f46c2?lisp).

When I run this under the homebrew-installed CCL with `/usr/local/bin/ccl64` I get 60 frames per second, as expected.  When I run the exact same code under Roswell's CCL with `ros -L ccl-bin run` I get 30 frames per second.  Performance drops further for the Roswell version as I add more circles.

Both the homebrew CCL and Roswell CCL appear to be the same version of CCL (`Welcome to Clozure Common Lisp Version 1.11-r16635  (DarwinX8664)!`).  What could be causing the massive drop in performance when running through Roswell?

**Comment by snmsts** [comment]
Thank you for your report.I'm surprised with your report.

I'm not sure is it the same binary or not.I mean it might have applied different compile option.
Would you compare binary installed by brew and roswell for me?

You can find (or be infered) where the CCL placed by roswell via `ros --test -L ccl-bin run`

If the result would same... I'll start thinking what I can do for it. so far I'm completely no idea what's wrong.

**Comment by snmsts** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/clozure-cl.rb

sorry it looks same...

**Comment by guicho271828** [comment]
could you check the other factors like

* log output
* default compilation option
* quicklisp version

**Comment by sjl** [comment]
Looking at the `dx86cl64` and `dx86cl64.image` files they are indeed identical for both roswell and homebrew (according to `md5`).  Strange.

I'm not sure where to look for "log output".  There's nothing special in Console.app or anything obvious in the terminal... what other logs should I look at?

I don't know what "default compilation option" means.  I just installed CCL with homebrew and roswell with no special configuration options that I know of.

I'm not 100% sure how to get the "quicklisp dist version" because `ql:dist-version` seems to take some kind of name and has no docstring explaining what it is.  But both `~/.quicklisp/dists/quicklisp/distinfo.txt` and `~/.roswell/impls/ALL/ALL/quicklisp/dists/quicklisp/distinfo.txt` say `version: 2016-03-18` so I assume they're the same...

**Comment by snmsts** [comment]
@sjl
I'd like to reproduce the phenomenon,but for now I can't execute your ''trivial sketch''.
Don't you have something that need to run the sketch other than the code?
I can't find where ``calc-fps`` and ``drow-fps`` are defined.

**Comment by sjl** [comment]
Sorry I'm dumb and copypasted wrong.  Here's a demo that works:

    (ql:quickload 'sketch)
    (in-package :sketch)
    
    ;;;; FPS
    (defvar *last-draw* 0)
    (defvar *fps* 0.0)
    (defvar *mspf* 0.0)
    (defvar *width* 800)
    (defvar *height* 600)
    
    
    (defun calc-fps (frames)
      (let* ((current-draw (get-internal-real-time))
             (elapsed (float (/ (- current-draw *last-draw*)
                                internal-time-units-per-second))))
        (setf *last-draw* current-draw)
        (setf *mspf* (* 1000 (/ elapsed frames)))
        (setf *fps* (* frames (/ 1 elapsed)))))
    
    (defun draw-fps ()
      (text (format nil "MSPF: ~,1F" *mspf*) 0 0)
      (text (format nil "FPS: ~,1F" *fps*) 0 20))
    
    
    (defsketch cm (:width *width*
                   :height *height*
                   :debug :scancode-d)
        ((mx 0)
         (my 0)
         (frame 1)
         )
      (background (gray 1))
      (incf frame)
      ;;
      (with-pen (make-pen :stroke (gray 0) :fill (gray 0.5))
        (circle 10 50 3)
        (circle 20 50 3)
        (circle 30 50 3)
        (circle 40 50 3)
        (circle 50 50 3)
        (circle 60 50 3)
        (circle 70 50 3)
        (circle 80 50 3)
        (circle 90 50 3)
        (circle 100 50 3)
        )
      ;;
      (when (zerop (mod frame 20))
        (calc-fps 20))
      (draw-fps))
    
    (defparameter *demo* (make-instance 'cm))

I just tried it locally and it loads, and shows the problem (60fps in homebrew/app store CCL and 20fps in roswell CCL).

**Comment by snmsts** [comment]
Thank you for quick response.

I feel it might be difficult to find clue.
Please be patient :(

**Comment by eudoxia0** [comment]
FWIW, you can consult the compiler's optimization policy with

```lisp
(defmacro policy (&environment env)
  `',(ccl:declaration-information 'optimize env))

(policy) ;; => ((SPEED 0) (SAFETY 3) (COMPILATION-SPEED 1) (SPACE 1) (DEBUG 3))
```

**Comment by sjl** [comment]
No worries, I'm just using this for a toy project right now so I'm just using the homebrew version for now.

Both the homebrew and roswell versions seem to have the same optimization policies by default:

    ><((°> /usr/local/bin/ccl64
    Welcome to Clozure Common Lisp Version 1.11-r16635  (DarwinX8664)!

    COMMON-LISP-USER> (defmacro policy (&environment env)
    `',(ccl:declaration-information 'optimize env))

    (policy)POLICY
    COMMON-LISP-USER>
    ((SPEED 1) (SAFETY 1) (COMPILATION-SPEED 1) (SPACE 1) (DEBUG 1))
    COMMON-LISP-USER> ⏎

    ><((°> ros -L ccl-bin run
    Welcome to Clozure Common Lisp Version 1.11-r16635  (DarwinX8664)!

    ? (defmacro policy (&environment env)
    `',(ccl:declaration-information 'optimize env))

    (policy)POLICY
    ?
    ((SPEED 1) (SAFETY 1) (COMPILATION-SPEED 1) (SPACE 1) (DEBUG 1))
    ?

**Comment by sjl** [comment]
Okay, so after a LOT of digging around tonight with the help of a ton of different people in #lisp I managed to figure out the issue.  It has nothing to do with Roswell so I'm gonna close this, sorry for the noise.

The rough gist of the problem is that one of the libraries I was quickloading was changing the optimization settings in a `declaim`, and the load order was different under different conditions, and so sometimes I would see different performance depending on the order libraries were initially compiled/loaded, which was affected by something else.

The full story would be like a megabyte of IRC logs so let's just leave it at that :)

**Comment by eudoxia0** [comment]
Have you reported this issue to the library? Changing global optimization settings is pretty rude.

**Comment by guicho271828** [comment]
oh it is horrible.
I guess quicklisp needs additional criteria for acceptance: it should not change the global conditions like this. others include: `*macroexpand-hook*, *readtable*, *print-case*` etc.
