### ISSUE TITLE
can't fetch install-for-ci.sh

### ISSUE THREAD

**Issue by macdavid313** [roswell/roswell#143]
In Travis-CI, it keeps reporting this information:

`The command "curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh" failed and exited with 2 during .`

I guess the branch information may be broken or?

**Comment by snmsts** [comment]
It doesn't tell anything other than it fails.
Would you show me the travis-CI log URL that shows the message?

**Comment by macdavid313** [comment]
Well, here's a log file: https://s3.amazonaws.com/archive.travis-ci.org/jobs/123915712/log.txt

**Comment by snmsts** [comment]
I see thanks. I'll fix it.

**Comment by macdavid313** [comment]
oh no problem, we should thank you for bringing Roswell to us :)

**Comment by snmsts** [comment]
Instead of 'release', set ROSWELL_BRANCH to 'v0.0.5.58' might work for now.

**Comment by macdavid313** [comment]
seems still broken :( 
the log is here https://api.travis-ci.org/jobs/124695106/log.txt?deansi=true

**Comment by snmsts** [comment]
```
$ export ROSWELL_BRANCH=release
```

hm... please fix it once.

**Comment by macdavid313** [comment]
Hi, sorry for the late reply, too busy at work. 

And thanks, that fix the problem, but for the following projects, do we have to set a specific branch?

**Comment by snmsts** [comment]
for now.

**Comment by macdavid313** [comment]
Yeah I guess so :)
