### ISSUE TITLE
The appveyor builds for Windows are failling

### ISSUE THREAD

**Issue by mpsyco** [roswell/roswell#147]
The builds for Windows on [appveyor](https://ci.appveyor.com/project/snmsts/roswell-en89n/history) are all "failed" for the last three months (since [this one](https://ci.appveyor.com/project/snmsts/roswell-en89n/build/1.0.119) at least).

**Comment by snmsts** [comment]
I know...

**Comment by mpsyco** [comment]
Do you have an idea how to fix it? Or how could somebody help to fix it?
I don't use (yet) roswell on any linux box because OS package-manager + quicklisp is awesome for mosts task. But on windows, I never really bothered because of the setup it requires (lisp + emacs + slime + a non-crappy shell + a non-crappy terminal, etc.).

So, maybe one day I may have some motivation to fix this issue, but maybe it will be somebody else.
But how one could/should start this digging the issue?

**Comment by snmsts** [comment]
Unfortunately there are no clear path to fix it.
test and find error or bug and fix it then repeat is what I'll do.

I respect your idea of not using roswell.
Thanks.

**Comment by snmsts** [comment]
Implementing download retry looks fix the issue.

**Comment by mpsyco** [comment]
It started failling again 5 days ago:

![roswell-appveyor-fail](https://cloud.githubusercontent.com/assets/2881922/15995476/f4af534c-30e9-11e6-9ce0-24838c19b5a0.PNG)

**Comment by mpsyco** [comment]
Based on [this](https://github.com/appveyor/ci/issues/403), I have changed the link in the wiki to point directly to the latest working builds. So... I will probably never notice again if it fails in the future :stuck_out_tongue: 

I think it is a big step toward a better user experience for Window users.
