### ISSUE TITLE
ros setup cannot allocate memory

### ISSUE THREAD

**Issue by leongithub** [roswell/roswell#149]
error:

> While evaluating the form starting at line 71, column 0
>   of #P"/usr/local/share/common-lisp/source/roswell/util.lisp":
> Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
>                                     {100295F603}>:
>   Couldn't fork child process: cannot allocate memory

environment:
Debian 7.0 x86_64  VPS  RAM 512

I run local sbcl: sbcl --dynamic-space-size 256

Can i run roswell on my vps?

Thanks!

**Comment by snmsts** [comment]
I don't understand what you mean... if you want pass that option to sbcl, use ``ros dynamic-space-size=256 run``

**Comment by leongithub** [comment]
Thank you. my English is poor.
Yes, finally i use `ros dynamic-space-size=256 setup` and modify '/usr/local/share/common-lisp/source/roswell/init.lisp' roswell function (change 'args' to '(cons "dynamic-space-size=256" args)')

Thank you.

**Comment by snmsts** [comment]
I'm glad you can fix your problem :+1:
