### ISSUE TITLE
Missing ros-build man page

### ISSUE THREAD

**Issue by mck-** [roswell/roswell#150]
Trying to learn more about how to use `ros build` and reading through the man pages, I realized that this ons seems to be missing.

Also, would love to learn about the benefits of using this vs buildapp.

**Comment by guicho271828** [comment]
For feature comparison, read the following:

https://github.com/roswell/roswell/wiki/0.-What's-the-Difference%3F

**Comment by snmsts** [comment]
the usage of ``ros build`` is just as is written on wiki.
https://github.com/roswell/roswell/wiki/2.0-Reducing-the-Startup-Time

@guicho271828  Would you write man page for ``ros build``?

**Comment by guicho271828** [comment]
shortly

**Comment by guicho271828** [comment]
I checked build.ros, but there is basically no comments. The purpose of this file is not entirely clear for me. Please write comments or something, at least the purposes. I guess it is a shortcut to `dump executable`, which is going to be made obsolete, right?

**Comment by snmsts** [comment]
Thank you for your struggle and sorry for that as well.
The purpose of ``build`` is shortcut.You are right.
But it is introduced after the ``dump`` I never thought it should be obsolete.

**Comment by svetlyak40wt** [comment]
What is the difference between `build` and `dump`?

**Comment by guicho271828** [comment]
https://github.com/roswell/roswell/blob/master/documents/ros-dump.md

**Comment by guicho271828** [comment]
`ros dump executable` == `ros build` : its just a shortcut.
`ros dump output` does not imply `--restart main`. it can be used as an image with possibly multiple entry points, for example

```
ros dump output -l A.lisp -l B.lisp -l C.lisp myimage      # each file contains an entry function a-init, b-init, c-init
ros -m myimage --restart a-init                                          # runs a-init in the toplevel and exit
ros -m myimage --restart b-init                                          # runs b-init in the toplevel and exit
ros -m myimage --restart c-init                                          # runs c-init in the toplevel and exit
```
