### ISSUE TITLE
'ros install sbcl' failed on Kubuntu 16.04

### ISSUE THREAD

**Issue by peterlopen** [roswell/roswell#152]
hi,

peter@dell:~/sw/roswell$ ros install sbcl
Checking version to install....
Using 'sbcl-bin' to compile SBCL. (default)
Skip downloading https://github.com/sbcl/sbcl/archive/sbcl-1.3.6.tar.gz.
Specify 'download.force=t' to download again.

Extracting archive:/home/peter/.roswell/archives/sbcl-1.3.6.tar.gz
     0 ......................................................................
   700 ................................Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                         {1002927603}>:
  Subprocess (:PROCESS #<SB-IMPL::PROCESS :EXITED 2>)
 with command ("/bin/bash" "-lc"
               "cd \"/home/peter/.roswell/src/sbcl-1.3.6/\";/bin/bash ./make.sh '--xc-host=ros lisp=sbcl-bin --no-rc run -- --disable-debugger' '--prefix=/home/peter/.roswell/impls/x86-64/linux/sbcl/1.3.6/'")
 exited with error code 2

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002927603}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10060DE3D3}> #<unavailable argument>)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10060DE3D3}>)
2: (INVOKE-DEBUGGER #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10060DE3D3}>)
3: (CERROR "IGNORE-ERROR-STATUS" UIOP/RUN-PROGRAM:SUBPROCESS-ERROR :COMMAND ("/bin/bash" "-lc" "cd \"/home/peter/.roswell/src/sbcl-1.3.6/\";/bin/bash ./make.sh '--xc-host=ros lisp=sbcl-bin --no-rc run -- --disable-debugger' '--prefix=/home/peter/.roswell/impls/x86-64/linux/sbcl/1.3.6/'") :CODE 2 :PROCESS (:PROCESS #<SB-IMPL::PROCESS :EXITED 2>))
4: (UIOP/RUN-PROGRAM::%CHECK-RESULT 2 :COMMAND ("/bin/bash" "-lc" "cd \"/home/peter/.roswell/src/sbcl-1.3.6/\";/bin/bash ./make.sh '--xc-host=ros lisp=sbcl-bin --no-rc run -- --disable-debugger' '--prefix=/home/peter/.roswell/impls/x86-64/linux/sbcl/1.3.6/'") :PROCESS (:PROCESS #<SB-IMPL::PROCESS :EXITED 2>) :IGNORE-ERROR-STATUS NIL)
5: ((FLET #:CLEANUP-FUN-16 :IN UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM)) [cleanup]
6: ((LAMBDA (UIOP/RUN-PROGRAM::REDUCED-INPUT UIOP/RUN-PROGRAM::INPUT-ACTIVITY) :IN UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM) NIL NIL)
7: (UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM ("/bin/bash" "-lc" "cd \"/home/peter/.roswell/src/sbcl-1.3.6/\";/bin/bash ./make.sh '--xc-host=ros lisp=sbcl-bin --no-rc run -- --disable-debugger' '--prefix=/home/peter/.roswell/impls/x86-64/linux/sbcl/1.3.6/'") :INPUT NIL :ERROR-OUTPUT NIL :IF-INPUT-DOES-NOT-EXIST :ERROR :IF-OUTPUT-EXISTS :OVERWRITE :IF-ERROR-OUTPUT-EXISTS :OVERWRITE :ELEMENT-TYPE :DEFAULT :EXTERNAL-FORMAT :UTF-8 :OUTPUT T :IGNORE-ERROR-STATUS NIL)
8: (ROS.INSTALL::SBCL-MAKE (:TARGET "sbcl" :VERSION "1.3.6" :ARGV NIL))
9: (INSTALL-IMPL "sbcl" NIL "install" NIL)
10: (MAIN "install" "sbcl")
11: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROS:*ARGV*) #<NULL-LEXENV>)
12: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROS:QUIT (APPLY (QUOTE MAIN) ROS:*ARGV*)) #<NULL-LEXENV>)
13: (SB-EXT:EVAL-TLF (ROS:QUIT (APPLY (QUOTE MAIN) ROS:*ARGV*)) NIL NIL)
14: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROS:QUIT (APPLY (QUOTE MAIN) ROS:*ARGV*)) NIL)
15: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {1003B2D973}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
16: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {1003B2D973}> NIL)
17: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {1003B2D973}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
18: ((FLET ROS::BODY :IN ROS:SCRIPT) #<SB-SYS:FD-STREAM for "file /usr/local/etc/roswell/install.ros" {1003B28AC3}>)
19: (ROS:SCRIPT :SCRIPT "/usr/local/etc/roswell/install.ros" "install" "sbcl")
20: (ROS:RUN ((:SCRIPT "/usr/local/etc/roswell/install.ros" "install" "sbcl") (:QUIT NIL)))
21: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROS:RUN (QUOTE ((:SCRIPT "/usr/local/etc/roswell/install.ros" "install" "sbcl") (:QUIT NIL)))) #<NULL-LEXENV>)
22: (EVAL (ROS:RUN (QUOTE ((:SCRIPT "/usr/local/etc/roswell/install.ros" "install" "sbcl") (:QUIT NIL)))))
23: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/etc/roswell/init.lisp\"))") (:EVAL . "(ros:quicklisp)") (:EVAL . "(ros:run '((:script \"/usr/local/etc/roswell/install.ros\"\"install\"\"sbcl\")(:quit ())))")))
24: (SB-IMPL::TOPLEVEL-INIT)
25: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SB-EXT:SAVE-LISP-AND-DIE))
26: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting

thank you.
regards,
peter

**Comment by peterlopen** [comment]
sudo apt-get install zlib1g-dev
fixes it.

**Comment by luoxing91** [comment]
thanks, in centos should execute 'sudo yum install zlib-devel'

**Comment by guicho271828** [comment]
Added these info to the Wiki.
