### ISSUE TITLE
Sourceforge sbcl-bin download should use https

### ISSUE THREAD

**Issue by Immortalin** [roswell/roswell#161]

**Comment by snmsts** [comment]
why?

**Comment by eudoxia0** [comment]
Because someone could MITM the HTTP download and replace it with a malicious copy of SBCL.

**Comment by snmsts** [comment]
OK, If so, Are there any way to keep connection https?
Sourceforge download link seems always redirect to http uri.
the reason to keep it secure doesn't make sense for me.

**Comment by Hexstream** [comment]
SourceForge has been known to literally [INFECT DOWNLOADS AND BINARIES WITH MALWARE](https://en.wikipedia.org/wiki/SourceForge#Controversies) (and more), so I guess `https` is the least of concerns...

**Comment by snmsts** [comment]
It's not my business.
If your concern is Sourceforge itself. You should consult the problem with SBCL maintainers not me.
I'll follow SBCL upstream change immediately.

Again, so far what I know about Sourceforge's https URI is just redirected to other http server address.
MITM attack is still possible and I don't have any idea to prevent MALWARE.

What's the point?
It's OK to change but so far I believe practically no benefit.

**Comment by Immortalin** [comment]
It is an automatic safeguard for the future I.e. if source forge changes to HTTPS, all users of Roswell will be protected by default.

**Comment by Immortalin** [comment]
fixed by #163
