### ISSUE TITLE
Can't open ros.exe on windows

### ISSUE THREAD

**Issue by ailisp** [roswell/roswell#164]
It shows ros.exe has stopped working dialog when run ros.exe

**Comment by snmsts** [comment]
Thanks to reporting.

Where did you find the message?
Please provide information enough to reproduce the bug.

**Comment by ailisp** [comment]
Sorry, I think it's my network connection error when first run roswell and it download fails. When running ros.exe again it will show up ros.exe has stopped working dialog. After deleting `.roswell` in the home directory it will just work. I think roswell initialization may be more strong if add a recovery from broken `.roswell` directory.

**Comment by ailisp** [comment]
The `ros install ccl-bin` seems don't work on windows. I have runed `ros setup` and install ZIP package in quicklisp via `ros install ZIP`. The error information is as following:
```
E:\roswell>ros install ccl-bin
;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Package ZIP does not exist.
;
;       Line: 64, Column: 37, File-Position: 2912
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file E:\\roswell\\lisp\\ins
ll-ccl-bin.lisp" {253B69E1}>
;
; compilation unit aborted
;   caught 3 fatal ERROR conditions
;   caught 1 ERROR condition
'ccl-bin' is not a valid target for 'install' -- It should be a name of either
+ a quicklisp-installable system
+ a common lisp installation
```

**Comment by snmsts** [comment]
Thank you again.
it's different topic.
I close this issue first.
