### ISSUE TITLE
ros install ccl-bin problem on windows.

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#165]
The `ros install ccl-bin` seems don't work on windows. I have runed `ros setup` and install ZIP package in quicklisp via `ros install ZIP`. The error information is as following:

```
E:\roswell>ros install ccl-bin
;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Package ZIP does not exist.
;
;       Line: 64, Column: 37, File-Position: 2912
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file E:\\roswell\\lisp\\ins
ll-ccl-bin.lisp" {253B69E1}>
;
; compilation unit aborted
;   caught 3 fatal ERROR conditions
;   caught 1 ERROR condition
'ccl-bin' is not a valid target for 'install' -- It should be a name of either
+ a quicklisp-installable system
+ a common lisp installation
```

reported by @ailisp #164

**Comment by snmsts** [comment]
the phenomena itself is already fixed... but,

see uris

http://ccl.clozure.com/ftp/pub/release/1.10/ccl-1.10-windowsx86.zip
http://ccl.clozure.com/ftp/pub/release/1.11/ccl-1.11-windows.zip

terrible... huh?

**Comment by ailisp** [comment]
Thanks. It's annoying to keep track on these kind of changes in name.

2016年12月25日 上午2:28，"SANO,Masatoshi" <notifications@github.com>写道：
