### ISSUE TITLE
Choosing image (-m option) does not work

### ISSUE THREAD

**Issue by mobius-eng** [roswell/roswell#168]
The following command:

```
ros -L sbcl-bin -m lisp-image.core run
```

does not pick up the saved image `lisp-image.core` and loads the default image instead.

Tested on Ubuntu 16.04

**Comment by snmsts** [comment]
use ``ros dump`` to make a image for ``-m`` see ``ros help dump`` or ``man ros-dump``

**Comment by mobius-eng** [comment]
Thanks! I figured that roswell has a specific location for images. Perhaps the help line on `-m` should be amended a bit to prevent this kind of confusion?

**Comment by snmsts** [comment]
Thank you for your sugestion :)
hmm. I'm not good at English...

What would be good to prevent confusion and keep it short.

btw, pull requests are always welcomed. ;)

https://github.com/roswell/roswell/blob/master/lisp/help.ros#L17
