### ISSUE TITLE
How to build from source on CentOS/RHEL 5 and 6

### ISSUE THREAD

**Issue by leuler** [roswell/roswell#172]
Hi,

roswell doesn't build out of the box on these distributions as the automake version there is too old. I was able to build it nevertheless by changing
`AC_PREREQ([2.65])`
to
`AC_PREREQ([2.59])`
in configure.ac.

Please consider making this change in your sources -- I guess the features that the never automake versions provide are not needed for roswell.

Also, in case someone else wants to build on these distributions, here are the packages that I needed to install to be able to build roswell:

On RHEL/CentOS 5:
`# yum install git curl-devel zlib-devel`

On RHEL/CentOS 6:
`# yum install git libcurl-devel zlib-devel`

The architecture I used was x86-64.

Thanks and greetings,

Lutz

**Comment by snmsts** [comment]
Thanks applied
1c3bb62e7871e5d0d133c07498da5c7e6d0a79fc
