### ISSUE TITLE
Cannot use allegro on Travis

### ISSUE THREAD

**Issue by ssaavedra** [roswell/roswell#173]
I am trying to build a .travis.yml file for my Common Lisp project, and I'm using https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh for installing roswell in Travis.

However, if I try to use the allegro compiler, the build fails saying it cannot find alisp (but the file exists).

I made a branch in my project demonstrating the failure. The full build logs are available at: https://travis-ci.org/cavi-art/cl-clir2mlw/jobs/158200799

In short:

```
$ ros install allegro
Installing allegro/100express...
Downloading archive:http://www.franz.com/ftp/pub//acl100express/linux86/acl100express-linux-x86.bz2
Downloading http://www.franz.com/ftp/pub//acl100express/linux86/acl100express-linux-x86.bz2
[##########################################################################]100%
Extracting archive:/home/travis/.roswell/archives/acl100express-linux-x86.bz2
up to date. stop

$ ls -la ~/.roswell/impls/x86-64/linux/allegro/100express/ || true
total 84148
drwxr-xr-x 22 travis travis     4096 Aug 15 17:49 .
drwxrwxr-x  3 travis travis     4096 Sep  7 14:47 ..
drwxr-xr-x  3 travis travis     4096 Aug 15 17:48 acache
-rwxr-xr-x  1 travis travis  7750608 Sep 10  2015 acli100413.tpll
-rwxr-xr-x  1 travis travis  2329073 Sep 10  2015 aclissl.so
-rwxr-xr-x  1 travis travis  2329073 Sep 10  2015 aclssl.so
-rwxr-xr-x  1 travis travis    38616 Sep 10  2015 alisp
-rw-r--r--  1 travis travis  4931584 Aug 15 17:48 alisp.dxl
-rwxr-xr-x  1 travis travis    38616 Sep 10  2015 allegro-express
-rw-r--r--  1 travis travis 21528576 Aug 15 17:48 allegro-express.dxl
-rw-r--r--  1 travis travis 16681952 Sep 10  2015 allegro-express.pll
drwxr-xr-x 12 travis travis     4096 Aug 15 17:48 ansicl
drwxr-xr-x  2 travis travis     4096 Aug 15 17:48 bin
-rw-r--r--  1 travis travis    16723 Jun 11  2015 cg-obsolete.cl
-rw-r--r--  1 travis travis   234565 Jun 11  2015 cgtree.cl
[...]

$ ros config set default.lisp allegro

$ ros run -- --version
/home/travis/.roswell/impls/x86-64/linux/allegro/100express/alisp is not exist.stop.
```

**Comment by ssaavedra** [comment]
This issue also exists with container-based builds: https://travis-ci.org/cavi-art/cl-clir2mlw/jobs/158206417 (the former report was for the old-style `sudo:required` builds).

It fails with the same error message and the same behavior. Maybe I'm missing something, but I don't realize what it can be.

**Comment by fukamachi** [comment]
I also can reproduce it at https://travis-ci.org/fukamachi/quri/jobs/156991406.
It seems it's the bug of Roswell core with Linux.

```
$ ros --version
roswell 0.0.6.65(9b667a2)
$ ros install allegro
$ ros use allegro
/home/nitro-idiot/.roswell/impls/x86-64/linux/allegro/100express/alisp is not exist.stop.
Error: unable to use 'allegro'
$ ls -l ~/.roswell/impls/x86-64/linux/allegro/100express/alisp
-rwxr-xr-x 1 nitro-idiot nitro-idiot 38616 Sep 11  2015 /home/nitro-idiot/.roswell/impls/x86-64/linux/allegro/100express/alisp
$ ~/.roswell/impls/x86-64/linux/allegro/100express/alisp
-bash: /home/nitro-idiot/.roswell/impls/x86-64/linux/allegro/100express/alisp: No such file or directory
```

The file exists, however, it won't run.

**Comment by snmsts** [comment]
Thank you for reporting @ssaavedra . and notice again @fukamachi .

hm... I notice it's bug..

https://travis-ci.org/snmsts/quri/builds/158231905
https://github.com/fukamachi/quri/compare/master...snmsts:travis-test?expand=1

by this experiment I understand why,I'll fix it later.

and I hope you'll know how you could avoid it as well.

Thank you.

**Comment by ssaavedra** [comment]
I understand.

Then, for container-based Travis builds, this excerpt needs to be added to `.travis.yml` (and it can also be used in traditional trusty builds instead of "sudo apt-get"):

```yaml

addons:
  apt:
    packages:
      - libc6-i386
```

This should get into the roswell documentation. It's possible to run roswell in Travis although it seems not to be very well documented how.

**Comment by snmsts** [comment]
https://github.com/roswell/roswell/wiki/4.1-Travis-CI ?

**Comment by ssaavedra** [comment]
o.o, you are right. It's clearly well documented, and I don't know why or how I didn't come across that page. I sent you a PR making some links in the README; and hopefully make that information a bit more easily reachable.

I think we can close this issue, it was on my end. Although, maybe we should update the install-for-ci.sh script also installing libc-i386 on those cases, I can also send you a PR on that if you agree.

**Comment by fukamachi** [comment]
install-for-ci.sh used to install `libc6-i386`, however, the line was deleted at https://github.com/roswell/roswell/commit/592c962308f2cb1f6a01fa4a944b390262a1c942#diff-cf5094785ea43f139ee822996e58a49cL121, maybe because Allegro CL is officially supported by Roswell core.

Perhaps the package should be installed when installing Roswell or `ros install allegro`?

**Comment by snmsts** [comment]
@fukamachi I'm sorry it's my mistake my CI environment always runs with `libc6-i386` so I didn't notice my braking the script.I'll make the script install libc6-i386 again.

**Comment by ssaavedra** [comment]
Not sure, but roswell should not know which package managers are in use and should not have that responsability, so on `ros install allegro` it's difficult to support it portably.

Also, the package is not used by Roswell, which can be compiled in a x86_64 architecture without the 32bit libs, so it does not really make sense to require it as a dependency for roswell as a package (maybe as a recommended install, to support allegro and other 32bit lisps).

In my opinion, the best place to install libc6-i386 is on the install-for-ci script, so that it only gets installed if needed (or, in the case of `sudo:false` it *fails* if it has not been installed) for the proper $LISP value.

Definitely, we cannot ensure the package *is* actually installed when configuring or setting up roswell, but we could signal an error on ros install allegro if the 32bit libc is not installed (which is sub-optimal if the install-for-ci script could already have it installed).

I'm not sure which is the better way.

@snmsts I sent PR #175 with those changes.

**Comment by ssaavedra** [comment]
@fukamachi actually, it occurs to me that it's not exclusive, and maybe it's a good idea to *also* have a check on install.lisp, if possible, that we can run 32-bit executables; but I'm not sure how much portable is that.

**Comment by fukamachi** [comment]
I see your point and I think installing libc6-i386 in install-for-ci.sh is reasonable.
