### ISSUE TITLE
ros list versions does not work

### ISSUE THREAD

**Issue by ssaavedra** [roswell/roswell#178]
After installing roswell, `ros list versions` should output a list of available compilers to install. However, it outputs just the following text:

```
Installable versions for sbcl-bin:
script #P"/etc/roswell/install.lisp" does not exist
```

It seems I'm missing an install.lisp, but I cannot find it. I can only find an install.ros, but I'm not sure if it is the same file.

Incidentally, install.ros does not get installed by roswell if I do so from a Fedora specfile, available currently at https://gist.github.com/ssaavedra/335b404a7c8859aacb682000eaac9ab9.
I had to comment the line because the file does not actually exist (but I had put it before in case it did to include it in the installable RPM).

**Comment by snmsts** [comment]
`install.lisp` was renamed and It doesn't  tested. :( 

I'll fix it soon.

**Comment by snmsts** [comment]
fixed

**Comment by ssaavedra** [comment]
I just tested and it works.
I'm closing the issue then.
