### ISSUE TITLE
ros install -> ros clone : too "multi-purpose"

### ISSUE THREAD

**Issue by guicho271828** [roswell/roswell#179]
Ability to install something on github is yes actually useful, but ros install has too many features no?
Features like `ros install <username>/<reponame>` might better be named separately, and `ros clone` would capture the meaning more appropriately.

**Comment by guicho271828** [comment]
Also I would like to make it accept arbitrary git repository URLs. Does it already work?

**Comment by snmsts** [comment]
I'd like to use ``ros install <username>/<reponame>`` for installing implementations as well. ``roswell/jscl`` is an example. If you feel ``ros install`` and ``ros clone`` should be separated, I believe it should be failure of abstraction.
I'd like to support ``mkcl`` soon. but I don't plan modify this repository anymore.Just create ``roswell/mkcl`` and I'd improve install facilities. 

>> it accept arbitrary git repository URLs

It would be nice. I don't work on it yet.

**Comment by guicho271828** [comment]
that ＵＲＬ feature would be useful for giyhub enterprise

**Comment by guicho271828** [comment]
> I believe it should be failure of abstraction.
I don't get it ---- do you mean you agree with me and you want to separate it, or do you think `ros clone` is not good idea?

**Comment by snmsts** [comment]
sorry. I disagree with you partially. ``ros install user/project`` would do some extra tasks. load the project (and do some chore by loading) and copy ros files in project's ``roswell`` directory to ``.roswell/bin``.

I agree with you,in a sense it might be good to just checkout/clone/get remote repositories to somewhere and do nothing  with it.

**Comment by guicho271828** [comment]
Okay that makes sense so the cloning and installing is not completely the same thing. In that case cloning doesn't accurately describe the functionality....

**Comment by snmsts** [comment]
Related issue should be discussed.

- `ros install` should support git repo which isn't github.
- new subcommand name for pull/copy/checkout should be decided.
- what kind of uri should be used to specify which versioning system to be used.

hmm.

**Comment by guicho271828** [comment]
maybe worth trying all possible measures until it succeeds?
