### ISSUE TITLE
Roswell with atom-slime?

### ISSUE THREAD

**Issue by tamamu** [roswell/roswell#180]
I try to use roswell for Atom's plugin, atom-slime.
I set Lisp Process section: `ros -L sbcl -Q run`, but it doesn't work.

Can I use roswell with atom-slime?

**Comment by snmsts** [comment]
I guess not...

**Comment by snmsts** [comment]
wrote pull request https://github.com/sjlevine/atom-slime/pull/46

**Comment by tamamu** [comment]
Thanks.

**Comment by snmsts** [comment]
Thank you for your report.

I'll close this issue when atom-slime support it.

**Comment by snmsts** [comment]
was merged.
