### ISSUE TITLE
Ros install does not build installed script

### ISSUE THREAD

**Issue by can3p** [roswell/roswell#188]
Roswell has a build step, however afaik it's not used when system is installed with `ros install some/repo`

Is there any specific reason for this? I would expect this step to happen because program startup time is so much faster after it.

**Comment by snmsts** [comment]
do you mean ros script in git repo should be build?

**Comment by can3p** [comment]
Yes, at least it was my expectation. I assumed that if `ros install` results in file in a bin folder so that you can run it right away, it will be even better if roswell makes a symbolic link to a built script to make things faster

**Comment by snmsts** [comment]
hmm..

It is not automatic but dump facility will do your expectation.
See the technique used in lake.

https://github.com/takagi/lake/tree/master/roswell

**Comment by snmsts** [comment]
So far I'm not sure roswell should optimize it for speed or size.

**Comment by guicho271828** [comment]
additional field in ros.config ?

**Comment by snmsts** [comment]
@guicho271828 
It should be option for each scripts.

FYI
https://github.com/roswell/roswell/issues/53

**Comment by guicho271828** [comment]
+ Providing an API to programatically access `ros build` from inside the script

**Comment by snmsts** [comment]
hm..

**Comment by mpsyco** [comment]
guico271828
> additional field in ros.config ?

snmsts:
> It should be option for each scripts.

Why not both? Each script having its config. But fallback to the one in ros.config if its not specified by the script.

**Comment by snmsts** [comment]
use ``-m`` for each of installed script. install executable is not my intended design.

**Comment by guicho271828** [comment]
> use -m for each of installed script. install executable is not my intended design.

This should be more elaborated on the Wiki.
