### ISSUE TITLE
Download Failed with status 2

### ISSUE THREAD

**Issue by kisp** [roswell/roswell#190]
I am having trouble with https://github.com/roswell/roswell/blob/master/scripts/install-for-ci.sh in this build job https://travis-ci.org/kisp/gdid/jobs/176688346.

Not sure how to turn on verbose in roswell for further debugging.

**Comment by snmsts** [comment]
you should use https://github.com/roswell/roswell/blob/release/scripts/install-for-ci.sh

**Comment by kisp** [comment]
Thank you very much! That fixes it for me.
