### ISSUE TITLE
version schema

### ISSUE THREAD

**Issue by dunn** [roswell/roswell#193]
Why did the version suddenly jump from `v0.0.6.69` to `v16.11.7.70`?  I'm only concerned because if that was a mistake and the next version is back to `v0.0.x`, some package managers' version detection will be confused.

**Comment by snmsts** [comment]
it's not mistake.
https://github.com/roswell/roswell/commit/823daa2bace0dca2cd8eb954318eff8005b98eaf

**Comment by dunn** [comment]
Great, thank you!
