### ISSUE TITLE
Don't enter debugger in TravisCI (exit with non zero status instead ?)

### ISSUE THREAD

**Issue by avodonosov** [roswell/roswell#194]
Both the -s and -e options to ros , when hey fail they allow lisp implementation to enter debugger.

Here CLISP enters debugger when it can't load bordeaux-threads because CLISP doesn't have ASDF 3:
- a case with `ros -s cl+ssl.test`: https://travis-ci.org/cl-plus-ssl/cl-plus-ssl/jobs/181217278
- a case with `ros -e '(ql:quickload :cl+ssl.test)'`: https://travis-ci.org/cl-plus-ssl/cl-plus-ssl/jobs/181539210

I was trying to `-e (handler-case (ql:quickload :cl+ssl.test) (serious-condition () (uiop:quit 1))` but uiop is unknown to CLISP due to old ASDF.

Still I think it's worth to look for a solution and exit with non-zero code instead of keeping TravicCI machine occupied until timeout.

**Comment by snmsts** [comment]
hmmm. I guess you can use ``(ros:quit 1)`` instead of ``uiop:quit``.

**Comment by avodonosov** [comment]
Thanks for the advice. Can rowsell help install and load new ASDF when running TravisCI with CLISP

**Comment by snmsts** [comment]
Yes.I should write I'll change API. it's not stable at all yet but on master branch
``ros asdf install`` will introduce new asdf and ``(ros:ensure-using-downloaded-asdf)`` would load asdf.

**Comment by snmsts** [comment]
``(ros:asdf)``  is the API to use downloaded ASDF now.
