### ISSUE TITLE
loading system via (ql:quickload ... :silent t) breaks some functionality

### ISSUE THREAD

**Issue by avodonosov** [roswell/roswell#195]
As you see in this TravisCI build log of cl-plus-ssl on ECL, it fails during cffi-grovel with error 
> :OUTPUT argument to RUN-PROGRAM does not have a file handle:
> #<broadcast stream 00000000038cd5a0>.

https://travis-ci.org/cl-plus-ssl/cl-plus-ssl/jobs/181217279

This happens because we are loading the cl+ssl.test with `ros ...  -s cl+ssl.test ...` which loads the system using `(ql:quickload ... :silent t)` : https://github.com/roswell/roswell/blob/8edb8fb36f9115c2f5b7387484d2abf24bbf6702/lisp/init.lisp#L276

`:silent t` is implemented in Quicklisp by binding `*standard-output*` and `*standard-trace*` to a dummy broadcast-stream: 
https://github.com/quicklisp/quicklisp-client/blob/3377414539e5fda49d8aa60ec195beed56ca83c6/quicklisp/client.lisp#L21

https://github.com/quicklisp/quicklisp-client/blob/3377414539e5fda49d8aa60ec195beed56ca83c6/quicklisp/client.lisp#L31

cffi-grovel passes `*standard-output*` to run-program via `(run-program :output t)`, but on ECL a broadcast-stream can't not be used as a target for run-program output, because it doesn't have a file descriptor.

Therefore build fails.

As a workaround I've replaced `ros ...  -s cl+ssl.test ...` with `ros ...  -e '(ql:quickload :cl+ssl.test)' ...`.

I also suggest to fix that in roswell by removing the `:silent t` key from the `ql:quickload` call

**Comment by snmsts** [comment]
hmm...

I prefer not too verbal by default.
Do you think it's acceptable when with passing ``-v`` to roswell would change ``:silent t`` to ``:silent nil``?

**Comment by avodonosov** [comment]
I don't know. I prefer as much information as possible. But whether it's by default or via option is not very important. 

In case of `siltent :t` I think it makes sense to have a warning on ECL.

**Comment by snmsts** [comment]
done.
