### ISSUE TITLE
Different *package* values when running a script directly vs. building it.

### ISSUE THREAD

**Issue by TeMPOraL** [roswell/roswell#196]
Set up a simple script with `ros init foo`.
Add a following line to the generated `main` function:
```lisp
(print *package*)
```

Output after running the script directly with `./foo.ros` will be something like `#<PACKAGE "ROS.SCRIPT.FOO.some-number">`. After building it with `ros build foo.ros`, the result of executing `./foo` is `#<PACKAGE "COMMON-LISP-USER">`.

I feel this isn't valid/expected behaviour.

---

`ros version` output:
```
roswell 16.11.7.70(681dda9)
build with gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
libcurl=7.35.0
Quicklisp=2016-02-22
Dist=2016-10-31
lispdir='/usr/local/etc/roswell/'
configdir='/home/temporal/.roswell/'
```
`ros list installed` lists `sbcl-bin/1.3.4`.

**Comment by snmsts** [comment]
Thank you!
