### ISSUE TITLE
Error running ABCL with quicklisp

### ISSUE THREAD

**Issue by Chream** [roswell/roswell#203]
$ ros -L abcl-bin run

Caught FILE-ERROR while processing --eval option "(ros:run '((:eval"(ros:quicklisp)")))":
  Bad place for a wild pathname.

**Comment by snmsts** [comment]
It doesn't occur my environment.
show me,

```
ros config
```

and

```
ros version
```

**Comment by Chream** [comment]
Sorry I didnt reply to this. I got it working at some point. Did a full reinstall of roswell and all implementations.

**Comment by snmsts** [comment]
Thank you.
