### ISSUE TITLE
eliminate options

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#206]
below are options which I borrowed from [cl-launch](http://www.cliki.net/cl-launch) but I think it's incompatible with idea of ros script.

```
   -r  FUNC     --restart FUNC       restart from build by calling (FUNC)
   -E  FUNC     --entry FUNC         restart from build by calling (FUNC argv)
   -i  FORM     --init FORM          evaluate FORM after restart
   -ip FORM     --print FORM         evaluate and princ FORM after restart
   -iw FORM     --write FORM         evaluate and write FORM after restart
   -F  FORM     --final FORM         evaluate FORM before dumping IMAGE
```

I'm thinking about stop supporting those options from next version.
Does anyone annoyed from this decision?

**Comment by guicho271828** [comment]
It would be better be kept unless it is preventing you from refactoring the code. the feature serves as a strong incentive for people using cl-launch, if any, to stop using it and migrate to roswell.

**Comment by snmsts** [comment]
Sure, but don't want you to be aggressive to cl products like cl-launch.
We should be to different language products like npm/leiningen/go. ;)

Basically I don't care about command line compatibility with cl-launch. I believe it shouldn't be big deal for cl guys.

- It already differs and there should be some pitfalls.(I don't even check those are compatible or not)
- I don't use them and not sure it works or not. I don't have plan to use it in the future as well. so keeping them is not good plan for me.
- ``ros build`` should support those functionality.

what I intended to ask here is,are there someone already taking advantage of these options and have problem if those are eliminated.

I count @guicho271828 is not that kind of person. are you?

**Comment by guicho271828** [comment]
No, personally the change does not matter to me because I don't use cl-launch compatibility.

**Comment by snmsts** [comment]
just not show options from January release.
