### ISSUE TITLE
Don't overwrite existing files when building

### ISSUE THREAD

**Issue by libre-man** [roswell/roswell#208]
I wrote a simple script using roswell as I'm in the process of replacing not so trivial bash scripts with lisp. However it was quite annoying that I had to rewrite one because I didn't pay attention to naming it script.ros. So when running `ros build script` my script got truncated.

I understand that this behavior is somewhat documented and it is the same behavior `gcc` and `clang` have, however those pieces of software are not really renowned for their friendliness.

I think it would be saner to check if the output file exists and only make it possible to overwrite this with a `--hard` flag or something. Maybe paying extra caution if the output is the same as the input as this will probably never work as intended.

**Comment by fstamour** [comment]
I agree.

**Comment by snmsts** [comment]
I don't want to add more options for that purpose.

**Comment by libre-man** [comment]
I think it would be way better than what we have right now. I still would also like to see some kind of error we can overwrite so that users don't accidentally overwrite over files.

**Comment by snmsts** [comment]
@libre-man see 6bbdc23.
