### ISSUE TITLE
Is it possible to define a roswell github install target as an asdf dependency?

### ISSUE THREAD

**Issue by ahungry** [roswell/roswell#210]
For instance, if I want to depend on https://github.com/ahungry/ahungry-fleece, I can `ros install ahungry/ahungry-fleece`, but how can I then use that package as a dependency of another package?  Or even re-use the core that has loaded it?

**Comment by snmsts** [comment]
If you are using roswell 16.12.8.72, 
I believe you can use ``:depends-on ("ahungry/ahungry-fleece")`` on asd file.

feed back and bug reports are welcomed. please try :)

**Comment by ahungry** [comment]
Awesome, thanks!
