### ISSUE TITLE
"ros" command on Mac

### ISSUE THREAD

**Issue by cidj** [roswell/roswell#212]
Hi, I'm a beginner to use roswell. I encountered an issue when I try to use roswell command on my macbook pro. Here is what I did:

First, I use Homebrew to install roswell, so I input this in the terminal:
**brew install roswell**

It succeed. And I use the following command to see what would happen:
**ros**
The screen showed, some version of SBCL was being downloaded, and a increasing percentage was on the command line. However, I've already had a SBCL installed in my mac, which may not be the newest version. I thought I didn't need to install a new one. So before the downloading process was completed, I closed the terminal window thus interrupted the process.

After a while, I changed my mind, I think I should've let it run to see what would happen. So I open a terminal again and input:
**ros**
However, this time, it failed, it showed only a line:
**1327 fragmentation fault**
Why did this happen? Were there some files that were downloaded before preventing the command from running?

I didn't know how to deal with it. I don't know how to clean the maybe incomplete files (I'm not familiar with Mac OS, either). I use Onxy to clean the Caches of the computer, and restart it. After that, when I input:
**ros**
The respond is
**403 fragmentation fault**
It seemed the number decreased here. But it didn't work, either.

I tried to uninstall roswell, using:
**brew remove roswell**
and
**brew uninstall roswell**
and cleanup:
**brew cleanup**
It showed a warning that "SBCL was not installed"(I can't remember exactly, but it's kind like this)

However, when I reinstalled roswell and type:
**ros**
It still showed
**1003 fragmentation fault**

So could you tell me is there a way to clean my computer system so I can install Roswell and SBCL again without error?

Thank you in advance!

**Comment by cidj** [comment]
All the numbers are not exact, such as 403, 1003. But they're not too much different from what I saw on my computer yesterday.

**Comment by snmsts** [comment]
fragmentation? I believe it should be segmentation...
Please don't trust your memory as much as possible.please copy & paste to report.
I understand some of errors are already impossible to reproduce and logs are gone already but the part you mention 'still showed' part you can copy.

anyway..What you should do to reset roswell's installation

```
rm -rf ~/.roswell
```

I think it should have other problems If you still met problem. I'd like to know to solve it.
feel free to report :)

**Comment by cidj** [comment]
Hi, snmsts,

Thank you very much. As you said, it's segmentation, not fragmentation. And, I followed your instruction, use
**rm -rf ~/.roswell**
And everything goes well. The issue no longer exists. I don't know why. But I think I can use roswell now. Thank you for your kind help!

The following is what appeared on my screen:)


**************************************************************
➜  ~ ➜  ~ rm -rf ~/.roswell
➜  ~ brew install roswell
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
ammonite-repl              influxdb                   qbs
apktool                    kapacitor                  stormpath-cli
caddy                      khal                       telegraf
collectd                   libosmium                  tin
dnscrypt-proxy             link-grammar               vapoursynth
extract_url                mcabber                    vim
fzf                        pgformatter                youtube-dl
gitlab-ci-multi-runner     prometheus
groonga                    pushpin

==> Downloading https://homebrew.bintray.com/bottles/roswell-16.12.8.72.sierra.b
Already downloaded: /Users/tao/Library/Caches/Homebrew/roswell-16.12.8.72.sierra.bottle.tar.gz
==> Pouring roswell-16.12.8.72.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/roswell/16.12.8.72: 70 files, 274.7K
➜  ~ ros
Installing sbcl-bin...
➜  ~ ros
Usage: /usr/local/bin/ros [OPTIONS] [Command arguments...]
Usage: /usr/local/bin/ros [OPTIONS] [[--] script-path arguments...]

Commands:
   run       Run repl
   install   Install a given implementation or a system for roswell environment
   build     Make executable from script.
   use       change default implementation
   init      Creates a new ros script, optionally based on a template.
   list      List Information
   asdf      manage asdf version
   config    Get and set options
   delete    Delete installed implementations
   dump      Dump image for faster startup or Make Executable
   emacs     Launch emacs
   fmt       [WIP] indent lisp source
   help      Show Command help
   setup     Initial setup
   template  [WIP] Manage templates
   version   Show the roswell version information
   wait      Wait forever

Options:
                --version            Print version information and quit
   -w  CODE     --wrap CODE          Run roswell with a shell wrapper CODE,
   -m  IMAGE    --image IMAGE        continue from Lisp image IMAGE
   -M  NAME     --module NAME        Execute ros script found in 'ROSWELLPATH'.(python's -m)
   -L  NAME     --lisp NAME          Run roswell with a lisp impl NAME[/VERSION].
   -l  FILE     --load FILE          load lisp FILE while building
   -S  X        --source-registry X  override source registry of asdf systems
   -s  SYSTEM   --system SYSTEM      load asdf SYSTEM while building
                --load-system SYSTEM same as above (buildapp compatibility)
   -p  PACKAGE  --package PACKAGE    change current package to PACKAGE
   -sp SP       --system-package SP  combination of -s SP and -p SP
   -e  FORM     --eval FORM          evaluate FORM while building
                --require MODULE     require MODULE while building
   -q           --quit               quit lisp here
   -r  FUNC     --restart FUNC       restart from build by calling (FUNC)
   -E  FUNC     --entry FUNC         restart from build by calling (FUNC argv)
   -i  FORM     --init FORM          evaluate FORM after restart
   -ip FORM     --print FORM         evaluate and princ FORM after restart
   -iw FORM     --write FORM         evaluate and write FORM after restart
   -F  FORM     --final FORM         evaluate FORM before dumping IMAGE
   +R           --no-rc              skip /etc/rosrc, ~/.roswell/init.lisp
   -A           --asdf               use new asdf
   +Q           --no-quicklisp       do not use quicklisp
   -v           --verbose            be quite noisy while building
                --quiet              be quite quiet while building (default)
                --test               for test purpose
➜  ~

**Comment by snmsts** [comment]
lgtm

**Comment by guicho271828** [comment]
By the way, I actually do not want to recommend deleting ~/.roswell . The primary reason is that if you have some private libraries that is not being backed up elsewhere in `local-projects` when you delete `.roswell`, then you are messed up.

I don't come up with an easy workaround for this pathology than implementing a full update facility in roswell. If done properly, it would have several separate directories under .roswell which correspond to different versions/hashes of the build, just like python having separate pip directories for each python version, while maintaining a single `.roswell/local-projects` .

**Comment by cidj** [comment]
@guicho271828  
Hi, I strongly support you. You gave a very good suggestion. Haha.
