### ISSUE TITLE
Emacs always starts with default lisp

### ISSUE THREAD

**Issue by svetlyak40wt** [roswell/roswell#214]
Suppose, I have sbcl and ecl installed. Then:

```
# this will setup SBCL as default implementation
ros use sbcl
# now I want to start emacs session with ECL
ros -L ecl emacs
```

But when I start slime in emacs, it starts with SBCL (which was selected as default).
This happens because roswell makes emacs eval `(setq inferior-lisp-program "ros -Q run")` ignoring the given `-L ecl` option.

**Comment by snmsts** [comment]
Sorry for confusing documentation of 'ros help emacs'

'-L' option could work only with 'run','build' and 'dump'. All other are launched with 'sbcl-bin' Don't expect the option to work with other sub commands.

**Comment by snmsts** [comment]
8d367fe6218ffe2a833a811ba23d4693e0b98d1d

**Comment by snmsts** [comment]
my case launch emacs with ``ros emacs`` then ``C-u M-x slime`` and type ``ros -L ecl run`` is the way to try non default lisp.

**Comment by svetlyak40wt** [comment]
Thank you, I understand. But it would be nice to make this option consistent across `run` and `emacs` commands. If you don't mind, I'll send a pull-request which this fix.

**Comment by svetlyak40wt** [comment]
You are the great, @snmsts thank you! :)
