### ISSUE TITLE
clasp build failure

### ISSUE THREAD

**Issue by guicho271828** [roswell/roswell#221]
https://gist.github.com/guicho271828/ba4173d7f2c7382b122136a13bf8863c

**Comment by snmsts** [comment]
hmm...
may be updated `externals.clasp.version` value in `~/.roswell/config` is not accessible from `install-clasp.lisp`

what's happen when you try `ros install clasp` again?

**Comment by guicho271828** [comment]
to make sure everything I removed removed .roswell and trying again

**Comment by snmsts** [comment]
is it finished?

**Comment by guicho271828** [comment]
didnt work, tried building in lib/external-clasp/.../

**Comment by guicho271828** [comment]
> externals.clasp.version value in ~/.roswell/config

config does not have such a value

**Comment by guicho271828** [comment]
btw the build script in external-clasp does not run the builds in parallel, which is awful

**Comment by snmsts** [comment]
> config does not have such a value

meaning it doesn't pass there?

https://github.com/roswell/roswell/blob/5e7907c9ac780e5f85eb103c7f4f65bb36cef160/lisp/install%2Bexternals-clasp.lisp#L50

> btw the build script in external-clasp does not run the builds in parallel, which is awful

it's not my focus.

**Comment by guicho271828** [comment]
pwd
/home/guicho/.roswell/lib/x86-64/linux/externals-clasp/cb00dd0edc7e698162aa176a7d51b9d704bd2596

Building external-clasp failed while compiling LLVM:

```
[ 95%] Building CXX object tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o
/home/guicho/.roswell/lib/x86-64/linux/externals-clasp/cb00dd0edc7e698162aa176a7d51b9d704bd2596/llvm39ToT/tools/gold/gold-plugin.cpp:31:24: fatal error: plugin-api.h: そのようなファイルやディレクトリはありません
compilation terminated.
tools/gold/CMakeFiles/LLVMgold.dir/build.make:62: ターゲット 'tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o' のレシピで失敗しました
make[6]: *** [tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o] エラー 1
```

**Comment by snmsts** [comment]
hm...

**Comment by guicho271828** [comment]
did it work for you or only gos-k has reproduced the successful build?

**Comment by snmsts** [comment]
work for me.

**Comment by guicho271828** [comment]
is it Arch or Mac? Im on Ubuntu 16.04

**Comment by guicho271828** [comment]
.travis.yml does not seem to have a test for clasp

**Comment by snmsts** [comment]
Compile clasp on travis environment in 50 min? Just impossible it's waste of resources. 

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**Comment by snmsts** [comment]
May be your environment lacking some dependencies.

https://github.com/drmeister/clasp/wiki/Clasp-0.5-Build-Instructions

Follow the ``apt install`` part before ``ros install clasp``.

**Comment by guicho271828** [comment]
legit

**Comment by snmsts** [comment]
is it working?

**Comment by snmsts** [comment]
what's up?

**Comment by guicho271828** [comment]
Im looking for how to install waf. As pointed by @gos-k , yes waf was missing.

**Comment by guicho271828** [comment]
um, `waf` seems to be already in the local directory (it doesnt try to use the system-global scripts), so no need to install it. (it is not how waf works anyways)

[guicho ~]$ ros install clasp
Skip downloading https://github.com/drmeister/externals-clasp/archive/cb00dd0edc7e698162aa176a7d51b9d704bd2596.tar.gz
specify download.force=t to download it again.

Extracting archive:/home/guicho/.roswell/archives/externals-clasp-cb00dd0edc7e698162aa176a7d51b9d704bd2596.tar.gz
externals-clasp+/cb00dd0edc7e698162aa176a7d51b9d704bd2596 is already installed. add 'install.force=t' option for the forced re-installation.
building dump:roswell
up to date. stop
git checkout 3f6ffecc31f8d0cc835fe0f87cb88402c95c9519
chdir /home/guicho/.roswell/src/clasp/
     0 ...Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                         {1001BB7383}>:
  Subprocess (:PROCESS #<SB-IMPL::PROCESS :EXITED 2>)
 with command ("/bin/bash" "-lc"
               "cd \"/home/guicho/.roswell/src/clasp/\";./waf configure update_submodules build_cboehm")
 exited with error code 2

**Comment by gos-k** [comment]
@guicho271828 

please give me detail without roswell command.

```
cd $HOME/.roswell/src/clasp/
./waf configure update_submodules build_cboehm
```

**Comment by snmsts** [comment]
sorry. build logs are preserved but not reliable for trouble shooting...

**Comment by guicho271828** [comment]
I don't know why but I removed the .roswell dir and now it succeeded!
```
ros install clasp
Downloading https://github.com/drmeister/externals-clasp/archive/cb00dd0edc7e698162aa176a7d51b9d704bd2596.tar.gz
   4K downloaded.
Downloading archive:https://github.com/drmeister/externals-clasp/archive/cb00dd0edc7e698162aa176a7d51b9d704bd2596.tar.gz:OK

Extracting archive:/home/guicho/.roswell/archives/externals-clasp-cb00dd0edc7e698162aa176a7d51b9d704bd2596.tar.gz
     0 .bell
.....................................................................
   700 ......................................................................
  1400 ......................................................................
  2100 ......................................................................
  2800 ......................................................................
  3500 ......................................................................
  4200 ......................................................................
  4900 ......................................................................
  5600 ....................................................................building dump:roswell
up to date. stop
git clone clasp
git checkout 3f6ffecc31f8d0cc835fe0f87cb88402c95c9519
chdir /home/guicho/.roswell/src/clasp/
     0 ......................................................................
   700 ......................................................................
  1400 ......................................................................
  2100 ......................................................................
  2800 .done.

building dump:roswell
up to date. stop
```

However, later,

```
[guicho ~]$ ros use clasp

Condition of type: UNBOUND-VARIABLE
The variable "QUICKLISP" is unbound.
```

Also, invoking slime,

```
(progn (load "/home/guicho/.roswell/lisp/slime/2017.01.24/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init")) (funcall (read-from-string "swank:start-server") "/tmp/slime.7041"))

Starting Boehm cclasp FRGO_CLASP_DEV_FOREIGN_DATA_002-737-g3f6ffec ... loading image... it takes a few seconds

Condition of type: UNBOUND-VARIABLE
The variable "QUICKLISP" is unbound.
No restarts available.

Top level.
> 
Debugger received error of type: UNBOUND-VARIABLE
The variable "PROGN" is unbound.
Error flushed.
> 
;;; Loading "/home/guicho/.roswell/lisp/slime/2017.01.24/swank-loader.lisp"
Debugger received error of type: FILE-ERROR
Filesystem error with pathname #P"/home/guicho/.roswell/lisp/slime/2017.01.24/swank-loader.lisp".
Either
 1) the file does not exist, or
 2) we are not allowed to access the file, or
 3) the pathname points to a broken symbolic link.
Error flushed.
> 
Debugger received error of type: PACKAGE-ERROR
#<PACKAGE-ERROR>
Error flushed.
> 
Debugger received error of type: PACKAGE-ERROR
#<PACKAGE-ERROR>
Error flushed.
> ;;; Warning: Ignoring an unmatched right parenthesis.
```

**Comment by snmsts** [comment]
build is ok.
how about without quicklisp like ``ros +q run``
