### ISSUE TITLE
roswell abort connection to slime

### ISSUE THREAD

**Issue by ta2gch** [roswell/roswell#233]
When I type undefined symbol in slime, clasp aborts the connection to slime like this.

```lisp
CL-USER> foo
Debugger received error of type: UNBOUND-VARIABLE
The variable "FOO" is unbound.; Evaluation aborted on #<UNBOUND-VARIABLE>.
CL-USER>
```
After this, clasp cannot evaluate any expressions but it can do in sbcl and others.
It's a issue for clasp of roswell and not a issue for clasp because it works for me in this setting.

```lisp
(setq inferior-lisp-program "~/.roswell/impls/x86-64/linux/clasp/fa20fc6c7ef9b9b615cbb07070ec2de7130a1e03/clasp"
```

It doesn't work in this setting

```lisp
(setq inferior-lisp-program "ros run +Q")
```

Is it a issue about `ros run +Q -L clasp`?

**Comment by snmsts** [comment]
isn't it clasp issue?

**Comment by ta2gch** [comment]
No, it isn't.
Please see the last of before comment.

> It's a issue for clasp of roswell and not a issue for clasp because it works for me in this setting.
> 
> ```lisp
> (setq inferior-lisp-program "~/.roswell/impls/x86-64/linux/clasp/fa20fc6c7ef9b9b615cbb07070ec2de7130a1e03/clasp"
> ```
> 
> It doesn't work in this setting
> 
> ```lisp
> (setq inferior-lisp-program "ros run +Q")
> ```

Clasp's REPL catches an error and open the debugger in toplevel,
but `ros run -L clasp +Q` doesn't catch an error in toplevel and does restart without debugger.

It's a cause of this issue, isn't it?

**Comment by snmsts** [comment]
What is shown on ``*inferior-lisp*`` buffer?

**Comment by ta2gch** [comment]
I'm sorry to say that my init.el is wrong.

It works with `(setq "ros -L clasp +Q run")` and doesn't work with `(setq "ros -L clasp -Q run")`.
Hence 'Quicklisp' on clasp is a cause of this issue and `ros run -L clasp +Q` has caught an error.
When SLIME is loading with `(setq inferior-lisp-program "ros run -L clasp -Q")`, roswell fail to load Quicklisp and to open correct REPL.

I guess, default setting for roswell is that is ignoring to load Quicklisp.
So, there are no issues about this but clasp's user who use it via roswell take care of this.

I'm so sorry to puzzle you.

**Comment by snmsts** [comment]
Thanks. glad you can solve the problem.

I notice that If clasp's ``read-from-string`` is fixed ``-Q`` could became available option.
