### ISSUE TITLE
ros install 40ants/cldomain does not work for some reason

### ISSUE THREAD

**Issue by svetlyak40wt** [roswell/roswell#238]
Hi!

I've added a script to `roswell/cldomain.ros`, but roswell does not see it:

```bash
[art@art-osx5:~/common-lisp]% ros install 40ants/cldomain
install from github 40ants/cldomain
building dump:roswell
up to date. stop
[art@art-osx5:~/common-lisp]% ls ~/.roswell/bin
qlot
[art@art-osx5:~/common-lisp]% ros --version
roswell 17.2.8.74(5e7907c)
[art@art-osx5:~/common-lisp]
```

**Comment by snmsts** [comment]
Because roswell find ros script file where relative path from a system PATH.
roswell can't find project named ``cldomain`` after ``git clone``.

after first ros install command, you can install scripts via

```
ros install sphinxcontrib.cldomain
```

I hope it'll make sense.

**Comment by snmsts** [comment]
to solve this problem,I think there are two options.

* rename your repository to 40ants/sphinxcontrib.cldomain
* make ``cldomain.asd`` in your repository.

It is conventional restriction.I don't have idea to fix problem from roswell side.

**Comment by svetlyak40wt** [comment]
Thank you for the fast reply, SANO.

It works now!

After I've renamed system to cldomain, `ros install 40ants/cldomain` produced much more output about loading the `cldomain` system.

**Comment by snmsts** [comment]
sorry there's third option :)

**Comment by svetlyak40wt** [comment]
By the way, I found another problem – script was not installed because I've ~/common-lisp/cldomain/, but my version of roswell expects system to be installed into the `~/.roswell/…`. But I see you've removed this code 19 days ago: https://github.com/roswell/roswell/commit/b58a107fafd561d11a947a95a53b2df7b70018dd

**Comment by snmsts** [comment]
use ``ros update system`` to update.

**Comment by svetlyak40wt** [comment]
How should this help?

**Comment by svetlyak40wt** [comment]
By the way I have roswell, installed from the source. I've updated it to the last version from master branch, but now have another problem – roswell always build a binary using sbcl-bin instead of currently selected sbcl version. I will make another issue about this problem.

**Comment by snmsts** [comment]
>> How should this help?

Sorry, I think I misunderstand.
I'm not sure how your expectation implemented.

**Comment by svetlyak40wt** [comment]
Here a ticket about broken `ros build`: https://github.com/roswell/roswell/issues/239
