### ISSUE TITLE
A proposal of interface for roswell

### ISSUE THREAD

**Issue by ta2gch** [roswell/roswell#246]
I love this project. I hope that this proposal will make Roswell better.
This proposal is too long to read, so I create a repository (http://github.com/ta2gch/roswell-next).
Please see that. The description of this proposal is here.

- Reduce subcommands
- Provide simple interface like the go.

Since this proposal requires change of incompatible API, I think that it will be difficult to accept everything, but I hope you accept some of them.

Thank you.

**Comment by Hexstream** [comment]
I haven't started actually using Roswell yet, but I think I'd prefer commands a bit like this (somewhat inspired by the AWS cli):

```
ros install impl sbcl
ros install lib clhs
ros update impl sbcl
ros help
ros install help
ros install impl help
ros install impl ccl
ros select impl ccl
ros remove impl sbcl
```
Etc.

**Comment by snmsts** [comment]
I thought I've commented about this issue. Sorry fol late.
And I'm glad you love ``roswell`` and take effort thinking about improvement.

Honestly I'm quite not sure overall design of this project.

* ros run/test/build

I like this ideas. but not sure how yet.I believe there are different expectations of what it should work like.

* Reduce subcommands

it doesn't make sense for me.Why? I think basically ``ros`` command need more complex management than ``go``.While ``go`` is just manage libraries,``ros`` need to manage ``implementations``,``libraries`` 
and ``images`` (recently ``project template`` or ``scafold`` as well). I don't think ``ros`` command isn't so complex yet. Correct me if I'm wrong.

* Provide simple interface like the go.

I think to make ``roswell`` like ``go`` or ``npm`` I think we have to think about how common lisp project should be developed ,deployed, maintained with ``roswell``.

I believe [qlot](https://github.com/fukamachi/qlot)'s functionality is ``roswell``'s big missing piece compare to those software.

**Comment by ta2gch** [comment]
Thank you for your agreeing about run/test/build​.

There is a comparison in language package managers.

Feature                                     | npm | go | roswell
--------------------------------------- | ------ | --- | ---------
Project dependencies               |  :o:  |  :x: |  :x:
Library management                |  :o:  |  :o: | :o:
Implementations management |  :x:  | :o: [1] | :o:
Software installation                  |  :o:  | :o:  | :o:
Task runner                               |  :o:  | :o:  | :o:
Project information                    |  :o:  | :x:  | :o:

According to this comparison and your opinion, Roswell will be like go. Currently Roswell doesn't have a feature to delete libraries. I agree this because we should use qlot for project dependencies. the deleting implementations is too, because we can change implementations by `ros use` when we needs to disable implementations. This idea successes in go.

In my proposal, simple interface is not a small interface but a smart interface. It is equivalent to having same interfaces/options for same effects. For example, installation and updating are same effect excepting versions. So it's enough to set use -u option same as go in management of libraries/implementations.

So I could say reducing following subcommands.

- update
- delete

Supplementally, reducing subcommands is also an opinion to integrate commands at option level.

---
[1] https://twitter.com/golang/status/875117556595515392

**Comment by ta2gch** [comment]
> .While go is just manage libraries,ros need to manage implementations,libraries and images (recently project template or scafold as well).

I haven't known that roswell manages images too.

hmm, these three ideas.

1. @Hexstream 's idea (using namespace)
2. `use` / `get` / `env` are for implementations / libraries / images with options (-u -h etc)
3. `install` will work hard internally.

Do you have any ideas?

**Comment by snmsts** [comment]
* feature to delete library.
undocumented commands are provided but I have hesitance to promote use it.
``ros list git`` shows list of systems and ``ros git delete system-name`` would delete system installed via git.

* images
I assume you know ``ros dump`` see ``ros help dump``
to see what images currently created by ``ros -L sbcl-bin list dump`` images are managed separatedly with each version of implementation. 

* each of it has common options.
If I understand correct way think your proposal is 

-- should implement ``ros 'command' -h`` instead of ``ros help 'command'``
-- should implement ``ros 'command' -u`` instead of ``ros update 'command'``
-- should implement ``ros 'command' -l`` instead of ``ros list 'command'``

I still don't understand the difference from proposal.For me It's like ``two times three`` is better expression then ``three times two``. For me ``-l`` before command are to specify lisp file to load and after command are taken as ``showing list`` is a bit confusing.

**Comment by snmsts** [comment]
I forget mention wired feeling about ``ros update quicklisp``(It's undocumented as well...) while users never try ``ros install quicklisp``.

**Comment by ta2gch** [comment]
`delete` command is good by undocumented. I think so too. It has a risk destroys many dependencies. If you (owner) never understand comfortability of my proposal, I have no way to tell you more but I can say these. 

- Why ros has  many feature at `install` ? 
- Why `ros git` has a  `delete` sub-sub-command?

Now I take no thought of my proposal. I guess ros should take one of these because for ros and users it is important to have impartiality.

- install, delete and update will work hard internally,  and ros ends git sub-command.
- using namespace (@Hexstream 's) and sub-sub-commands

By the way, yours is `ros <operatatoin> <target>` but mine is `ros <operation> <effects> <target>` and @Hexstream 's is `ros <namespace> <operation> <target>`. In yours, ros have many many operations.

**Comment by Hexstream** [comment]
I guess I'm thinking of `ros install impl sbcl` as `ros <verb> <namespace> <subject>`, rather.
I don't think of `install` as a "namespace" and `sbcl` as an "operation"...

**Comment by snmsts** [comment]
* Why ros has many feature at install?

I don't think about it seriously yet. I think I intended to deal with system to implement non supported implementation installation and launch it.

It'll not work now but see an experiment https://github.com/roswell/jscl by installing this,roswell will possibly launch jscl via ``ros run``. I don't want to distinguish installed install operation and builtin install operation.

*  why ``ros git`` has a ``delete`` sub-sub-

There's no strong reason and I felt ``ros delete git system`` would be more consistent now. I'll change it.

I'll elimiinate ``ros asdf`` as well.

* many many operations.
I'm curious about the feeling.I feel sorry about the inconsistent design and I'm quite ok to hear someone complaining about it. But I don't take it a complain. I'd like to understand the impression ``many many`` how it comes from?

**Comment by ta2gch** [comment]
>  But I don't take it a complain. I'd like to understand the impression many many how it comes from?

I'm sorry that I made you feel disagreeable.
The reason I think that ros has many commands is because ros have a few of uncalled-for commands (This is my feelings), but isn't because of the number of commands.

Roswell **had** these commands.
- ros emacs
- ros asdf (you said "I'll elimiinate ros asdf as well.")

And I said them at before comments in this issue.
- ros update (by `-u` options)
- ros delete (because of the success in go)

I understand CommonLisp and Roswell aren't Golang and go. So I doesn't force to remove two commands but I like the way of go.

**Comment by snmsts** [comment]
> I'm sorry that I made you feel disagreeable.
You shouldn't feel so.
My problem is difficulty to get your point.
Disagreement could be a goal of a discussion. I'll appreciate if we reach the goal.

I doubt I'm obstinate, so If you think your proposal is more than just a preference.
I would like to hear your opinion why it's superior or 
what aspect of current sub-commands could introduce problems.

* (because of the success in go)
Does it mean promote this idea because successful ``go`` doesn't have ``delete`` sub command?

**Comment by ta2gch** [comment]
Thank you.

> Does it mean promote this idea because successful go doesn't have delete sub command?

Yes. We just run `rm -rf /path/to/package` if want to remove packages. go take care of dependencies at the installation of packages but doesn't at the deleting, and we can use `dep` same as `qlot` in our projects if want to manage them.  There are no issues about this style in go and I think so too. The success in my comments is meaning of having no issues.

However do you have any plans to implement the functionality like `qlot`?  I'll welcome it. In the fact, `npm`, `pip` and `cargo` have them but `gem` and `go` doesn't.  `gem` has `uninstall` command in spite of having `bundler`. I'm surprised at. 

Without management project's dependencies of the implementations, libraries and images, the deleting make us be puzzled. I think so.

The reason of propose `-u` options,  The same as `install`,  `update` has three meanings. One is **implementations**, the others are **systems** and *git-systems*.  Currently, we can use it in just `systems`. It is not friendly, is it? In my proposal, To update them we can add just `-u` options to command when we used in the installation.

**Comment by snmsts** [comment]
* go without delete.

ok, I understand.
structure of  ``.roswell`` is already enough puzzling.
I think now I understand enough to disagree.

* implement project management facility

No. I like ``qlot``.

* -u
ok, I couldn't understand it cause I don't think it's not friendly at all.

Thanks.

**Comment by ta2gch** [comment]
Okey. Will we use following commands in the feature?

- test (for project)
- build (for project)

Next, we need to know how ros do these.

**Comment by snmsts** [comment]
Yes, but I'm no idea.
Lake might take that responsibility.

**Comment by ta2gch** [comment]
Thank you a lot. :bowing_man:

**Comment by snmsts** [comment]
Thank you. I enjoyed discussion. :+1:
