### ISSUE TITLE
ros install ccl-bin fails on Windows, attempts to download nonexistent file

### ISSUE THREAD

**Issue by anticrisis** [roswell/roswell#254]
## Environment

Windows 10

```
# result of evaluating
uname -a
MSYS_NT-10.0 ALIEN51 2.8.2(0.313/5/3) 2017-07-14 08:19 x86_64 Msys

ros --version    # if roswell runs successfully
roswell 17.6.9.79

ros config
roswell 17.6.9.79
```

## How to reproduce the issue

```sh

ros install ccl-bin

```

## Expected behavior

CCL is downloaded correctly and installed. 

## Actual result

The filename roswell tries to fetch is incorrect. It includes "x86," but the distribution ftp site does not have a file with that name.

```sh
Downloading http://ccl.clozure.com/ftp/pub/release/1.11/ccl-1.11-windowsx86.zip
```

Workaround: 

1. Manually fetch the correct ccl zip file http://ccl.clozure.com/ftp/pub/release/1.11/ccl-1.11-windows.zip
2. Place it in ~/.roswell/archives folder
3. Rename it to include the x86 suffix roswell is looking for.
4. `ros install ccl-bin` again.

**Comment by snmsts** [comment]
Thank you for your report.

I notice this behavior and I have been feeling I don't want to fix it roswell side.

compare

https://ccl.clozure.com/ftp/pub/release/1.9/
https://ccl.clozure.com/ftp/pub/release/1.10/
https://ccl.clozure.com/ftp/pub/release/1.11/

by seeing these filenames,I feel clozure guys break their naming convention only on 1.11 windows.
Would you mind reporting it to them?

**Comment by anticrisis** [comment]
Reported: https://trac.clozure.com/ccl/ticket/1417

**Comment by snmsts** [comment]
Thank you!

**Comment by xrme** [comment]
I added a symlink `ccl-1.11-windowsx86.zip -> ccl-1.11-windows.zip` so  that users won't have to rename the file manually.

**Comment by snmsts** [comment]
@xrme confirmed. Thank you!
