### ISSUE TITLE
can not run ros init in linux mint

### ISSUE THREAD

**Issue by wlisper** [roswell/roswell#257]
## Environment

linux mint 18.  latest roswell 17.7.9.80
## How to reproduce the issue

```sh
ros init

```

## Expected behavior

```sh
install sbcl succeesfully
```

## Actual result
Installing sbcl-bin...
No SBCL version specified. Downloading platform-table.html to see the available versions...
Something wrong! Check the connection or sbcl.org is down. Download failed (Code=2), tring the backup URL.
[##########################################################################]100%
Installing sbcl-bin/1.3.20...
Downloading https://github.com/roswell/sbcl_bin/releases/download/1.3.20/sbcl-1.3.20-x86-64-linux-binary.tar.bz2
Download Failed with status 2. See download_simple in src/download.c
Segmentation fault
```sh

```

**Comment by snmsts** [comment]
status 2 means it related to libcurl. I don't know well but looks https access are always failed with your environment. It might be linux package problem...

**Comment by wlisper** [comment]
I finally solved this problem by installing from a deb package.  thank you for your help

**Comment by snmsts** [comment]
install roswell via deb? anyway...

**Comment by Hexstream** [comment]
I think he meant that he installed something that handles the HTTPS correctly via a deb package.

OR, someone made an unofficial deb package that installs Roswell plus the needed dependencies...

**Comment by wlisper** [comment]
in fact, I downloaded an installable deb package from here: https://github.com/roswell/roswell/releases. I had tried to compile from source many times, just could not solve the problem.

**Comment by Hexstream** [comment]
Oh cool, there are now official deb packages??...
But then why did @snmsts appear confused about you installing from deb?? I am *very* confused...

**Comment by snmsts** [comment]
I'm confused cause I don't think it'll help practically.

**Comment by Hexstream** [comment]
Well, apparently it did. ;P
