### ISSUE TITLE
option for installing develop branch (ECL)

### ISSUE THREAD

**Issue by Chream** [roswell/roswell#268]
Hi, I am currently having issues with ECL in that it crashes when loading cffi. I was told this was fixed in the develop branch. As ECL releases are pretty far apart an option to install the develop branch would be nice. I have tried to look through the roswell code to see if I could supply a patch for this but between the c code and lisp I cant figure it out. Any plans or pointers for how to implement this?

**Comment by snmsts** [comment]
I fixed a bit now ``ros install ecl/develop`` will do what you want on master.
I will release it in a month.

Push them to release the new version.
Saying "the problem is already fixed but not yet released (and you can't expect when it would be released)" is rude.

**Comment by Chream** [comment]
Thank you! 

> Push them to release the new version.
> Saying "the problem is already fixed but not yet released (and you can't expect when it would be released)" is rude.

I did not understand this. Was I being rude?

**Comment by snmsts** [comment]
them not you.
