### ISSUE TITLE
members in roswell.

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#269]
I think it's better to maintain members who can commit all of roswell repository by how active they are.
basically, people who commit more frequently than once a three month should be in the circle.
I think I should review about it.

to give membership.

* who have will to contibute.
* if a member ask and the person accept to be a member.

to take membership.

* who are not active at all more than half year.
* might keep them as collaborator.

I'm thinking @fukamachi  and @eudoxia0 don't need full access anymore.

**Comment by fukamachi** [comment]
👍

**Comment by eudoxia0** [comment]
:+1:

**Comment by snmsts** [comment]
Done.
I hope you'll come back someday :)
