### ISSUE TITLE
install command doesn't recognize systems with slash in name

### ISSUE THREAD

**Issue by borodust** [roswell/roswell#274]
Slash in asdf system names is an officially supported and [documented](https://common-lisp.net/project/asdf/asdf/Components.html#index-find_002dsystem) way to define several systems in a single `.asd` file.

> It is often useful to define multiple systems in a same file, but ASDF can only locate a system’s definition file based on the system name. For this reason, ASDF 3’s system search algorithm has been extended to allow a file foo.asd to contain secondary systems named foo/bar, foo/baz, foo/quux, etc., in addition to the primary system named foo

## Environment
```
$uname -a
Linux 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 

$ros --version    
roswell 17.10.10.83

$ros config
setup.time=3719247514
sbcl-bin.version=1.4.1
default.lisp=sbcl-bin
```

## How to reproduce the issue
```sh
ros run -e '(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.txt" :prompt nil)' -q
ros install notalone
```

## Expected behavior
Full installation of :notalone system

## Actual result
Roswell tries to download `cl-bodge/assets` et al from github, most likely confusing `cl-bodge` for a github username

**Comment by snmsts** [comment]
I fixed with https://github.com/roswell/roswell/commit/ffd16bece43ba17d1e92255a2cd43c58c560a7df
try master or wait for new release.

**Comment by borodust** [comment]
Seems to work. Thank you very much!
