### ISSUE TITLE
Thanks much for all your work

### ISSUE THREAD

**Issue by borodust** [roswell/roswell#275]
`roswell` helped me a big bunch with building my Common Lisp software for Linux/macOS via `Travis CI` and Windows via `Appveyor`. 

Thank you very much for this amazing tool. Keep up the awesome work!

## How to reproduce the issue
```
Use roswell for Continuous Integration
```

## Expected behavior
```
Awesome results
```

## Actual result
```
Awesome results
```

**Comment by snmsts** [comment]
Our pleasure.Thank you.
