### ISSUE TITLE
Want to install a lisp: how to bypass SBCL's ensure_space error ?

### ISSUE THREAD

**Issue by vindarel** [roswell/roswell#276]
I can not install a lisp with Roswell nor run any Roswell command because I can not run SBCL. Is there a configuration option to allow me to set the lisp executable, so I could use ecl, besides `ros use` ?

I installed sbcl on my VPS but I can not run it: 

```sh
 sbcl
mmap: wanted 1040384 bytes at 0x20000000, actually mapped at 0x740a92523000
ensure_space: failed to validate 1040384 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
```

Note that I have 1.5Go of free RAM, but I'm using 365Mo/500 swap.

I don't know how to fix this but allright, I installed ECL with apt-get and I can run it, but it is an old version (it ships a 2.x version of ASDF which prevents me from installing some packages). So I wanted to install a newer version with Roswell, but I get a circular problem:

```
ros install ecl
mmap: wanted 1040384 bytes at 0x20000000, actually mapped at 0x71cf1a7a4000
ensure_space: failed to allocate 1040384 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
```

I thought about using `ros use ecl` but I can't either.

Which lisp is calling Roswell ?

I uninstalled sbcl but still the same.

## Environment

Linux ns379751.ip-x-x-x.eu 3.14.32-xxxx-grs-ipv6-64 / Debian x64
ros --version:  17.10.10.83
ros config
```
Making core for Roswell...
mmap: wanted 1040384 bytes at 0x20000000, actually mapped at 0x75db2a418000
ensure_space: failed to allocate 1040384 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
mmap: wanted 1040384 bytes at 0x20000000, actually mapped at 0x67d771e7d000
ensure_space: failed to allocate 1040384 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
```

## How to reproduce the issue

Reproduce when you get this issue with SBCL.

## Expected behavior

I suppose we could give a path to a lisp executable to Roswell.

## Actual result

---

ps: updating ASDF also seems difficult: its update script needs cl-launch which relies on SBCL and throws this problem… I might install ECL from scratch. But still.

**Comment by snmsts** [comment]
It seems environment and sbcl specific problem, not related to roswell.
why ask here?

**Comment by vindarel** [comment]
because does Roswell rely on SBCL to run its scripts ? Can I tell it to use ECL instead ?

**Comment by snmsts** [comment]
Just for scripts... may be you can but you can't install anything at the place.
you have to bring ``~/.roswell`` from other environment. 
because I wrote c code to install sbcl-bin, then every other target installation are depend on the sbcl-bin.
I don't have resource and plan to support provide choices for first priority implementation.
I'm feeling sorry to say this but It might better to give up Roswell for such a tricky environment.

FYI:
http://www.lispforum.com/viewtopic.php?f=2&t=4585

**Comment by guicho271828** [comment]
Ahhh, 

> sbcl won't run with ASLR.

this.

**Comment by snmsts** [comment]
@guicho271828 Can vps user modify kernel parameter?
I don't want to rethink/rewrite bootstrapping and distributing for windows with ECL at all.
Roswell binary distribution using ECL is technically possible but isn't Roswell affected by ECL's license?

**Comment by vindarel** [comment]
I got my answer, thanks.

I found a good [docker image](https://github.com/daewok/lisp-devel-docker), I'll go with that.
