### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by jaccarmac** [roswell/roswell#280]
This is probably a stupid question, but how does one update an installed system? `ros update` tells me "no update function" and I can't figure out how to get Roswell to recognize the `install.force` option (I've tried `--install.force`, `--install.force=t`, and `install.force=t` and all are ignored.).

**Comment by guicho271828** [comment]
`ros update` seems to be in the more recent release.

**Comment by jaccarmac** [comment]
I'm running `b0be720`.

**Comment by guicho271828** [comment]
oh, the latest. possible bug?

**Comment by guicho271828** [comment]
`ros update` is for asdf systems. If you want to update the implementations you can just use `ros install sbcl`, it checks for the latest version and download it even if the current implementation is sbcl.

AFAIK I believe `sbcl-bin` is basically a fixed version and you are not supposed to update it. It is only occasionally updated when roswell itself has a new release.

**Comment by jaccarmac** [comment]
I see, thanks. Was confused because certain `install` invocations were telling me to use `download.force=t` and others were suggesting `install.force=t`. I figured that meant I needed to override the install command to get a new version, clearly I was wrong.

**Comment by snmsts** [comment]
by default roswell checks https://github.com/roswell/sbcl_bin/releases/download/files/build.html and determin version.

the build.html are maintained via travis and daily updated. so if sbcl are updated and you are using linux of osx the newest version would be downloaded in a day after release, if scripts run properly...
