### ISSUE TITLE
Old Quicklisp dist does not find recent libraries

### ISSUE THREAD

**Issue by vindarel** [roswell/roswell#281]
Quicklisp-dist's version is pretty old, and so it doesn't find libraries. How can we update it ? (I don't feel like programmatically upgrading Quicklisp for my roswell scripts, that would be too long…)

Could not find with `ros help / config / help config` and looks into the readme and the wiki.

## Environment

```
uname -a
$ ros version                                                          
roswell 17.6.9.79
build with gcc-4.9 (Debian 4.9.2-10) 4.9.2
libcurl=7.54.1
Quicklisp=2016-02-22
Dist=2016-04-21
lispdir='/home/vince/.linuxbrew/Cellar/roswell/17.6.9.79/etc/roswell/'
configdir='/home/vince/.roswell/'
```

(I tried to upgrade roswell, with linuxbrew, no change).

## How to reproduce the issue

```sh
# roswell/myapp.ros
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#

(format t "--- ~a ~&" (ql:dist-version "quicklisp"))

(unless (find-package :str)
  (ql:quickload :str))

```

> --- 2016-04-21 
> An error occurred during initialization:
> System "str" not found.

## Expected behavior

to find `str`, as in Slime: `(ql:quickload "str")` is ok. [Quickdocs](http://quickdocs.org/cl-str/).

Thanks !

ps: while we're at it, some tips to not have to wait for Quicklisp everytime we run a ros script would be welcome.

**Comment by vindarel** [comment]
Despite an apparent `(ql:update-dist "quicklisp")` error
```

Downloading http://beta.quicklisp.org/archive/nibbles/2017-04-03/nibbles-20170403-git.tgz
##########################################################################
Downloading http://beta.quicklisp.org/archive/fast-io/2017-10-23/fast-io-20171023-git.tgz
##########################################################################
An error occurred during initialization:
Filesystem error with pathname #P"/home/vince/.roswell/lisp/quicklisp/tmp/distinfo-update/archives/".
Either
 1) the file does not exist, or
 2) we are not allowed to access the file, or
 3) the pathname points to a broken symbolic link..
```

it worked (now dist 2017-10-23, loads all my dependencies), but I don't think this is a viable workaround. What happens when I distribute my script to other users ?

**Comment by snmsts** [comment]
again. why you stick with roswell? read quicklisp related document.

**Comment by guicho271828** [comment]
@vindarel Ask @xach for providing a restart in `quickload` that calls `register-local-projects` and maybe `dist-upgrade`.
Or implement it yourself. Wrap it with a proper handler that retries `quickload` after calling it when it errors.
Although I'm fine to answer the question, Roswell is agnostic to quicklisp, it uses quicklisp as it is, thus all quicklisp related questions/issues should go to @xach .

> What happens when I distribute my script to other users ?

If you are sending a script to the other users, it is the user's (or the distributor's) responsibility to install the required libraries on the target machine. This is exactly the same in python or ruby, where users are expected to install libraries through `pip` or `gem` by themselves. If you also want to avoid it then you should distribute the built binary instead. (python/ruby does not allow such a possibility, btw.)

@snmsts It might be useful to provide a command for updating the entire dist.

**Comment by vindarel** [comment]
Thanks for the hints, I'll improve the wiki when I can. Here seemed the place to ask because Roswell advertises to be able to ship software, and I faced a limitation with bare bones Roswell. Not having a recent quicklisp dist bundled into it made the task not possible straight away. And you may be interested by user feedback.

> It might be useful to provide a command for updating the entire dist.

+1

> Roswell is agnostic to quicklisp

It's tightly coupled then. It can not build a script if it does not have a decent Quicklisp dist.

> This is exactly the same in python or ruby, where users are expected to install libraries through pip or gem by themselves.

well, nearly. Pip will install any dependencies, here we have a prior consideration (updating the dist) before it is possible. (the analogy with apt works better !)

I am able to distribute a binary but I was looking for a more lightweight solution and one more integrated for lispers.

**Comment by guicho271828** [comment]
> advertises to be able to ship software

Perhaps the wiki page for **distributing software via quicklisp** was confused with sending a script directly. In the former case, the `roswell/` directory in a repo is distributed by the monthly quicklisp release. When the script was **installed via quicklisp**, it means you already have the up-to-date dist, thus the problematic case never happens.

If you instead manually clone a github repo into `local-projects/` whose scripts assume a newer dist, the scripts would fail.

Sending a script directly is identical to cloning a repo manually. Quicker but not as organized as quicklisp. Good for one-time use hackjob like a perl script, or a professional use.

> It's tightly coupled then. It can not build a script if it does not have a decent Quicklisp dist.

It is **the script** that is coupling roswell and quickisp, because the script runs/builds fine when you remove any quicklisp-related part of the script and put the requisites in asdf's source directory.

In the case above, **it is `(ql:quickload "str")` that depends on quicklisp and making the code fail.** It is also depending on Roswell by expecting it to update the dist, which is not the case.

So, as I wrote earlier, there are three choices, and only two of which are reasonable:

1. Ask @xach to make `quickload` also update the dist when necessary, or provide some interactive restart, or a more friendly warning/error message etc.
2. The script handles `asdf:system-not-found` by itself and update the dist when necessary. I.e. implement it yourself.
3. Expect roswell, a program for launching an impl and loading whichever asdf/quicklisp available (agnostic) for conveniency, to handle asdf/quicklisp error.

**Comment by vindarel** [comment]
> You won't say gcc depends on apt-get when the compilation fails due to a missing header file curl.h that could be installed by apt-get libcurl-dev. gcc is not supposed to apt-get update && apt-get upgrade automatically.

that makes sense and I get this analogy. In this example, the user can run `apt-get update` & `apt-get install libcurl-dev`. In our case, *Roswell uses its own ql dist*. If the user runs `(ql:update-dist "quicklisp")` in its Slime repl, it has no influence on Roswell which will stay at its ql version and will not find the library, even if the user can qload it. 
When I opened my issue, Roswell was at `Quicklisp=2016-02-22`, but I had a more recent one. I had to update the dist in the context of Roswell, inside my script (*like if gcc updated apt*), not as a user.

What you suggested

> It might be useful to provide a command for updating the entire dist.

sthg like `ros ql-update` sounds like the solution to me.

In which case this issue should be open.

ps: a final word, to be sure I expect the right thing about Roswell :D I expect it to install a software that is not available Quicklisp (but has all its dependencies in it). (then: I was also hoping the startup time would be fast, as when pip installs software, but we'll have to wait for ql to load all dependencies).

**Comment by guicho271828** [comment]
> In our case, Roswell uses its own ql dist. If the user runs (ql:update-dist "quicklisp") in its Slime repl, it has no influence on Roswell which will stay at its ql version and will not find the library, even if the user can qload it.

I was confused by this part... [It sounds like your SLIME is not configured to use roswell.](https://roswell.github.io/Initial-Recommended-Setup.html) Is it?

**Comment by vindarel** [comment]
Yeeeah this is it. I'm a bit confused because the doc does exist so I'm not far from a "RTFD". I had read it long ago though, but didn't understand the necessity of Slime's setup at the time. I added a FAQ entry and a preamble in "Installation".

Thanks ! Hopes this will help other people :)
