### ISSUE TITLE
Misleadind information in the "list" command

### ISSUE THREAD

**Issue by fstamour** [roswell/roswell#283]
## Environment

```
$ uname -a
MINGW64_NT-10.0 DESKTOP-KIETB4S 2.8.0(0.309/5/3) 2017-03-21 14:04 x86_64 Msys
$ ros --version
roswell 17.11.10.85(8df9eaf)
$ ros config
setup.time=3721003398
sbcl-bin.version=1.3.18
default.lisp=sbcl-bin

Possible subcommands:
set
show
```

It's not really a bug, it's just really confusing that when you run `ros list` it's says that you can run `ros list default` but you can't. Maybe I misunderstood something, but that's pretty much the problem.

![image](https://user-images.githubusercontent.com/2881922/33412579-2a057308-d55a-11e7-934d-6fa0e1a9f3e5.png)

**Comment by fstamour** [comment]
Also, one the exact same setup. When I run `ros help list` it returns (print) nothing.

**Comment by snmsts** [comment]
does ``ros help something`` show anything?
I wrote nothing for windows.

**Comment by fstamour** [comment]
```sh
ros help something
ros help version
ros help config
```

All returns nothings.

**Comment by snmsts** [comment]
I believe the part man on unix and for windows not implemented yet.

**Comment by fstamour** [comment]
Just to make sure: you're saying it just not implemented yet?
