### ISSUE TITLE
How do I get a roswell binary to execute at native saved image speeds?

### ISSUE THREAD

**Issue by ahungry** [roswell/roswell#285]
For my project here: https://github.com/ahungry/ahungry-fleece, given that I load it up through roswell (I supplied the necessary ros files in my package to enable this):

```sh
ros install ahungry/ahungry-fleece
```

Then I execute it as such:
```sh
time ~/.roswell/bin/ahungry-fleece -h
ahungry-fleece v/0.3.0.

Usage:

    $ ahungry-fleece [-h, --help] # Print this help
    $ ahungry-fleece make-skelly-project /path/to/directory # Make a skeleton project

~/.roswell/bin/ahungry-fleece -h  1.01s user 0.24s system 97% cpu 1.286 total
```

You can see it takes 1.286 seconds to launch - that is too slow for a user to treat a ros installed binary the same as any other system binary.

For comparisons sake, in my repo, I provide a `make` command to produce a binary for SBCL generated via `#'sb-ext:save-lisp-and-die`, with the same entry point that ros script uses, and it runs in this time:

```sh
time ./bin/ahungry-fleece -h
ahungry-fleece v/0.3.0.

Usage:

    $ ahungry-fleece [-h, --help] # Print this help
    $ ahungry-fleece make-skelly-project /path/to/directory # Make a skeleton project

./bin/ahungry-fleece -h  0.00s user 0.00s system 69% cpu 0.011 total
```

Is there currently a way to keep a compiled ros image of shared binaries/scripts (or even one per `ros install`) so that we can get to the point where a user can simply `ros install some/bin` and expect true binary speeds vs the heavy overhead of booting up the lisp core? (useful for developers, not useful for users)

**Comment by snmsts** [comment]
edit fourth line like
```
exec ros -Q -L sbcl-bin -m ahungry-fleece -- $0 "$@"
```

**Comment by ahungry** [comment]
Thank you for the suggestion - unfortunately the time difference this makes is negligible - I'm guessing the overhead is due to loading init / rc / quicklisp code + running the file as a script load instead of a compiled binary (even with saved core this doesn't speed it up, and it attempts to generate core each run).

**Comment by guicho271828** [comment]
i would test your code later

**Comment by ahungry** [comment]
Thanks - are there changes coming soon?  I hand edited all the ~/.roswell references to my file to ensure they incorporated the suggested `-m ahungry-fleece` flag - when I said 'negligible', it did change it to some (small) degree, but the new 0.9 sec run time vs 1.2 sec run time is still a large magnitude off from the 0.01 execution time.

Is roswell mostly aimed at filling the niche for CL development?  Or to make `ros` type scripts as usable for general purpose users as similar language specific installers (npm, composer, gem, pip etc.).

**Comment by snmsts** [comment]
it sound like bug. which version of roswell are you using @ahungry ?
It's not so clear question for me...

**Comment by ahungry** [comment]
Here is a better minimum example and comparative approach:

```
#!/bin/sh
#|-*- mode:lisp -*-|#
#| A utility library for Common Lisp dependant on SBCL
exec ros -Q -L sbcl-bin -- $0 "$@"
|#

(defpackage #:ros.script.speed
  (:use #:cl))

(in-package :ros.script.speed)

(defun main (&rest argv)
  (declare (ignore argv))
  (print "Hello world"))

(main)

;;; vim: set ft=lisp lisp:
```

Now, to time it (and see ros version):
```
λ mcarter-ultra-tp  bin → ros --version
roswell 17.11.10.85(b0be720)
λ mcarter-ultra-tp  bin → time ./speed 

"Hello world" 
"Hello world" ./speed  0.63s user 0.09s system 96% cpu 0.748 total
λ mcarter-ultra-tp  bin → time sbcl --script ./speed

"Hello world" sbcl --script ./speed  0.00s user 0.01s system 54% cpu 0.015 total
```

You can see running straight through sbcl it is done in 0.015 seconds, but running through ros with sbcl-bin launcher makes it magnitudes slower.

How do we prevent that extra 1 second of boot up on the ros side?  I have a feeling it has to do with the ros / sbcl-bin entry point loading up init/quicklisp stuff that is not necessary on a saved image core.

**Comment by ahungry** [comment]
If I change the option `-Q` to `+Q` to bypass loading QL libs, this can reduce it to 0.15 seconds, which is still 10x slower, but likely imperceptible to a user, however on the first load that generates the module, we likely *would* need quicklisp.  So, maybe we need a new flag/option to the `-m` switch to load quicklisp on the first boot / core generation, and not again afterwards.

**Comment by snmsts** [comment]
it's not automatic dump facility if you use without install.
try

```
ros -l speed.ros dump output speed
time ./speed
```

**Comment by snmsts** [comment]
or

```
ros install speed.ros
time ~/.roswell/bin/speed
```

**Comment by snmsts** [comment]
to examine dump is properly used or not, use ``-v`` option for roswell. it can be passed via commandline or fourth line of the script.

**Comment by guicho271828** [comment]
It seems it works.

```
time ros speed.ros

"Hello world" 
"Hello world" 
real	0m0.695s
user	0m0.624s
sys	0m0.048s
[guicho repos]$ ros install speed.ros
/home/guicho/.roswell/bin/speed
up to date. stop
[guicho repos]$ speed
Making core for Roswell...
building dump:/home/guicho/.roswell/impls/x86-64/linux/sbcl-bin/1.4.0/dump/speed.core

"Hello world" 
"Hello world" [guicho repos]$ time speed

"Hello world" 
"Hello world" 
real	0m0.056s
user	0m0.008s
sys	0m0.024s
[guicho repos]$ 
```

**Comment by guicho271828** [comment]
> it's not automatically dumped if you use without install.

It seems not the case. When I manually modified the script in `.roswell/bin`, it also creates a dump and the second invocation uses the fast binary.

**Comment by guicho271828** [comment]
Editing the roswell script that is not in `.roswell/bin/` has no effect, if this is what you meant.

**Comment by guicho271828** [comment]
Added a mention in https://github.com/roswell/roswell/wiki/How-to-distribute-your-software,-not-library,-on-Quicklisp-ala-python-pip . Thank you @ahungry !

**Comment by ahungry** [comment]
Thanks all, glad to see this looking good, I'll re-test today as well and close issue on success.

**Comment by guicho271828** [comment]
I believe this was resolved/clarified.

**Comment by ahungry** [comment]
Yes, sorry, thanks.

**Comment by guicho271828** [comment]
Reopening this. I identified another root cause Roswell fails to recognize the compiled binary.

So, in a nutshell, **both** `-L sbcl-bin` **and** `-m image` are necessary. Without `-L sbcl-bin` it works only when the current lisp is `sbcl-bin`, otherwise it fails to recognize the dumped image.

```
[guicho cl-prolog2]$ cat roswell/cl-prolog2.ros
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -m cl-prolog2 -- $0 "$@"
...

[guicho cl-prolog2]$ ros config
sbcl.version=1.4.3
sbcl-bin.version=1.4.0
default.lisp=sbcl

[guicho cl-prolog2]$ ros install cl-prolog2
...
Found 1 scripts: cl-prolog2
/home/guicho/.roswell/bin/cl-prolog2
up to date. stop

[guicho cl-prolog2]$ cl-prolog2
Making core for Roswell...
building dump:/home/guicho/.roswell/impls/x86-64/linux/sbcl-bin/1.4.0/dump/cl-prolog2.core
<script output>

[guicho cl-prolog2]$ cl-prolog2
Making core for Roswell...
building dump:/home/guicho/.roswell/impls/x86-64/linux/sbcl-bin/1.4.0/dump/cl-prolog2.core
<script output>
```

I believe below is what is happening:
* It looks for a dump made for the current `default.lisp` which is `sbcl`. Since it does not exist, so it decides to dump the core. However, when `-m` is specified for a roswell script, it always dumps the image with `sbcl-bin`. In the second invocation, it looks for `sbcl` image, fails, then dumps with `sbcl-bin` again.
* When `-L sbcl-bin` is specified, it looks for `sbcl-bin` image and dumps for `sbcl-bin` image.
* When `-L sbcl-bin` is not specified but the current `default.lisp` is `sbcl-bin`, it also works too.
* I tested `-L sbcl` but it still dumps with `sbcl-bin`.
* `-L ccl-bin` causes error, failing to load the dump.

```
[guicho cl-prolog2]$ cl-prolog2
Couldn't load lisp heap image from /home/guicho/.roswell/impls/x86-64/linux/ccl-bin/1.11/dump/cl-prolog2.lx86cl64: No such file or directory
```

**Comment by guicho271828** [comment]
It also fails when the script is updated but the old dump already exists.
It tries to create a build again and again.

**Comment by ahungry** [comment]
Thanks for looking into again - I thought I had experienced similar (constant attempts to rebuild core under the -m flag) but couldn't track down the cause (having modified the script).

**Comment by snmsts** [comment]
decide not to dump automatically for sbcl. only sbcl-bin.

**Comment by snmsts** [comment]
ping @guicho271828

**Comment by guicho271828** [comment]
testing the new version now

**Comment by guicho271828** [comment]
I am doing the fresh install of roswell before doing this. it takes a while...

**Comment by guicho271828** [comment]
well, I don't think the patch is really fixing the issue. The right behavior is not defined and it is not clear if the above patch fixes the issue. The patch seems like just disabling the dump, but the right behavior is 
* look for the core made for the specified implementation (-L)
* check the timestamp of the core and the script, then update the core properly

**Comment by guicho271828** [comment]
I confirmed that the dump feature is disabled except for sbcl-bin

**Comment by snmsts** [comment]
For autodump feature, I don't want to support other than sbcl-bin before env feature is stabilized.

**Comment by guicho271828** [comment]
sure, if you have a roadmap it is fine

**Comment by snmsts** [comment]
For now, I should say 'use "-L sbcl-bin"'.

close?

**Comment by guicho271828** [comment]
yes.

**Comment by guicho271828** [comment]
I'll note it in the wiki.

**Comment by snmsts** [comment]
So far I'm not willing to fix at all. you can fix if you want.
