### ISSUE TITLE
Not able to get random results from script

### ISSUE THREAD

**Issue by duikboot** [roswell/roswell#286]
Thanks for your great repo. I want to make a 'fortune' script, which returns a random line from a file.
It returns always the same line, though. Am I using Roswell incorrect?

## Environment

```
# result of evaluating
$ uname -a
Linux 192.168.2.9 4.13.16-200.fc26.x86_64 #1 SMP Mon Nov 27 18:19:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ ros --version    # if roswell runs successfully
roswell 17.10.10.83(0ba9990)
$ ros config
sbcl.version=1.4.1
ecl.version=16.1.3
setup.time=3719390458
sbcl-bin.version=1.3.20
default.lisp=sbcl
```
## How to reproduce the issue

When I run the script, I always get the same result:
```
$ ./fortune.ros ~/.oh-my-zsh/plugins/chucknorris/fortunes/chucknorris

Chuck Norris has counted to infinity. Twice.
```
If I run the expression:
```
(princ
    (alexandria:random-elt
           (split-sequence:split-sequence #\% (alexandria:read-file-into-string "~/.oh-my-zsh/plugins/chucknorris/fortunes/chucknorris"))))
```
I do get the desired random result.

# The script:

```sh
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#
(progn ;;init forms
  (ros:ensure-asdf)
  #+quicklisp (ql:quickload '(alexandria split-sequence) :silent t))


(defpackage :ros.script.fortune.3721561154
  (:use :cl))
(in-package :ros.script.fortune.3721561154)

(defun main (file &rest argv)
  (declare (ignorable argv))
  (princ
    (alexandria:random-elt
           (split-sequence:split-sequence #\% (alexandria:read-file-into-string file)))))

;;; vim: set ft=lisp lisp:


```

## Expected behavior

Get a different line every time (random-elt)

## Actual result
I do get the same result every time.

**Comment by guicho271828** [comment]
Previously discussed in https://github.com/roswell/roswell/issues/110 .
At the moment, try `(setf *random-state* (random-state t))` to get the fresh random state.

**Comment by duikboot** [comment]
Thanks a lot, I missed it when searching for it in the issues

**Comment by guicho271828** [comment]
Mentioned in the wiki. https://github.com/roswell/roswell/wiki/FAQ#my-roswell-script-uses-a-fixed-random-seed
