### ISSUE TITLE
How can I evaluate expressions using Roswell?

### ISSUE THREAD

**Issue by phoe** [roswell/roswell#298]
I want Roswell to execute the Lisp process, evaluate an expression like `(print 2)` and quit. How can I achieve this?

**Comment by snmsts** [comment]
ros -e (p…) -q

i'm out without laptop with all of japanese contributors. help yourself or wait for a while.

**Comment by snmsts** [comment]
not all contributors sorry

**Comment by guicho271828** [comment]
a.l.a. `perl -e`

**Comment by phoe** [comment]
It works. Thank you!
