### ISSUE TITLE
Roswell not working on OpenBSD

### ISSUE THREAD

**Issue by engblom** [roswell/roswell#306]
I filed this bug report because roswell is not supporting OpenBSD, but this is more a feature wish rather than a bug report.

While there is an implementation of CL for almost every platform (packages, ports, downloadable binaries, ABCL on JVM, etc), roswell is not working on every platform.

My humble suggestion, if possible,  is to be less dependable on C and downloadable platform-dependent binaries. My wish is that roswell would be more like leiningen for Clojure: you only download a single shell script and it makes sure you have everything. This works well for Clojure as it is only depending on JVM, which is available for almost every platform. Rosewell could do something similar, considering ABCL runs on JVM and ECL exists for most platforms.

**Comment by snmsts** [comment]
As roswell is distributed in MIT license, you can fork and port it freely.

**Comment by engblom** [comment]
This is what happens when running `ros setup` on OpenBSD 6.2:
>Installing sbcl-bin...
>No SBCL version specified. Downloading platform-table.html to see the available versions...
>[##########################################################################]100%
>this architecture is not supported.stop
>Segmentation fault (core dumped) 

I realize this is not a bug itself, as I said in the initial post. It is more about the architecture itself, and how it only works on certain platforms. This is why this is a feature request rather than a real bug report.

My feature request is a way to run roswell on all platforms supporting some kind of CL. For example, OpenBSD got SBCL, CLISP, ECL and even ABCL packages and is thus supporting well CL. Still roswell is not running on this platform. 

There are many ways to achieve platform independence for roswell, and what I suggested in my first post is just suggestions among many solutions.

**Comment by snmsts** [comment]
I push a fix for openbsd while I don't have box to test.
see #104 may be related.

**Comment by engblom** [comment]
I did not test this fix until now, but the same problem remains: I get the very same segfault.
