### ISSUE TITLE
protect impl from deleting

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#31]
Currently 'ros delete' delete what ever it specified. but deleting current impl would seriously affect Roswell's system itself. We need to modify 'ros delete' command not accidentally delete those implementations.

**Comment by fukamachi** [comment]
What is the ideal way to do it you think?

- Raise an error and don't allow to delete it until change the current one. 
- Delete anyway and change the current to something else, like sbcl-bin

I should look into other similar projects like RVM.

**Comment by snmsts** [comment]
I'm not sure yet,but I currently support the former idea.

- At least one sbcl-bin should be reserved to execute subcommands.
- It is difficult to find which impl is appropriate to be chosen when the last version of impl are deleted.

from those viewpoint, I don't think I can implement the later one directly.

**Comment by fukamachi** [comment]
Surprisingly, RVM doesn't do anything for it. When I tried uninstalling the current & default one, it deletes it successfully. 




It seems RVM allows the situation with no current implementation. 'ruby' command points nothing in RVM and which means it will be the system Ruby (/usr/bin/ruby) on OS X.




I don't think this helps Roswell in any ways, though.




In my opinion, Roswell shouldn't do anything automatically unless it's quite obvious. Raising an error would be a better choice.

**Comment by snmsts** [comment]
Thank you for your investigation.

my current idea is.
- delete whatever impl.(may be,it should have some treat on windows,deleting exe file by it self is not allowed by default (not sure))
- treat config (I'm still thinking about it but basically meaning blank 'ros config' default.lisp and lisp.version if deleted impl were exactly the case)

**Comment by snmsts** [comment]
I stop worry about it. people keep using roswell never uninstall the last sbcl-bin. and people who try uninstall it will uninstall roswell as well. No problem. No need to care.
