### ISSUE TITLE
uname failed

### ISSUE THREAD

**Issue by gas2serra** [roswell/roswell#310]
Hi,
it was an old issue #265.
It was fixed by reinstalling from scratch. In my case it does not work.
I think that the problem is the name of the function "uname". Debugging the code I have seen that `curl_easy_perform(curl); ` calls uname...
Changing the name of `uname` resolves the problem.

## Environment

```
Linux desktop 4.15.11-1-ARCH #1 SMP PREEMPT Mon Mar 19 18:21:03 UTC 2018 x86_64 GNU/Linux
roswell 18.3.10.89(9d72eb7)
archlinux
```
## How to reproduce the issue
```
yaourt -R roswell
rm -rf ~/.roswell
yaourt -S roswell

ros
```
## Actual result

```
Installing sbcl-bin...
No SBCL version specified. Downloading platform-table.html to see the available versions...
[##########################################################################]100%
Installing sbcl-bin/1.4.5...
Downloading https://github.com/roswell/sbcl_bin/releases/download/1.4.5/sbcl-1.4.5-x86-64-linux-binary.tar.bz2
Assertion 'uname(&u) >= 0' failed at ../systemd-stable/src/basic/hostname-util.c:58, function gethostname_malloc(). Aborting.
Segmentation fault (core dumped)

```

Best regards,
Alessandro

**Comment by snmsts** [comment]
really? try ed0630c and report it fix or not.

**Comment by gas2serra** [comment]
It works!
The problem arises after a huge update I did in archlinux. I really don't know if the problem is the new version of the compiler, the libc, the kernel or something else.
Thanks,
Alessandro

**Comment by snmsts** [comment]
thank you
