### ISSUE TITLE
Use qlfile when installing a script from GitHub

### ISSUE THREAD

**Issue by svetlyak40wt** [roswell/roswell#312]
It would be useful if roswell run `qlot install` if it finds a qlfile or qlfile.lock inside the repository of the script.

For example, I you can run:

```
ros install 40ants/cl-info
```

But this script requires `40ants/defmain`, which is not in the Quicklisp yet. But I want to have ability to add a qlfile into the 40ants/cl-info repository with following content:

```
github defmain 40ants/defmain
```

And when roswell should setup this additional quicklisp ditribution automatically using `qlot install` if it Qlot is available.

**Comment by snmsts** [comment]
responsibility of roswell and qlot is different, and qlot install would install different place than roswell. It'll introduce something difficult for me.
If the dependency is complex to solve, I need to consider something new but with the simple one

```
#+ros.installing
(roswell:roswell '("install" "40ants/defmain"))
```

in cl-info.asd is enough for me.

btw put a binary file in roswell directory is not good.

**Comment by svetlyak40wt** [comment]
Great! I've added this piece of code into the cl-info's defsystem:

```
:perform (compile-op :before (o c)
                       #+ros.installing
                       (roswell:roswell '("install" "40ants/defmain")))
```

And it works.

BTW I don't put a binary into the Roswell's bin directory. Why did you decide I do?

**Comment by snmsts** [comment]
isn't it binary?
https://github.com/40ants/cl-info/blob/master/roswell/cl-info

**Comment by svetlyak40wt** [comment]
Ops, seems I've commited it unintentionally. Good catch. Removed!
