### ISSUE TITLE
install-for-ci.sh LISP=ecl: ERROR in extend-quicklisp.c: too few arguments to function ‘cl_remove’

### ISSUE THREAD

**Issue by avodonosov** [roswell/roswell#343]
https://travis-ci.org/cl-plus-ssl/cl-plus-ssl/jobs/434573575

**Comment by avodonosov** [comment]
Seems to be caused by this line: https://github.com/roswell/roswell/blob/release/lisp/extend-quicklisp.lisp#L134

**Comment by snmsts** [comment]
oh ok. I fix it.

**Comment by avodonosov** [comment]
Thanks.

How soon it will be in the release branch? (Does it make sense to wait or better to switch ROSWELL_BRANCH to master in our .travis.yml?)

**Comment by snmsts** [comment]
not now.I'm planning to do it in a few days.
