### ISSUE TITLE
How to update libraries/softwares installed via `ros install`?

### ISSUE THREAD

**Issue by koji-kojiro** [roswell/roswell#349]
In case a library `foo` installed using `ros install`, how can I update that?

`ros install bar/foo` dose not update `foo`.
I think I need to do followings to update `foo`:

1. remove old version of `foo`
2. `ros install  bar/foo` again

or, `git pull` at `~/.roswell/local-project/bar/foo/`

## Environment

```
# result of evaluating
uname -a
Linux localhost 3.14.0 #1 SMP PREEMPT Mon Dec 10 23:49:58 PST 2018 armv7l GNU/Linux
ros --version    # if roswell runs successfully
roswell 19.1.10.96(32e380a)
ros config
ccl-bin.version=1.11.5
setup.time=3756954298
sbcl-bin.version=1.4.11
default.lisp=ccl-bin

Possible subcommands:
set
show
```

## How to reproduce the issue

```sh
$ ros install bar/foo
```

## Expected behavior

`bar/foo` updated.

## Actual result

not updated.

**Comment by snmsts** [comment]
``ros update foo`` or ``ros git foo pull``

**Comment by koji-kojiro** [comment]
It worked,  thanks.
But I think it's better to be `ros update bar/foo` for consistency.
