### ISSUE TITLE
Install CCL from git master

### ISSUE THREAD

**Issue by phoe** [roswell/roswell#350]
The current stable version of CCL is quite old. I suggest adding the command `ros use ccl` that downloads the latest release of `ccl-bin`, fetches the latest git master from https://github.com/Clozure/ccl/archive/master.zip, builds it using `ccl-bin` and installs the resulting binary into Roswell.

**Comment by snmsts** [comment]
This should be claimed to them to release.Not to me.

**Comment by snmsts** [comment]
... clisp as well.

**Comment by phoe** [comment]
If one wanted to implement this in roswell, where should they start? Where is the current source code for installing SBCL from source?

**Comment by snmsts** [comment]
hmmm.... for new implementation
``lisp/install*`` ``src/cmd-run*`` should be modified.
