### ISSUE TITLE
How can I distribute a .ros script with the .so dynamic libraries used?

### ISSUE THREAD

**Issue by ryukinix** [roswell/roswell#352]
Suppose I'm making a game which the launcher it's written as a .ros script. How I can distribute my software to load custom libraries, for instance, from the current working directory? 

My main problem today to distribute common lisp software is this and Roswell is great, but I don't understand how I can do properly this part. I don't know if I need add some hack about LD_LIBRARY_PATH...

**Comment by snmsts** [comment]
I think it differs by platform. May I have more specific information about your problem?

**Comment by ryukinix** [comment]
I'm talking about distributing a standalone application to Linux-based operating systems. It would be really nice if we have some public info about how we deliver reliable software without external dependencies. 

In the past I tried to share a binary dump of SBCL for this application: https://github.com/ryukinix/lisp-chat. Works on my machine, but not in others without hotfixes.

My problem is: my software depends of GNU Readline of a specific version and I'm not distributing it together because I don't know how I can make it. I'm wondering if roswell could help on that since it's a package manager and binary builder.

**Comment by ryukinix** [comment]
Here how this problem is solved for C/C++ programs on Linux: https://aimlesslygoingforward.com/blog/2014/01/19/bundling-shared-libraries-on-linux/

I'd like if we can accomplish the same one day.

**Comment by guicho271828** [comment]
For the C/C++ solution (rpath), you can accomplish the same through pushing the `lib` path in `cffi:*foreign-library-directories*`

**Comment by guicho271828** [comment]
To implement it in roswell, adding `-rpath` option to `ros build` might be nice

**Comment by ryukinix** [comment]
Thank youuuu!!!

**Comment by ryukinix** [comment]
> For the C/C++ solution (rpath), you can accomplish the same through pushing the lib path in cffi:*foreign-library-directories*


I can add a relative path without any problem?

**Comment by ryukinix** [comment]
Another question: Is there a nice way to get a list of the current foreign dynamic libraries loaded?

**Comment by ryukinix** [comment]
Just to share my research:

Related problems & Solutions:

+ [Portacle Shared Libraries][1]
+ [How can I make sure ASDF loads a dynamic foreign library every time my system is loaded?][2]
+ [Delivering Common Lisp][3]
+ [How to specify CFFI load path?][4]
+ [How to unload dynamic libraries before save-and-die?][5]
+ [Distributing shared libraries with the executable on Linux (C/C++)][6]

[1]: https://github.com/portacle/portacle/issues/4
[2]: https://stackoverflow.com/questions/39885605/how-can-i-make-sure-asdf-loads-a-dynamic-foreign-library-every-time-my-system-is
[3]: https://borodust.org/delivering-common-lisp#bundle
[4]: https://sourceforge.net/p/sbcl/mailman/message/32104251/
[5]: https://sourceforge.net/p/sbcl/mailman/message/20522546/
[6]: https://aimlesslygoingforward.com/blog/2014/01/19/bundling-shared-libraries-on-linux/

I'm still having problems. :[ 

After `save-and-lisp-die` generate the binary dump, CFFI cannot find my libreadline library from the current working directory without passing `LD_LIBRARY_PATH=.`... I'm trying making a concept here about these problems and a possible solution: https://github.com/ryukinix/lisp-chat/pull/20. 

I'm still not using .ros. I'd like to use if would have something like `-rpath` as @guicho271828 said. Sorry if this is not right place to discuss this.

**Comment by snmsts** [comment]
close?

**Comment by ryukinix** [comment]
The problem is not solve for Roswell actually, because the main question is not solved or even discussed, only my use-case which was not aided by Roswell and I was asking for it.

But if there is no interest to do that, I'm ok to close this issue. Maybe what I'm asking is too much, but really would be cool a `-rpath` option on `build` command dealing with `cffi`, `foreign-load-libraries` and distributing the loaded libraries automagically. That it's what a expect from a build/package system: help me to distribute my software.

**Comment by snmsts** [comment]
for roswell I'm not interest in including external library specific code.
