### ISSUE TITLE
slime-compile-file fails due to read error

### ISSUE THREAD

**Issue by wrycode** [roswell/roswell#354]
Hello, I am trying to get the Slime integration working but running `slime-compile-file` gives the following read error:

```
cd /home/wrycode/code/roswell-testing/
1 compiler notes:

hello.ros:1:2:
  read-error: 
    READ error during COMPILE-FILE:
    
      no dispatch function defined for #\!
    
        Line: 1, Column: 2, File-Position: 1
    
        Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/wrycode/code/roswell-testing/hello.ros" {1001B14E23}>

Compilation failed.
```
This error would make sense to me if I had not followed the instructions in [Initial Recommended Setup](https://github.com/roswell/roswell/wiki/Initial-Recommended-Setup), however I think I followed them correctly. Here is the contents of my *inferior-lisp* buffer:

```
(progn (load "/home/wrycode/.roswell/lisp/slime/2019.02.02/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init") :from-emacs t) (funcall (read-from-string "swank:start-server") "/tmp/slime.24278"))

* ; loading #P"/home/wrycode/.roswell/lisp/slime/2019.02.02/swank-loader.lisp"
WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
;; Swank started at port: 44447.
44447
* WARNING:
   redefining THREAD-FOR-EVALUATION (#<STRUCTURE-CLASS SWANK::MULTITHREADED-CONNECTION>
                                     #<SB-MOP:EQL-SPECIALIZER :FIND-EXISTING>) in DEFMETHOD
```

## Environment

```
# result of evaluating
uname -a :  Linux wrycode 4.20.12-arch1-1-ARCH #1 SMP PREEMPT Sat Feb 23 15:11:34 UTC 2019 x86_64 GNU/Linux
ros --version:  roswell 19.1.10.96
ros config: emacs.type=slime
slime.version=2019.02.02
setup.time=3760498020
sbcl-bin.version=1.4.16
default.lisp=sbcl-bin

Possible subcommands:
set
show

```
## How to reproduce the issue
add the recommended lines to .emacs
```sh
ros install sbcl
ros install slime
ros init hello
ros emacs &
```
I added a print statement to the main function and tried to compile with slime-compile-file
## Expected behavior
I was expecting Slime to automatically ignore the first 5 lines and compile the rest of the file using roswell/sbcl. 

Instead, I got the read error because Slime tried to read the first line as a lisp expression.

Am I misunderstanding how the Slime integration is supposed to work?

**Comment by snmsts** [comment]
would you try ``(roswell:ignore-shebang)`` before ``slime-compile-file``?

**Comment by wrycode** [comment]
Before I got your comment I tried to reinstall Roswell's libraries from scratch (including the slime helper) but I got the following output when running `ros setup` : 
https://0x0.st/zouX.txt

This is weird because `ros setup` worked the first time. I cleared the roswell installation by deleting `~/.roswell/`.

**Comment by snmsts** [comment]
It is caused because sbcl-bin version changed...
.... sorry I'll fix it.

**Comment by snmsts** [comment]
see #355

**Comment by wrycode** [comment]
Excellent, that is fixed for me in v19.3.10.97. I will test the Slime helper in a minute.

@tmccombs I'm mentioning you as a friendly notification that your AUR package version and md5sums will need to be updated at some point for Roswell

**Comment by wrycode** [comment]
`(roswell:ignore-shebang)` does allow Slime to compile the file. Perhaps this should be added to the [Initial Recommended Setup](https://github.com/roswell/roswell/wiki/Initial-Recommended-Setup)?

**Comment by snmsts** [comment]
I don't think so.

* I haven't seen want to compile ros file to compile until this issue. (I recommend use ros as just thin wrapper for command line)
* It has side effect to the language. though it is small side effect I don't like it.

I think refer to the ``(roswell:ignore-shenbang)`` could be nice.

**Comment by ackalker** [comment]
@snmsts I'm sorry but have to disagree with you about not mentioning `(ros:ignore-shebang)`, AFAICT it is the most convenient way to be able to debug ros files with all the niceties of SLIME.

An example of me trying to fix an issue with `ros list`:
```
$ ros list
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
Possible subcommands:
asdf
dump
env
git
installed
versions
```
Why does this signal an error? (And why can't I get more verbose output by using `-v` option to `ros`?
I haven't found the answer to those, so I wanted to go hunt about in `list.ros` using Emacs and SLIME.

```
; SLIME 2.23
CL-USER> (load "/etc/roswell/list.ros")
; Evaluation aborted on #<SB-C::INPUT-ERROR-IN-LOAD {1001D8EF53}>.
CL-USER> *runtime-pathname*
#P"/home/miki/.roswell/impls/x86-64/linux/sbcl-bin/1.5.2/bin/sbcl"
CL-USER> (ros:ignore-shebang)
T
CL-USER> (load "/etc/roswell/list.ros")
T
LIST.3672012243> (main)
...
```
If I hadn't found this issue and your mention of `(roswell:ignore-shebang)` (apparently it's now `(ros:ignore-shebang)`, I wouldn't have known how to proceed.

**Comment by snmsts** [comment]
hmm.Question could be where would you like to know ignore-shebang or where the information should be put?

**Comment by ackalker** [comment]
I guess the obviously best place would be in a paragraph about debugging ros scripts. I think it makes sense there, because the "side effect to the language" which you mentioned seems to apply there anyhow, so the system should behave similarly whether debugging or running the script.
