### ISSUE TITLE
Proposal: cross platform binary 

### ISSUE THREAD

**Issue by ta2gch** [roswell/roswell#365]
Hello, I made a new binary package for roswell as AppImage.

> AppImage is a format for distributing portable software on Linux without needing superuser permissions to install the application.[1] It tries also to allow Linux distribution-agnostic binary software deployment for application developers,[2] also called Upstream packaging. Released first in 2004 under the name klik, it was continuously developed, then renamed in 2011 to PortableLinuxApps and later in 2013 to AppImage. (Wikipedia)

I have a  script for this package in my repository forked from this repository.
Could I send the pull request ? I request you to upload this package the GitHub releases.

Because AppImage requires no tools for users to install any packages,  this format makes roswell better for users and free them from any tools such as apt, yum, linuxbrew.

Thank you.

**Comment by ryukinix** [comment]
Great!

**Comment by snmsts** [comment]
I tested and merged... Does it work?

**Comment by ta2gch** [comment]
Thank you for that, however, it doesn't work when we run it out of the built environment.
For example, the following case fails.

- Build roswell.AppImage in Linux A
- Run roswell.AppImage in Linux B

So, your comment is right.

I'm trying to solve this case.

**Comment by ta2gch** [comment]
Above comment is solved by @snmsts . Thank you very much for you help!
