### ISSUE TITLE
Installing roswell for CI on Windows

### ISSUE THREAD

**Issue by iamFIREcracker** [roswell/roswell#374]
I was doing some experiments with roswell on travis-ci lately, and noticed that the default [install-for-ci.sh](https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh) script works quite nicely on Windows too (after you installed pre-compiled binaries; `ros` will be found somewhere on `$PATH`, and the script will then jump to the setup phase skipping the install/compile one).

Anyway, is there appetite for enhancing the script to support Windows?  If so I could try and put together a PR; for now, I wrapped that logic into another script (that you can find [here](https://gist.github.com/iamFIREcracker/3564db5a24e296e087da49513d6cd00c)), and as you can see it's really simple:

- Check for `/tmp/roswell` to be in `$PATH`
- Download/unpack pre-compiled binaries
- Delegate to [install-for-ci.sh](https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh)

Now, I am not 100% sold on step 1 above, but honestly I could not come up with a way to update `$PATH` for the current process (so `ros` could be set up), and for subsequent ones (i.e. CI build steps).

**Comment by snmsts** [comment]
Great work.
Are there ci service which you can use the script with?

**Comment by iamFIREcracker** [comment]
I only tested it with travis-ci, but I don't see why it shouldn't work with other services.   If any of you guys is using a different system and is willing to help out, please give it a go, [here](https://github.com/iamFIREcracker/cg/blob/master/.travis.yml) you can find the travis-ci configuration I used to pre-compile (Linux, macOS, and Windows) a CL command line application I recently wrote -- most important bits:

* Windows-only: add `/tmp/roswell` to `$PATH`
* `curl -L https://gist.githubusercontent.com/iamFIREcracker/3564db5a24e296e087da49513d6cd00c/raw/4e356d00a98bb09c73c131c8c9db9f6fbd1cf018/roswell-install-for-ci.sh | sh`

And that's it, `ros` should now be available for you to use (i.e. `make binary-ros` in my case)!

**Comment by snmsts** [comment]
Ok I'll manage to merge your experiment.  in a few days thanks.

**Comment by snmsts** [comment]
https://github.com/roswell/travis-windows I'm testing... not finished.

**Comment by snmsts** [comment]
I think you don't need your hack anymore.

**Comment by iamFIREcracker** [comment]
I see you:

- Removed the guard to check that `/tmp/roswell` was listed in `$PATH`
- Moved the unzipped binaries inside `~/.roswell/bin`

Does it mean we don't have to add `/tmp/roswell` (or `~/.roswell/bin`) to `$PATH` anymore?  If not the case, don't you think it's better to make the script fail early, with a *controlled* message? (e.g. `/tmp/roswell not found in $PATH`)

Thanks for taking the time to look into this.

**Comment by snmsts** [comment]
would be ok to set ``/usr/bin`` for ci?

**Comment by snmsts** [comment]
anyway now I'm using windows on this repo.
https://travis-ci.org/roswell/roswell/jobs/541115985
Thank you!
