### ISSUE TITLE
Github Description

### ISSUE THREAD

**Issue by UlisseMini** [roswell/roswell#376]
The github description `intend to be a lisp installer and launcher for major environment that just work.`

Should be
`intends to be a lisp installer, launcher and major environment that just works.`
or something along these lines.

**Comment by snmsts** [comment]
grammar... I'm not sure...

(I) intend (Roswell) to be a launcher for major (lisp related) environment that just work.

**Comment by snmsts** [comment]
better expression? Thank you very much for suggestion.

**Comment by UlisseMini** [comment]
I intend Roswell to be a launcher for a major (lisp related) environment that just works.
Would be better.

**Comment by snmsts** [comment]
edited.
