### ISSUE TITLE
Infinitely hooked on trying to install ASDF

### ISSUE THREAD

**Issue by JotaPe** [roswell/roswell#379]
For better utilizing the limited human resources, please include the following
information when reporting an issue. Issues which do not follow the
format may be immediately closed without review.

## Environment

```
# result of evaluating
Linux endurance 5.2.2-artix1-1-ARTIX #1 SMP PREEMPT Sun Jul 21 21:15:22 UTC 2019 x86_64 GNU/Linux
roswell 19.06.10.100(NO-GIT-REVISION)
emacs.type=slime
slime.version=2019.07.11
setup.time=3773282872
sbcl-bin.version=1.5.4
default.lisp=sbcl-bin
```

We may assign explanatory tags to bad questions instead of replying to it.
See this famous text on how to ask good questions http://catb.org/~esr/faqs/smart-questions.html

## How to reproduce the issue

```sh
ros install asdf
```

## Expected behavior

```sh
Installing ASDF without any problems
```

## Actual result

```sh
Infinitely spawning new SBCL threads and doing this for every command
```

**Comment by JotaPe** [comment]
![photo_2019-07-28_05-58-22](https://user-images.githubusercontent.com/17516509/62004534-e8d1bd80-b115-11e9-8e03-135cd7a1aa00.jpg)

**Comment by JotaPe** [comment]
After doing this and killing all the SBCL threads, any new commands I try to do have the same behaviour of infinitely spawning SBCL threads.

This images say it all.

**Comment by ryukinix** [comment]
That's completely insane.

**Comment by jnc-nj** [comment]
sbcl 1.5.4 seems to have a lot of issues with roswell, i've downgraded to 1.4.1 just to avoid them.

**Comment by guicho271828** [comment]
hmm, 1.5.2 had no issues on Ubuntu 18.04.

**Comment by JotaPe** [comment]
Just to add here.
`(ql:quickload :asdf)`
Works fine, so this is a only roswell problem.

**Comment by snmsts** [comment]
confirmed... hm...

**Comment by svetlyak40wt** [comment]
I have the same issue. But only on Linux.

**Comment by snmsts** [comment]
hope fixed. @JotaPe @svetlyak40wt ?

**Comment by svetlyak40wt** [comment]
Will try this fix tonight!

**Comment by svetlyak40wt** [comment]
Oh! It works for me now!

Thank you!

**Comment by svetlyak40wt** [comment]
Interesting. Why did it break at some moment?

I tried to figure it out myself, but only found that "probably it is somewhere in the `opt` func, may be related to the way how SBCL flushes streams to the disk."

**Comment by snmsts** [comment]
it happend because init.lisp is read for dump file created and the value ``(opt "asdf.version")`` is not changed even when ``.roswell/config`` is already changed. I don't remember from when it is the problem and I didn't test it well...
