### ISSUE TITLE
Change of release tag version mechanism

### ISSUE THREAD

**Issue by sheepduke** [roswell/roswell#381]
## Environment

```
# result of evaluating
$ uname -a
Linux home 5.1.3-gentoo #1 SMP Wed May 22 05:36:16 CST 2019 x86_64 AMD Ryzen 7 2700X Eight-Core Processor AuthenticAMD GNU/Linux

$ ros --version    # if roswell runs successfully
roswell 19.3.10.97

$ ros config
sigsegv.version=2.11
ffcall.version=ffcall-1-10
sbcl.version=1.4.16
ecl.version=16.1.3
setup.time=3759919648
sbcl-bin.version=1.4.1
default.lisp=sbcl

Possible subcommands:
set
show
```

## How to reproduce the issue

The version number of recent 2 releases are `19.0x.xx.xx`.

## Expected behavior

Before it was like `19.4.10.98`, i.e. not `19.04`.

Is this change intended?

This is important because I have added the package into Gentoo portage.

The change in version number breaks the upgrading due to the inconsistency. In Gentoo `19.3` is larger than `19.06`.

**Comment by snmsts** [comment]
intended https://github.com/roswell/roswell/commit/bfaa3c1af8e2b5a9b7bb5d9facaa0f5fcd3658a6#diff-d36df04faf029bd99773735c7a469975

I don't have idea version comparator behavior on gentoo.are there no way to deal with it gentoo side?

**Comment by sheepduke** [comment]
It should be possible to perform some (IMHO ugly) hack in Gentoo side, I am not sure.

But if it intended, at least this problem will be solved in `20.xx` versions since it is naturally larger than `19.xx`.

Since it is not a bug, I will close this issue then.
