### ISSUE TITLE
ros init test -> ros build test.ros fails

### ISSUE THREAD

**Issue by jnc-nj** [roswell/roswell#382]
see #380 

For better utilizing the limited human resources, please include the following
information when reporting an issue. Issues which do not follow the
format may be immediately closed without review.

## Environment

```
macOS High Sierra 10.13.6
roswell (brew) 19.06.10.100(NO-GIT-REVISION)
sbcl 1.5.1 to sbcl 1.5.5 fails
sbcl 1.4.x works
```

We may assign explanatory tags to bad questions instead of replying to it.
See this famous text on how to ask good questions http://catb.org/~esr/faqs/smart-questions.html

## How to reproduce the issue

```
ros init test
ros build test.ros
creating a file manually in accordance with https://roswell.github.io/Roswell-as-a-Scripting-Environment.html is failing as well
```

## Expected behavior

```
build to go through
```

## Actual result

```
Unhandled SIMPLE-ERROR: 'test.ros' is not acceptable for build.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1005E3F733}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100641185B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100641182B}>)
3: (SB-DEBUG:PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDERR* {10001AD263}> :START 0 :FROM :INTERRUPTED-FRAME :COUNT NIL :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "'~A' is not acceptable for build." {100640FC93}> #<unavailable argument>)
5: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "'~A' is not acceptable for build." {100640FC93}>)
6: (INVOKE-DEBUGGER #<SIMPLE-ERROR "'~A' is not acceptable for build." {100640FC93}>)
7: (ERROR "'~A' is not acceptable for build." "test.ros")
8: (MAIN #<unavailable &REST argument>)
9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
10: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
11: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL #<NULL-LEXENV>)
12: ((FLET SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL)
13: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {1005E65243}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
14: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {1005E65243}> NIL)
15: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {1005E65243}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
16: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" {1005E62C93}>)
17: (ROSWELL:SCRIPT "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" "test.ros")
18: (ROSWELL:RUN ((:SCRIPT "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" "test.ros") (:QUIT NIL)))
19: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:SCRIPT "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" "test.ros") (:QUIT NIL)))) #<NULL-LEXENV>)
20: (EVAL (ROSWELL:RUN (QUOTE ((:SCRIPT "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" "test.ros") (:QUIT NIL)))))
21: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:script \"/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros\"\"test.ros\")(:quit ())))")))
22: (SB-IMPL::TOPLEVEL-INIT)
23: ((FLET #:WITHOUT-INTERRUPTS-BODY-85 :IN SB-EXT:SAVE-LISP-AND-DIE))
24: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
```

**Comment by snmsts** [comment]
something seems wrong for me...

would you show the result of `ros -v build test.ros`?

**Comment by jnc-nj** [comment]
> something seems wrong for me...
> 
> would you show the result of `ros -v build test.ros`?

`bash-3.2$ ros -v build test.ros
opt:verbose:1
dispatch:build,name=top
proc_cmd:
dispatch:/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros,name=top
proc_cmd:
cmd_script_frontend:0
frontend:script_*:argc=2 argv[0]=/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros
ros_script_cmd=exec ros +Q -m roswell -N roswell -- $0 "$@"
dispatch:+Q,name=top
proc_options:+Q:top
opt:no-quicklisp:0
dispatch:-m,name=top
proc_options:-m:top
get_opt(image,0)=(null)
take1:image:roswell,(null)
set_opt(image)='roswell'
dispatch:-N,name=top
proc_options:-N:top
get_opt(roswellenv,0)=(null)
take1:roswellenv:roswell,(null)
set_opt(roswellenv)='roswell'
dispatch:--,name=top
proc_options:--:top
cmd_script_frontend:1
cmd_script
get_opt(program,0)=(null)
script_:argc=3 argv[0]=--
current=(null)
set_opt(script)='"/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros""test.ros"'
cmd_run_star:1:argv[0],script
get_opt(image,0)=roswell
get_opt(roswellenv,0)=roswell
get_opt(roswellenv,1)=roswell
set_env_opt:/Users/asclepius/.roswell/env/roswell/config
set_opt(lisp)='sbcl-bin'
set_opt(sbcl-bin.version)='1.2.11'
get_opt(lisp,1)=sbcl-bin
determin_impl:sbcl-bin
get_opt(sbcl-bin.version,1)=1.2.11
set_opt(impl)='sbcl-bin/1.2.11'
get_opt(quicklisp,0)=(null)
set_opt(quicklisp)='/Users/asclepius/.roswell/lisp/quicklisp/'
set_opt(argv0)='ros'
which cmd:command -v "ros"
which result:/usr/local/bin/ros

set_opt(wargv0)='/usr/local/bin/ros'
set_opt(homedir)='/Users/asclepius/.roswell/'
set_opt(verbose)='1'
set_opt(lispdir)='/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/'
set_opt(patchdir)='/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/patch/'
get_opt(asdf.version,0)=(null)
set_opt(uname)='darwin'
set_opt(uname-m)='x86-64'
get_opt(program,0)=(null)
get_opt(asdf.version,0)=(null)
set_opt(program)=''
get_opt(impl,0)=sbcl-bin/1.2.11
get_opt(help,0)=(null)
get_opt(script,0)="/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros""test.ros"
get_opt(image,0)=roswell
get_opt(program,0)=
get_opt(dynamic-space-size,0)=(null)
get_opt(control-stack-size,0)=(null)
get_opt(without-roswell,0)=(null)
get_opt(enable-debugger,0)=(null)
get_opt(roswellenv,1)=roswell
roswellenv=roswell
get_opt(roswellenv,1)=roswell
get_opt(roswellenv,1)=roswell
get_opt(version,0)=(null)
get_opt(asdf.version,0)=(null)
init.lisp=/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/init.lisp

help=nil script="/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros""test.ros"
get_opt(wrap,1)=(null)
args /Users/asclepius/.roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/bin/sbcl --core /Users/asclepius/.roswell/env/roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/dump/roswell.core --noinform --no-sysinit --no-userinit --disable-debugger --eval (progn #-ros.init(cl:load "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/init.lisp")) --eval (ros:run '((:script "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros""test.ros")(:quit ()))) 
ROS_OPTS (("program""")("uname-m""x86-64")("uname""darwin")("patchdir""/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/patch/")("lispdir""/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/")("verbose""1")("homedir""/Users/asclepius/.roswell/")("wargv0""/usr/local/bin/ros")("argv0""ros")("quicklisp""/Users/asclepius/.roswell/lisp/quicklisp/")("impl""sbcl-bin/1.2.11")("sbcl-bin.version""1.2.11")("lisp""sbcl-bin")("script""\"/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros\"\"test.ros\"")("roswellenv""roswell")("image""roswell")("ecl.version""16.1.2")("sbcl.version""1.5.1")("slime.version""2019.01.07")("setup.time""3773541749")("sbcl-bin.version""1.2.11")("default.lisp""sbcl"))
Unhandled SIMPLE-ERROR: 'test.ros' is not acceptable for build.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1005E3F733}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100670FF3B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100670FF0B}>)
3: (SB-DEBUG:PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDERR* {10001AD263}> :START 0 :FROM :INTERRUPTED-FRAME :COUNT NIL :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "'~A' is not acceptable for build." {100670E383}> #<unavailable argument>)
5: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "'~A' is not acceptable for build." {100670E383}>)
6: (INVOKE-DEBUGGER #<SIMPLE-ERROR "'~A' is not acceptable for build." {100670E383}>)
7: (ERROR "'~A' is not acceptable for build." "test.ros")
8: (MAIN #<unavailable &REST argument>)
9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
10: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
11: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL #<NULL-LEXENV>)
12: ((FLET SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL)
13: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {1005E65243}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
14: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {1005E65243}> NIL)
15: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {1005E65243}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
16: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" {1005E62C93}>)
17: (ROSWELL:SCRIPT "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" "test.ros")
18: (ROSWELL:RUN ((:SCRIPT "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" "test.ros") (:QUIT NIL)))
19: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:SCRIPT "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" "test.ros") (:QUIT NIL)))) #<NULL-LEXENV>)
20: (EVAL (ROSWELL:RUN (QUOTE ((:SCRIPT "/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros" "test.ros") (:QUIT NIL)))))
21: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:script \"/usr/local/Cellar/roswell/19.06.10.100/etc/roswell/build.ros\"\"test.ros\")(:quit ())))")))
22: (SB-IMPL::TOPLEVEL-INIT)
23: ((FLET #:WITHOUT-INTERRUPTS-BODY-85 :IN SB-EXT:SAVE-LISP-AND-DIE))
24: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
bash-3.2$ `

**Comment by snmsts** [comment]
sbcl-bin/1.2.11? it is version released 2015... Would you try backup&delete ``~/.roswell`` then try again?

**Comment by jnc-nj** [comment]
> sbcl-bin/1.2.11? it is version released 2015... Would you try backup&delete `~/.roswell` then try again?

Oh interesting, that means when I input `ros use sbcl/1.5.1` it isn't affecting ros build.
Basically, my `ros build test.ros` is defaulting to sbcl-bin/1.2.11 even though I used `ros use sbcl/1.5.1`
I just tried on my linux machine, and `ros use sbcl/1.5.1` creates the right info in `ros -v build test.ros`.
So it seems to be a mac specific issue.

**Comment by snmsts** [comment]
``sbcl-bin.version`` in ``~/.roswell/env/roswell/config`` is what roswell use for subcommands. If you install sbcl-bin/1.2.11 and edit the config as it should be. You'll have same problem on linux box.

**Comment by jnc-nj** [comment]
> `sbcl-bin.version` in `~/.roswell/env/roswell/config` is what roswell use for subcommands. If you install sbcl-bin/1.2.11 and edit the config as it should be. You'll have same problem on linux box.

Ahhhh that explains everything! 
This should probably be part of the tutorial, or at least, more precisely documented as a gotcha.
Thanks a lot for the help though! Can confirm everything is working as expected now.

Love the project, been using it since, well, 2015 I guess.

**Comment by snmsts** [comment]
:) pressure. Thank you.
