### ISSUE TITLE
File collision on Gentoo system

### ISSUE THREAD

**Issue by sheepduke** [roswell/roswell#385]
This is not really an "issue" of Roswell.

Since I have added Roswell into Gentoo package system, I received a bug recently:

https://bugs.gentoo.org/691754

It means that another package `net-libs/librouteros` will install binary `ros` into `/usr/bin/`, which causes conflict with Roswell.

Gentoo system does not allow that. There are several solutions:
1. Change the name of Roswell binary from `ros` to something else. Personally I do not like it.
2. I change the name of `ros` binary during installation, to `roswell` maybe. This requires Roswell to declare this difference for Gentoo system in README or Wiki.
3. I add a block to the 2 packages, so that only one of them can be installed at the same time. It seems that `net-libs/librouteros` is a popular package so this might bring inconvenience to Gentoo/Roswell users.

I cannot decide it myself.

What do you think?

**Comment by Hexstream** [comment]
Gentoo developer Joonas Niilola [said](https://bugs.gentoo.org/691754#c7) this:

> A man page collision wouldve been doable with a soft blocker. Since the binary file collides, I think hard blocker is needed in roswell. Well, it doesnt seem like librouteros is exactly a popular package.

Based on this, I would go with option 3.

(He said that "it doesn't seem like librouteros is exactly a popular package", while you say that it seems that librouteros is a popular package. Did you misread him?)

**Comment by sheepduke** [comment]
Oops. I was stupid. 

It was `doesnt` not `does`. Better written `doesn't` anyway...

I will make add a blocker then.

Issue closed.

**Comment by snmsts** [comment]
@sheepduke  May I ask you edit here for gentoo? https://github.com/roswell/roswell/wiki/Installation

**Comment by sheepduke** [comment]
> @sheepduke  May I ask you edit here for gentoo? https://github.com/roswell/roswell/wiki/Installation
>
Done. Please let me know if you are not happy with it ;-)

**Comment by snmsts** [comment]
Perfect. Thank you!
