### ISSUE TITLE
Cannot run "ros setup" in CentOS 6.10 after SBCL 1.5.8 release 

### ISSUE THREAD

**Issue by jespertp-systematic** [roswell/roswell#397]
## Environment
The problem is that SBCL 1.5.8 requires GLIBC_2.14
SBCL 1.5.7 worked fine on CentOS 6.10 and Red Hat Enterprise Linux 6.10, so if I could somehow tell roswell to use SBCL 1.5.7 instead, everything would be fine.
```
# result of evaluating
"uname -a" in a docker container with CentOS 6.10
Linux af735a613396 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## How to reproduce the issue
In a docker container with CentOS 6.10 with a local source installation:
```sh
rowell_archive_url='https://github.com/roswell/roswell/archive/release.tar.gz'
curl -SL ${rowell_archive_url} \
  | tar -xzC /tmp/ \
  && pushd /tmp/roswell-release \
  && sh bootstrap \
  && ./configure --prefix=$HOME/.local/ \
  && make \
  && make install \
  && popd \
  && rm -rfv /tmp/roswell-release
echo 'PATH=$HOME/.local/bin:$PATH' >> ~/.profile
export PATH=$HOME/.local/bin:$PATH
ros setup
```

## Expected behavior
Something like the following makes roswell use a predetermined SBCL version.
```sh
ros -L sbcl-bin/1.5.7 setup
```

## Actual result
The attached log file contains the output of "ros -v -v setup"
[ros.log](https://github.com/roswell/roswell/files/3797801/ros.log)

**Comment by jespertp-systematic** [comment]
I have tried to add the version to the ~/.roswell/config file but alas without success.
echo 'sbcl-bin.version	0	1.5.7' >> ~/.roswell/config

**Comment by snmsts** [comment]
'ros install sbcl-bin/1.5.7' before 'ros setup' might help... 

may I see what kind of problem with 1.5.8 with cent os?

**Comment by jespertp-systematic** [comment]
That works like a charm :-)
Sorry to have missed that.
