### ISSUE TITLE
Functions can only be used after they have been declared.

### ISSUE THREAD

**Issue by equwal** [roswell/roswell#399]
Roswell should be able to compile my lisp code if asked. Currently it can only interpret the forms as a script. 

## Why you want this:

```sh
ros init topology.ros
```
Write this code in it:
```common-lisp
(defun main (&rest argv)
  (declare (ignorable argv))
  (breakit))
(defun breakit () (print 0))
```
Run it
```sh
./topology.ros
```

## Expected behavior
return 0

## Actual result
Style warnings.
```sh
;   Undefined function:
;     BREAKIT
;   caught 1 STYLE-WARNING condition
0
```

**Comment by guicho271828** [comment]
it is not an error because it is a style warning,
