### ISSUE TITLE
ros emacs should just start a server, or a new `ros sever`

### ISSUE THREAD

**Issue by equwal** [roswell/roswell#415]
`ros emacs` installs SLIME into Emacs and starts it with an instance of a
roswell lisp running.

Instead, I think it is better to have a command like

`ros server [port|file]` that starts a roswell lisp. This way Emacs SLIME or
SLY, a vim package, or another IDE can straightforwardly hook into the socket,
and not have roswell opinionated about what IDE is used.

As a primer, here are code segments that I use in my StumpWM server and SLY
client.

```common-lisp
;;; In stumpwm's init, running on the StumpWM server instance
(slynk:create-server :port 4004
  :style slynk:*communication-style*
  :dont-close t)
```
```emacs-lisp
;;; In my emacs config
(add-hook 'sly-mode-hook
            (lambda ()
              ;; Connect to StumpWM if there is no other connection to it. The
              ;; first sly opened will attempt to connect to StumpWM.
              (unless (sly-connected-p)
                (or (save-excursion
                      (sly-connect "localhost" 4004 'utf-8-linux)
                      t)
                    (save-excursion
                      (sly))))))
```

**Comment by snmsts** [comment]
https://github.com/fukamachi/swank.ros like this?

**Comment by snmsts** [comment]
I don't have idea ''ros server'' should behave in general. general **server** should support all of protocol like swank/slynk/jsonrpc or something would introduce in the future.

If you would like to support slynk personally with with ``ros server`` , you can make your own sub command.(see https://github.com/t-sin/ros-tap )

``ros emacs`` is just intended to be a **minimal** emacs setting for non emacs users.
I'm not emacs user anymore and I don't want to contaminate existing ``.emacs`` at all.
that's the reason why design of ``ros emacs`` is not for convenience for emacs users.
