### ISSUE TITLE
CCL 1.12 fails to install

### ISSUE THREAD

**Issue by neil-lindquist** [roswell/roswell#422]
Last night, the I had a Travis build fail because a directory for CCL was missing.  This failure occured for both Linux and OSX.  I re-ran both jobs and got the same error.  All of the other implementations passed their tests correctly.

It looks a the version of CCL that Roswell attempted to install was added to Roswell yesterday, about 9 hours before my tests failed.

## Environment

Travis's log is at https://travis-ci.org/github/neil-lindquist/linear-programming/jobs/677535023 .  I don't know how to access the requested information from that system.

## How to reproduce the issue

On travis:
```sh
export PATH=~/.roswell/bin:$PATH
export ROSWELL_INSTALL_DIR=$HOME/.roswell
export LISP=ccl-bin
curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

```

## Expected behavior

Roswell should install without errors.

## Actual result

Fails with the following error (the log has the full stacktrace and stdout, so I omitted it here for brevity's sake)

```sh
Extracting archive:/home/travis/.roswell/archives/ccl-1.12-linuxx86.tar.gz

Unhandled SB-INT:SIMPLE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING

                                                {1000518083}>:

  Failed to find the TRUENAME of /home/travis/.roswell/impls/x86-64/linux/ccl-bin/ccl/:

    No such file or directory

```

**Comment by snmsts** [comment]
Sorry for inconvenience.
related issue here. https://github.com/Clozure/ccl/issues/296 

fixture plan would follow two steps.

* ccl archives structure would be fixed. (hopefully)
* my [ci](https://github.com/roswell/daily_maintenance/blob/master/ccl-bin/Lakefile) successfully copy archives to https://github.com/roswell/ccl_bin/releases

I can repackage by ci but It would be better ccl maintainers could care roswell.
after the first part are finished. it's my responsibility. so please wait for a while.

**Comment by svetlyak40wt** [comment]
Probably 1.12 version number should be added to the title of this issue to make it more specific?

**Comment by snmsts** [comment]
@neil-lindquist is it ok?

**Comment by neil-lindquist** [comment]
It's running correctly for me again.  Thanks.
