### ISSUE TITLE
load a git dependency in script?

### ISSUE THREAD

**Issue by ailisp** [roswell/roswell#424]
It's nice to have `ros install foo/bar` to install a git dependency. I wonder if there's a way to include a git dependency in a ros script? (So I can use fork of some quicklisp project) Thanks!

**Comment by snmsts** [comment]
not implemented yet but what do you think about ``ros follow-dependency=t install foo/bar`` to do ``git submodule update -i`` on the project directory?

**Comment by ailisp** [comment]
Thanks! Sounds a good work around! I just considered one corner case: what if my project depends on `github.com/foo/bar`, but the original `bar` is on quicklisp. In my project script it's `(ql:quickload :bar)`. If later on I installed `bar` from quicklisp, Can ros script still finds foo/bar?
It seems i'm asking a `ros:quickload` or `ros:load-system` function, which acts like `ros install`, to precisely depends on a fork. I can also help with a PR if you're interested.

**Comment by snmsts** [comment]
```
CL-USER> asdf:*system-definition-search-functions* 
(ROSWELL.UTIL:ROSWELL-INSTALLABLE-SEARCHER ASDF/PACKAGE-INFERRED-SYSTEM:SYSDEF-PACKAGE-INFERRED-SYSTEM-SEARCH ASDF/SYSTEM-REGISTRY:SYSDEF-CENTRAL-REGISTRY-SEARCH ASDF/SYSTEM-REGISTRY:SYSDEF-SOURCE-REGISTRY-SEARCH ROSWELL.UTIL::LOCAL-PROJECTS-SEARCHER QUICKLISP-CLIENT:LOCAL-PROJECTS-SEARCHER QL-DIST:SYSTEM-DEFINITION-SEARCHER)
```

to see this ``ROSWELL.UTIL::LOCAL-PROJECTS-SEARCHER`` is higher priority than ``QL-DIST:SYSTEM-DEFINITION-SEARCHER`` once you installed the project via ``ros install`` asdf can't find quicklisp installed system. 

My original concern was consider you have ``foo`` account and ``foo/bar`` have subsystem ``foo/baz`` then it could have possibly installing ``foo/baz`` twice by direct install with ``ros install foo/baz`` and ``ros follow-dependency=t install foo/bar`` with different state.
It'll introduce chaos and currently I don't plan to manage this kind of complexity.

**Comment by ailisp** [comment]
I see. Thanks!

**Comment by snmsts** [comment]
problem is if submodules are via ssh it asks passphrase and it seems roswell hang up...

**Comment by ailisp** [comment]
That's good enough. I can make sure submodule is via https. If there's a private repo I can use a github access token

**Comment by ailisp** [comment]
It works after https://github.com/roswell/roswell/commit/14605f9b4dc840b3e71fdcdd3593fdeb74d4e698, looking forward to next roswell release!

**Comment by snmsts** [comment]
:) released
