### ISSUE TITLE
[Support] Asking for "LTS" versions

### ISSUE THREAD

**Issue by sheepduke** [roswell/roswell#435]
Hi folks,

This is not really a bug report. 

I am maintaining Gentoo Roswell package and I would like to remove some out-of-date versions.

Could you please let me know which version are considered "stable" so that I will keep them and delete the others?

Thanks!

**Comment by snmsts** [comment]
so far I don't test any old versions and there's no branch policy for roswell. It's small project and there's  no demand to backports bugs and there's no drastic changes which everyone complains.
It might safe to say over a year version I would take it as out-of-date. 
What do you think?

**Comment by sheepduke** [comment]
Sounds reasonable. I will just keep versions of recent one year.

Thanks!

**Comment by snmsts** [comment]
Thank you!
