### ISSUE TITLE
icon for windows

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#438]
does anyone volunteer help editing icon for roswell for windows?
https://en.wikipedia.org/wiki/ICO_(file_format)

convert it to 32x32 is difficult for me.

**Comment by t-sin** [comment]
Created just now.

This below is a sheet for preview.
![roswell-32x32](https://user-images.githubusercontent.com/4403863/89514651-18c79c80-d811-11ea-821e-173e782822b0.png)

And this is original 32x32 8bit coloured png file. The black (#000000) can be used as transparent color in icon.
![roswell-icon](https://user-images.githubusercontent.com/4403863/89514763-3ac11f00-d811-11ea-9c85-400356e7c080.png)

Feel free for any question.

**Comment by snmsts** [comment]
@t-sin Thank you for great and quick work!
