### ISSUE TITLE
Roswell installs old version of SBCL on Travis CI's OSX machines

### ISSUE THREAD

**Issue by neil-lindquist** [roswell/roswell#439]
I'm using Roswell to install SBCL (among other implementations) on Travis CI for continuous testing.  However, a few days ago, Roswell installed SBCL 1.2.11 on the OSX test (on Linux it installed 2.0.7 as expected).  I've rerun the tests and gotten the same results.

## Environment

Failing (OSX) job: https://travis-ci.org/github/neil-lindquist/linear-programming/jobs/721502294
Passing (Linux) job: https://travis-ci.org/github/neil-lindquist/linear-programming/jobs/721502288
(Lines 320 and 240 is the start of the `install-for-ci.sh` for OSX and Linux, respectively)

The job ran the week before on the same commit and succeeded (although installed SBCL 2.0.6)
Linux: https://travis-ci.org/github/neil-lindquist/linear-programming/jobs/718833587
OSX: https://travis-ci.org/github/neil-lindquist/linear-programming/jobs/718833593

## How to reproduce the issue

I'm guessing this will reproduce for any install of SBCL on Travis's OSX machines.
Specific steps would be to clone my [linear-programming repo](https://github.com/neil-lindquist/linear-programming), enable it on Travis, and trigger a build.

## Expected behavior

Roswell should install a somewhat recent version of SBCL.

## Actual result

Roswell installs SBCL 1.2.11, which is from 2015.

**Comment by smashedtoatoms** [comment]
This is related to [the ticket I opened earlier](https://github.com/roswell/roswell/issues/437).

**Comment by neil-lindquist** [comment]
This appears to be fixed.
