### ISSUE TITLE
ABCL started to fail with "Class not found: com.sun.jna.Pointer". Any updates to ABCL recently?

### ISSUE THREAD

**Issue by avodonosov** [roswell/roswell#448]
For better utilizing the limited human resources, please include the following
information when reporting an issue. Issues which do not follow the
format may be immediately closed without review.

## Environment
That's a Travis CI build: https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/.travis.yml

$ export ROSWELL_BRANCH=release

```
# result of evaluating
uname -a
ros --version    # if roswell runs successfully
ros config
```

We may assign explanatory tags to bad questions instead of replying to it.
See this famous text on how to ask good questions http://catb.org/~esr/faqs/smart-questions.html

## How to reproduce the issue

```sh


```

## Expected behavior

```sh


```

## Actual result

```sh

```

**Comment by avodonosov** [comment]
The issue was caused by Travis CI build VM coming without Apache Maven installed. Previously Maven was available. ABCL needs Maven for CFFI.

Fixed by https://github.com/cl-plus-ssl/cl-plus-ssl/commit/4aca9753a9c6c769b30e5888bab76d2b83314726

**Comment by snmsts** [comment]
Thank you! I have completely no idea.
