### ISSUE TITLE
[Windows10] ros.exe does not run after installing

### ISSUE THREAD

**Issue by kinoshita-lab** [roswell/roswell#462]
## Environment
- Windows 10 Pro Version 2004, OS Build 19041.746
- roswell 20.06.14.107

## How to reproduce the issue
- Follow the instructions on the wiki: https://github.com/roswell/roswell/wiki/Installation#windows]
- Type ```ros``` on cmd.exe

## Expected behavior
- print roswell usage
- back to prompt

## Actual result
- pops up following error dialog(in Japanese environment)
![Screenshot_2](https://user-images.githubusercontent.com/6611/108587271-16d0bf80-7396-11eb-950b-8e1e7b120e13.png)
- back to prompt after clicking "OK" on the dialog

## Further information
- It seems roswell's default environment does not works on the windows environment, simply it lacks zlib1.dll
- sbcl 2.0.0(official windows release) does not have dependency with zlib, but the .msi file contain with roswell is ver. 2.0.2, and it DOES HAVE the dependency with it.

**Comment by peterbn** [comment]
I got the same issue, and was able to move forward by downloading zlib from http://www.winimage.com/zLibDll/zlib123dllx64.zip.

In the zib file, I extracted the `dll_x64/zlibwapi.dll` file to `%USERPROFILE%\.roswell\impls\x86-64\windows\sbcl-bin\2.0.2\bin` and renamed it to `zlib1.dll`.

After that I ran
```
ros install quicklisp
```

And after that I had what appeared to be a functioning roswell environment.

**Comment by kinoshita-lab** [comment]
@peterbn yes, your workaround is absolutely possible solution. Actually I use such kind of solution to make windows installation working.

I want official release would contain the missing dll, or remove the dependency.

As I have noted above, just simply bundle official release(=2.0.0) will immediately remove the problem since it does not have zlib dependency.

I have tried to make such kind of build script but failed. I hope anybody who have enough knowledge will do it in the future...

**Comment by snmsts** [comment]
fixed.

**Comment by kinoshita-lab** [comment]
@snmsts Please tell me the exact commit that has fixed the issue, I can reproduce the problem with the latest release(v21.05.14.109, both github's release and scoop installation according to the roswell's documentation).

**Comment by kinoshita-lab** [comment]
I can fix the problem by removing .roswell folder. Sorry for disturbing!
