### ISSUE TITLE
factorial example application still takes about 180ms to launch with ros build fact.ros and without quicklisp?

### ISSUE THREAD

**Issue by Gira-X** [roswell/roswell#477]
## Environment

```
$ uname -a
Darwin blueberry.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64

$ ros --version
roswell 21.01.14.108(NO-GIT-REVISION)

$ ros config
setup.time=3829267459
sbcl-bin.version=2.1.4
default.lisp=sbcl-bin

Possible subcommands:
set
show
```

## How to reproduce the issue

I followed the steps in https://github.com/roswell/roswell/wiki/Reducing-Startup-Time to reduce the startup time, but the compiled `fact.ros` still needs about 180ms.

This is my `fact.ros`: 

```lisp
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros +Q -- $0 "$@"
|#

(defun fact (n)
  (if (zerop n)
      1
      (* n (fact (1- n)))))

(defun main (n &rest argv)
  (declare (ignore argv))
  (format t "~&Factorial ~D = ~D~%" n (fact (parse-integer n))))
```

```bash
$ ros build fact.ros
WARNING: :SB-EVAL is no longer present in *FEATURES*
compressed 0 bytes into 8 at level -1
compressed 32768 bytes into 278 at level -1
compressed 23756800 bytes into 5748324 at level -1
compressed 1867776 bytes into 531262 at level -1
compressed 11010048 bytes into 3527117 at level -1

$ time ./fact 10
real    0m0.180s
user    0m0.144s
sys     0m0.030s
```

Using `-Q` or `+Q` shows barely any difference, maybe about 20ms.

Any idea how to speed up the compiled executable?
I was hoping to use `roswell` to generate super fast executables as seen in the wiki, but this does not seem to be the case for me.

**Comment by Gira-X** [comment]
As a test I compared the execution time of the executable genereted by `buildapp` where `time` reports about 30ms, so it is a lot faster. I don't think `roswell` should be that slow?

```bash
  buildapp \
  --load fact.lisp \
  --entry main \
  --output hello-world
```

**Comment by mustiboost** [comment]
I have the exact same issue. In your wiki you say that you can speed things up, but that information at this point is incorrect. Even an `sbcl --script ` starts up more than ten times faster than a program compiled with `ros build. ` This is on Ubuntu Linux 20.04 by the way, so it's not just limited to MacOS.

**Comment by guicho271828** [comment]
Have you tried disabling the compression

**Comment by mustiboost** [comment]
Thanks! That solved the problem! I think this should be mentioned in the documentation. I'm pretty sure a lot of people aren't aware that core compression is enabled by default and needs to be explicity disabled to get fast startup times. People then look for other solutions instead of sticking with roswell.

**Comment by mdbergmann** [comment]
How is this being done? Is 'compression' mentioned in the wiki?

**Comment by mustiboost** [comment]
Yes, here: 
https://roswell.github.io/Building-images-and-executables.html
But it should be mentioned here: 

https://roswell.github.io/Roswell-as-a-Scripting-Environment.html

And especially here: 

https://roswell.github.io/Reducing-Startup-Time.html

**Comment by mdbergmann** [comment]
Would be cool if you could add this to the wiki.

**Comment by Gira-X** [comment]
It was added to the wiki, so we can close this issue.
