### ISSUE TITLE
Rosewell -- Cygwin

### ISSUE THREAD

**Issue by manugoswami** [roswell/roswell#485]
Hi Developers,

ROSEWELL fails to build in CYGWIN.

======================================================================
## Environment
CYGWIN Windows 10
------------------------------------------------------------------------------------------------------------------
# result of evaluating
make command results in below error
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
make  all-recursive
make[1]: Entering directory '/cygdrive/d/ons_cb_try/ons_roswell/roswell-master'
Making all in src
make[2]: Entering directory '/cygdrive/d/ons_cb_try/ons_roswell/roswell-master/src'
gcc -DHAVE_CONFIG_H -I. -I..      -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
In file included from opt.h:3,
                 from main.c:1:
util.h:32:10: fatal error: direct.h: No such file or directory
   32 | #include <direct.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:514: main.o] Error 1
make[2]: Leaving directory '/cygdrive/d/ons_cb_try/ons_roswell/roswell-master/src'
make[1]: *** [Makefile:572: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/d/ons_cb_try/ons_roswell/roswell-master'
make: *** [Makefile:430: all] Error 2

rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
## How to reproduce the issue
sh bootstrap
./configure enable_debug
make

eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
## Expected behavior
should compile

## Actual result

Fails to compile

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Warm Regards,
Manu

**Comment by snmsts** [comment]
Thank you. for report. see #345
