### ISSUE TITLE
Is it possible to let roswell use the installation of SBCL from the my package manager

### ISSUE THREAD

**Issue by Inc0n** [roswell/roswell#492]
## Environment
uname:
```
5.13.7-arch1-1
```
ros version:
```
roswell 21.06.14.110(NO-GIT-REVISION)
```
ros config:
```
sbcl-bin.version=2.1.7
default.lisp=sbcl-bin
```

## How to reproduce the issue

1. I had a version of `sbcl` installed already on my machine.
2. Install `roswell`, then simply run `ros`
3. `roswell` will proceed to setup the environment for me, installing `sbcl` and `quicklisp` etc.

## Expected behavior

I would like `roswell` to be able to pick up the fact that there exist a implementation of `sbcl` installed, and to use it instead of installing the setting things up again.

## Actual result

roswell has installed another sbcl for me.

**Comment by guicho271828** [comment]
ros use sbcl/system

**Comment by Inc0n** [comment]
Hi, I really appreciate your message within half a day, however, your response doesn't quite make sense to me, I do not understand what you said meant. 

The situation is as follows, I have a version of `sbcl` installed with my `pacman`, yet installed ros and running, it installed another sbcl in `.roswell/impls/x86-64/linux/`. 

It is not a huge issue, but down to my personal preference, which I would like one copy of it to remain on my machine.

Please clarify whether if this can be done, else I would just migrate my setup to be reliant on `roswell`.

**Comment by snmsts** [comment]
I wrote some code to setup roswell to be dependent on system installed sbcl via ``ros install sbcl-bin/system`` (only when ``$HOME/.roswell`` are not made yet) in the past but Those kind of setup is not well tested and there's no demand by myself. the status of the setup would be It might work but might not work as well. Sorry and I don't care it for now.

I feel it's proper for people who are using ``guix`` or ``nix`` to demand that feature (It's bit tricky so roswell's distributed sbcl wouldn't be run on the system) but your distribution provide ``pacman`` then I'd recommend just to be reliant on ``roswell``.

Thank you @guicho271828 for quick answer.

**Comment by Inc0n** [comment]
Thank you for the help and the information, I guess its time to try out some new stuff then.

**Comment by guicho271828** [comment]
Oh right, it was it sbcl-bin/system , my bad
