### ISSUE TITLE
ROSWELL_INSTALL_DIR has no effect

### ISSUE THREAD

**Issue by gwerbin** [roswell/roswell#493]
## Environment

```
Darwin ___.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64

roswell 21.06.14.110(NO-GIT-REVISION)

setup.time=3838937058
sbcl-bin.version=2.1.7
default.lisp=sbcl-bin
```

## How to reproduce the issue

```sh
rm -rf ~/.roswell
mkdir -p $HOME/a/b/c
export ROSWELL_INSTALL_DIR=$HOME/a/b/c
ros setup
```

## Expected behavior

```sh
Extracting sbcl-bin-2.1.7-x86-64-darwin.tar.bz2 to /Users/____/a/b/c/src/sbcl-2.1.7-x86-64-darwin/
```

## Actual result

```sh
Extracting sbcl-bin-2.1.7-x86-64-darwin.tar.bz2 to /Users/____/.roswell/src/sbcl-2.1.7-x86-64-darwin/
```

**Comment by guicho271828** [comment]
I just bumped into a related problem.

`ROSWELL_INSTALL_DIR` is recognized only by `install-for-ci.sh` script for CI automation.
It controlls where the main binary (`ros`) is installed.

It does NOT control where the resources directory (`$HOME/.roswell`) so what you are trying to do does not work.
So far there does not seem to be a way to control the resource directory in the current roswell.

**Comment by guicho271828** [comment]
Use `ROSWELL_HOME` environment variable.

**Comment by guicho271828** [comment]
be careful:  ROSWELL_HOME must be an absolute pathname.

**Comment by gwerbin** [comment]
Thanks @guicho271828 , is this documented somewhere?
