### ISSUE TITLE
Unclear on structuring porject and .ros file in order to create executable with `ros build`

### ISSUE THREAD

**Issue by alecStewart1** [roswell/roswell#499]
## Problem

I'm a bit confused as to how setup my project to build an executable with Roswell. Running `ros build roswell/cli-program.ros --disable-compression` gives me this error:

```
The name "CLI-PROGRAM/SRC/CLI" does not designate any package.
```

Even though that _is_ a package in my project.

## Info

Here's the `.ros` file:

```lisp
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros +Q -- $0 "$@"
|#

;; TODO is this all correct?

(progn ;;init forms
  (ros:ensure-asdf)
  #+quicklisp(ql:quickload '(osicat 
                             cl-fad 
                             pathname-utils 
                             clingon) ;; <- this package is not in Quicklisp, so I have to figure that out 
                 :silent t))

(defpackage :ros/script/cli-program
  (:use :cl)
  (:import-from :cli-program/src/cli
                #:cli-program/command))
(in-package #:ros/script/cli-program)

(defun main (&rest argv)
  (declare (ignorable argv))
  (let ((app (cli-program/command)))
    (clingon:run app)))
;;; vim: set ft=lisp lisp:

```

Here's the projects ASDF file:

```lisp
(asdf:defsystem "cli-program"
  :name "cli-program"
  :description "A cool CLI Program"
  :long-description "A *very* cool CLI Program"
  :version "0.1.0"
  :author "Alec Stewart <me@meme.com>"
  :maintainer "Alec Stewart <me@meme.com>"
  :license "MIT"
  :homepage "https://github/alecStewart1/cli-program"
  :bug-tracker "https://github/alecStewart1/cli-program"
  :source-control "https://github/alecStewart1/cli-program"
  :depends-on (:uiop
               :osicat
               :cl-fad
               :pathname-utils
               :clingon)
  :pathname #P"src/"
  :serial t
  :components ((:file "envvars")
               (:file "info")
               (:file "types")
               (:file "utils")
               (:file "cmds")
               (:file "cli"))
  :build-pathname "cli-program"
  :in-order-to ((test-op (test-op "cli-program-test"))))

;; TODO maybe actually write the tests
(asdf:defsystem "cli-program-test"
  :name "cli-program-test"
  :description "Tests for CLI Program"
  :long-description "Tests for the CLI Program, mostly using Rove."
  :version "0.1.0"
  :author "Alec Stewart <me@meme.com>"
  :maintainer "Alec Stewart <me@meme.com>"
  :license "MIT"
  :depends-on (:cli-program
               :rove)
  :pathname #P"t/"
  :components ;; TODO
  :perform (test-op (op c) (uiop:symbol-call :rove :run c)) )
```

Here's the package definition in the relevant file that SBCL is saying isn't a package. The file is in `$PROJECT-ROOT/src/cli.lisp`

```lisp
(defpackage :cli-program/src/cli
  (:use :cl)
  (:import-from :cli-program/src/envvars
                #:*cli-program-bin*)
  (:import-from :cli-program/src/info
                #:cli-program-info-data)
  (:import-from :cli-program/src/utils
                #:path
                #:concat-paths
                #:copy)
  (:import-from :cli-program/src/cmds
                #:put
                #:rm
                #:empty-trash
                #:restore)
  (:import-from :cl-fad #:walk-directory)
  (:import-from :clingon)
  (:export
   :cli-program/command))
(in-package :cli-program/src/cli)
```

This could end up being more of a question about Common Lisp packages, so I apologizes if that ends up being the case.

I did try using:

```sh
ros -e "(setf ql:*local-project-directories* '(#p\"(PWD)/\"))" build roswell/cli-program.ros --disable-compression
``` 

Which is based on what is found in the [FAQ](https://github.com/roswell/roswell/wiki/FAQ#quick-recipe-for-building-a-binary-with-my-private-subprojects), but the result is the same. The project is also symlinked to `~/.roswell/local-projects/`.

## Environment

`uname -a`:

```
Linux my-artix 5.14.15-lqx1-1-lqx #1 ZEN SMP PREEMPT Sun, 31 Oct 2021 04:41:45 +0000 x86_64 GNU/Linux
```

`ros --version`:

```
roswell 21.10.14.111(NO-GIT-REVISION)
```

`ros config`:

```
ccl-bin.version=1.12.1
setup.time=3844648578
sbcl-bin.version=2.1.9
default.lisp=sbcl-bin

Possible subcommands:
set
show
```

EDIT: I tried to more or less base the `.ros` file off of what's show in @fukamachi's [Qlot](https://github.com/fukamachi/qlot/blob/master/roswell/qlot.ros).

**Comment by guicho271828** [comment]
```diff
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros +Q -- $0 "$@"
|#

;; TODO is this all correct?

(progn ;;init forms
  (ros:ensure-asdf)
  #+quicklisp(ql:quickload '(osicat 
                             cl-fad 
+                             cli-program
                             pathname-utils 
                             clingon) ;; <- this package is not in Quicklisp, so I have to figure that out 
                 :silent t))

(defpackage :ros/script/cli-program
  (:use :cl)
  (:import-from :cli-program/src/cli
                #:cli-program/command))
(in-package #:ros/script/cli-program)

(defun main (&rest argv)
  (declare (ignorable argv))
  (let ((app (cli-program/command)))
    (clingon:run app)))
;;; vim: set ft=lisp lisp:
```

**Comment by alecStewart1** [comment]
@guicho271828 

Oh, well..shit. Thanks!

I guess I'd also ask about how I'd go about using `clingon` since it's not in Quicklisp. I can install it myself on my system, but what if I wanted distribute this program?

**Comment by alecStewart1** [comment]
Is this just a matter of how I've structured my project?

Modifying my projects `.asd` file doesn't change anything. I'm assuming because my projects Roswell file is in `$PROJECT-ROOT/roswell/` and not in the projects root directory?

**Comment by guicho271828** [comment]
you have a local copy of `clingon`, right? `clingon` is in your `local-projects`, right? Then it should load.

Loading `cli-program`, which is your library, is absolutely necessary because the script starts afresh.

**Comment by guicho271828** [comment]
If you want to get help, please specify what's where and how what is failing. In this case specifically the location of clingon and cli-program.

**Comment by alecStewart1** [comment]
I have specified what's failing. It's in the issue. `ros build` fails on my project.

cli-program is in a different directory, but it's symlinked to `~/.roswell/local-projects/`. Clingon is also in the directory as well.

The Roswell file is in the cli-program project, in the `roswell/` directory.

I would also like to note that running `asdf:make` works fine with the following `.asd` file:

```lisp
(defpackage :cli-program-system
  (:use :cl :asdf))
(in-package :cli-program-system)

(defsystem "cli-program"
  :name "cli-program"
  :description "A cool CLI program"
  :long-description "A *very* cool CLI Program"
  :version "0.1.0"
  :author "Alec Stewart <alec.stewart@protonmail.com>"
  :maintainer "Alec Stewart <alec.stewart@protonmail.com>"
  :license "MIT"
  :homepage "https://github/alecStewart1/cli-program"
  :bug-tracker "https://github/alecStewart1/cli-program"
  :source-control "https://github/alecStewart1/cli-program"
  :depends-on (:uiop
               :osicat
               :cl-fad
               :pathname-utils
               :clingon)
  :pathname #P"src/"
  :serial t
  :components ((:file "types")
               (:file "envvars")
               (:file "info")
               (:file "utils")
               (:file "cmds")
               (:file "cli"))
  :build-operation "program-op"
  :build-pathname "cli-program"
  :entry-point "cli-program/cli:main"
  :in-order-to ((test-op (test-op "cli-program-test"))))
```

**Comment by guicho271828** [comment]
* You should first find a reason why a package "cli-program/src/cli" does not exit.
* Assuming the package is in the "cli-program" system, you should load "cli-program".
* Is the package "cli-program/src/cli" defined in one of the 6 files above? ("types", ..., "cmds", "cli")

**Comment by guicho271828** [comment]
Sorry, the package seems to be define in the "cli.lisp"  that you showed above.
 
Perhaps your command line usage is weird. what happens if you simply run `ros install cli-program` ? It should autodetect `roswell/cl-program.ros` and copy it to `~/.roswell/bin`.

If you want to build the core, change the beginning to this. This doesn't seem quite reliable now, though.
```diff
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
+exec ros +Q -L sbcl-bin -m cli-program -- $0 "$@"
-exec ros +Q -- $0 "$@"
|#
```

**Comment by alecStewart1** [comment]
Ah, the `-L sbcl-bin -m cli-program` bit worked.

However I'm having issues building with `ccl-bin` and `ecl-bin`, _not_ using that same Roswell file. But that's a different issue.
