### ISSUE TITLE
Add installed implementations to ~/.roswell/bin

### ISSUE THREAD

**Issue by daewok** [roswell/roswell#504]
It would be amazing if Roswell could make its managed implementations available via their canonical names, without any Roswell customizations. This could be done by putting links or scripts in `~/.roswell/bin/`.

This would make usage of Roswell more transparent for a lot of use cases.

## Environment

```
# result of evaluating
uname -a
Linux rocinante 5.10.76-1.fc32.qubes.x86_64 #1 SMP Fri Oct 29 03:58:58 CEST 2021 x86_64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz GenuineIntel GNU/Linux
ros --version    # if roswell runs successfully
roswell 21.10.14.111(NO-GIT-REVISION)
ros config
setup.time=3850297671
sbcl-bin.version=2.2.0
default.lisp=sbcl-bin
```

We may assign explanatory tags to bad questions instead of replying to it.
See this famous text on how to ask good questions http://catb.org/~esr/faqs/smart-questions.html

## How to reproduce the issue

```sh
export PATH="/home/user/.roswell/bin:$PATH"
sbcl

```

## Expected behavior

Get an SBCL REPL.

## Actual result

```sh
zsh: command not found: sbcl
```

**Comment by snmsts** [comment]
Because I don't recommend to invoke each lisp implementation launch directory,
I don't want to support or implement the idea with roswell.

for your needs I think just introduce this kind of shell script would be sufficient most of the case...
```
#!/bin/sh
ros -L sbcl-bin without-roswell=t --no-rc run -- $*
```

**Comment by daewok** [comment]
That's unfortunate and I'd urge you to reconsider that stance. I think this is one of the big friction points getting in the way of broader Roswell adoption. It makes it feel like Roswell is trying to supplant large parts of the CL ecosystem instead of enhance them.

Additionally, it seems like `without-roswell=t` is undocumented and implemented only for SBCL.

**Comment by snmsts** [comment]
I do understand what you want here but my challenge with roswell is to provide same interface for different lisp implementations on some unix and windows. Therefore the os functionality usable from roswell are limited to the common set. that's why I do immediate No for symlink.

I don't disagree with opinions like "It's better to have simpler lisp installer/version manager than roswell". but it is not the way I can direct. sorry.

**Comment by daewok** [comment]
I'm not sure how to parse this:

> Therefore the os functionality usable from roswell are limited to the common set. that's why I do immediate No for symlink.

If it's just another way of saying you don't want to support this in Roswell, then ignore the next paragraph and code snippet.

If this is a technical argument against symlinks, note that it doesn't have to be a symlink and it can in fact be more powerful if it's not. It could instead be a script or batch script equivalent to:

```shell
#!/bin/sh

# A hypothetical Roswell command that resolves which version of SBCL we should
# use. This could look at config files, envvars, whatever.
_SBCL_PATH="$(ros which sbcl)"
exec "$_SBCL_PATH" "$@"
```

In either case, I'm going to close since you don't want to make unmodified Roswell-managed implementations available.
