### ISSUE TITLE
Roswell not working on Mac mini M1

### ISSUE THREAD

**Issue by loox** [roswell/roswell#508]
Hi there,
trying to make Roswell working on a Mac mini Apple Silicon with macOS 12.1 (21C52).

I installed Roswell via Homebrew but, when I try whatever Roswell command, the output is

`sbcl-bin/2.0.11 does not exist.stop.`

Can anyone help a newbie?

Thanks in advance. :-)

**Comment by snmsts** [comment]
``rm -rf  ~/.roswell``  and restart again might work.

**Comment by snmsts** [comment]
seems no one helped the newbie...
