### ISSUE TITLE
Malicous links on the installation page?

### ISSUE THREAD

**Issue by JennToo** [roswell/roswell#532]
I'm looking at the installation guide and see several suspicious links. I of course recommend not clicking them

https://github.com/roswell/roswell/wiki/Installation

Looking through the page I see links to:

- tracker.iplocation.net (this is the one I clicked and noticed the problem)
- Some links to rar files from a random renamed github account toxor4/VideoCaptureUtility/.../roswell_xyz.rar.

I can see from the revision history on the page that this seems to be a back-and-forth between random 404'ing github accounts and reverts of the (seemingly) malicious links they add. Maybe wiki editing should be locked down a bit more?

**Comment by snmsts** [comment]
I checked "Restrict editing to users in teams with push access only".
