### ISSUE TITLE
Roswell CI started installing old version of CCL-BIN – 1.8 instead of 1.12.0

### ISSUE THREAD

**Issue by svetlyak40wt** [roswell/roswell#534]
When I set `LISP=ccl-bin` for my GitHub workflow, and it hangs for hour, trying to install `ccl-bin/1.8`:

https://github.com/40ants/ci/actions/runs/3078757544/jobs/4974514420

a piece from the log:

```
Installing Quicklisp... Done 19889
  Making core for Roswell...
  Checking version to install...
  Downloading https://github.com/roswell/ccl_bin/releases.atom
  [#################                                                         ] 22%
  [#####################################                                     ] 50%
  [#########################################################                 ] 78%
  [##########################################################################]100%
  Installing ccl-bin/1.8...
  Downloading https://github.com/roswell/ccl_bin/releases/download/1.8/ccl-1.8-linuxx86.tar.gz
  [                                                                          ]  0%
  [                                                                          ]  1%
  [#                                                                         ]  1%
  [#     
...
Downloading archive:https://github.com/roswell/ccl_bin/releases/download/1.8/ccl-1.8-linuxx86.tar.gz:OK
  Extracting archive:/home/runner/.roswell/archives/ccl-1.8-linuxx86.tar.gz
  + ros use ccl-bin
```

Here is GitHub workflow run where I've used explicit version `LISP=ccl-bin/1.12.1` **and it ends successfully**:

https://github.com/40ants/40ants-asdf-system/actions/runs/3412865072/jobs/5678908762

Here is github action's code: https://github.com/40ants/setup-lisp/blob/master/action.yml I didn't changed it for a year. Probably something has changed in the https://github.com/roswell/ccl_bin/releases.atom?

Tested on Roswell: v21.10.14.111

**Comment by Ambrevar** [comment]
I confirm the issue, it also affects the nyxt actions: https://github.com/atlas-engineer/nyxt/actions/runs/3541291945/jobs/5945378336

**Comment by snmsts** [comment]
sorry I didn't check issues recently and it seems like came from https://github.com/Shinmera/plump/commit/b0ae08ff4fdc6c86847a736c40b66c8b115ea7f9#diff-915a62aea3d5082b634c9e1815182be1f98fa21ad6336078fa1b37435f63f39b

**Comment by Ambrevar** [comment]
CI is still failing, presumably because it's still using an old version of Roswell?
Any idea how to force the CI to use the fix on master?

This is how I'm installing Roswell in the CI:

```sh
curl -L https://raw.githubusercontent.com/roswell/roswell/v21.10.14.111/scripts/install-for-ci.sh | sh -x
```

**Comment by snmsts** [comment]
I guess with ``ROSWELL_BRANCH=master``  will do for now.
I'm planning to release in this week though.

**Comment by Ambrevar** [comment]
Roger that, thanks!

**Comment by Ambrevar** [comment]
I can still reproduce this problem with Roswell v22.12.14.113.

**Comment by snmsts** [comment]
I'm sorry to hear that. I thought I've solved.
Can you share how to reproduce?

**Comment by svetlyak40wt** [comment]
I found the probable issue. For some reason, GitHub returns wrong content of the shell script. Pay attention at `ROSWELL_RELEASE_VERSION` variable content for different URLs:

```
curl -L -s https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | head -4 | tail -1
ROSWELL_RELEASE_VERSION=21.10.14.111
```
```
curl -L -s https://raw.githubusercontent.com/roswell/roswell/v21.10.14.111/scripts/install-for-ci.sh | head -4 | tail -1
ROSWELL_RELEASE_VERSION=21.06.14.110
```

Latest version tag also shows old roswell version:

```
curl -L -s https://raw.githubusercontent.com/roswell/roswell/v22.12.14.113/scripts/install-for-ci.sh | head -4 | tail -1
ROSWELL_RELEASE_VERSION=21.10.14.111
```

And if I down load both versions, for above tags, then there will be no
any difference except "wrong" roswell version number:

```
diff -u /tmp/21.10.14.111.sh /tmp/22.12.14.113.sh                                 (master|✔)
--- /tmp/21.10.14.111.sh	2023-01-13 10:56:48.000000000 +0300
+++ /tmp/22.12.14.113.sh	2023-01-13 10:56:30.000000000 +0300
@@ -1,7 +1,7 @@
 #!/bin/sh
 set -e

-ROSWELL_RELEASE_VERSION=21.06.14.110
+ROSWELL_RELEASE_VERSION=21.10.14.111
 ROSWELL_TARBALL_PATH=$HOME/roswell.tar.gz
 ROSWELL_DIR=$HOME/.roswell
 ROSWELL_REPO=${ROSWELL_REPO:-https://github.com/roswell/roswell}
 ```
