### ISSUE TITLE
ECL installation fails on FreeBSD

### ISSUE THREAD

**Issue by ak-coram** [roswell/roswell#536]
## Environment

- FreeBSD in github actions via https://github.com/vmactions/freebsd-vm
- Roswell 21.10.14.111 (via `pkg install roswell` from latest binary packages)

## How to reproduce the issue

```sh
pkg install -y bash roswell autoconf texinfo perl5 gmake gcc libffi
ros install ecl/21.2.1
```

## Expected behavior

The installation should succeed, but fails because it tries to use BSD make and `/bin/sh` instead of GNU make and bash. For example the `-l` option is not supported via `/bin/sh`, but also ECL doesn't build with BSD make.

## Workaround

```sh
ln -s /usr/local/bin/gmake /bin/make
ln -s /usr/local/bin/bash /usr/local/bin/sh
export PATH=/usr/local/bin/:$PATH
```

See full example here:
https://github.com/ak-coram/cl-duckdb/blob/main/.github/workflows/BSD.yml

**Comment by snmsts** [comment]
thanks for reporting. I tested "ros install ecl" on my vagrant freebsd environment.
