### ISSUE TITLE
sbcl-bin for OpenBSD expects libutil.so.15.0, which doesn't exist on 7.2

### ISSUE THREAD

**Issue by kokokodak** [roswell/roswell#546]
When running ros for the first time, it fails with the following error message (Actual result).

It seems that the compiled sbcl expects libutil.so.15.0, but that doesn't exist on the 7.2 and the current version is libutils.so.16.0.

Symlinking the current libutils to the .so.15.0 works as a workaround.

Would it be possible to allow the lisp implementations to be chosen/compiled as initial? It would help to 1) avoid issues such as this, 2) help people understand what they are running.

## Environment

```
# result of evaluating
uname -a = OpenBSD foo.my.domain 7.2 GENERIC.MP#6 amd64
ros --version = roswell 22.12.14.113(eae6e5c)
ros config = sbcl-bin.version=2.3.0
             default.lisp=sbcl-bin

             Possible subcommands:
             set
             show

```

## How to reproduce the issue
Run ros for the first time on OpenBSD 7.2

```
ros
```

## Expected behavior

The first run of ros succeeds.

## Actual result

```
$ /opt/bin/ros                                           
Installing sbcl-bin...
No SBCL version specified. Downloading sbcl-bin_uri.tsv to see the available versions...
[##########################################################################]100%
Installing sbcl-bin/2.3.0...
Downloading https://github.com/roswell/sbcl_bin/releases/download/2.3.0/sbcl-2.3.0-x86-64-openbsd-binary.tar.bz2
[##########################################################################]100%
Extracting sbcl-bin-2.3.0-x86-64-openbsd.tar.bz2 to /home/user/.roswell/src/sbcl-2.3.0-x86-64-openbsd/
Building sbcl-bin/2.3.0... Done.
ld.so: sbcl: can't load library 'libutil.so.15.0'
Killed 
Segmentation fault 
```

**Comment by snmsts** [comment]
I changed default. how's current status.

**Comment by kokokodak** [comment]
Hi, the problem with 'libutil.so.15.0' is fixed now, so the issue can be closed.

I have a related question - where can I find the build scripts to create sbcl-bin? Also, where can I find build scripts that are run when building sbcl with "ros install sbcl"?
