### ISSUE TITLE
can roswell install implementation that I manually download ?

### ISSUE THREAD

**Issue by VSteveHL** [roswell/roswell#554]
can I just download an implementation, like `sbcl-bin-2.3.4-x86-64-windows.msi` or `ccl-1.12.1-windowsx86.zip`,  put it to `.roswell/archives`, then ask roswell to just install them instead of download them from Internet. For some reason roswell's download process often fail in my network, so i download implementation manually and want use roswell as manager. Then i can copy `.roswell` 
directory to other computer which don't have network.

## Environment

```
# result of evaluating
# OS: Windows 11
# ros --version    # if roswell runs successfully
roswell 21.10.14.111(NO-GIT-REVISION)
# ros config
setup.time=3893451723
sbcl-bin.version=2.3.4
default.lisp=sbcl-bin
```

**Comment by snmsts** [comment]
after copy ``ros install sbcl-bin/2.3.4`` ``ros install ccl-bin/1.12.1`` on new environment should work.

**Comment by VSteveHL** [comment]
Thanks! This works for me.
