### ISSUE TITLE
ros crashes on macOS 14

### ISSUE THREAD

**Issue by compufox** [roswell/roswell#568]
SBCL versions prior to 2.3.8 crash on macOS 14.
2.3.8 patched this issue.

## Environment

```
Darwin Machine.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64
```

## How to reproduce the issue

```sh
ros
```

## Expected behavior
Get dropped into lisp REPL

```sh
*
```

## Actual result
ros crashes

```sh
mmap: Operation not permitted
fatal error encountered in SBCL pid 31558 pthread 0x1d951d300:
load_core_bytes(3,0x10000,0x300000000,10000) failed
```

**Comment by seachicken** [comment]
I don't know if it helps, but I solved it with this workaround:
```sh
mv ~/.roswell ~/.roswell.org
ros setup
```
Then, it can install the latest SBCL.

**Comment by compufox** [comment]
oh my god, thank you! worked like a charm for me!
