### ISSUE TITLE
sbcl-bin for OpenBSD 7.5 expects libutil.so.16.0 and libc.so.96.2

### ISSUE THREAD

**Issue by ssh3** [roswell/roswell#583]
Hello. I was trying to use **ros** on OpenBSD, but I got an error.

## Environment
```
# result of evaluating
uname -a
OpenBSD tc.local 7.5 GENERIC.MP#82 amd64
ros --version
roswell 22.12.14.113(eae6e5c)
ros config
# I get error
```

## How to reproduce the issue

```sh
ros config 
```

## Expected behavior
I expected the successful finish of this operation

## Actual result

```sh
$ ros config 
Installing sbcl-bin...
No SBCL version specified. Downloading sbcl-bin_uri.tsv to see the available versions...
[##########################################################################]100%
Installing sbcl-bin/2.3.0...
Downloading https://github.com/roswell/sbcl_bin/releases/download/2.3.0/sbcl-2.3.0-x86-64-openbsd-binary.tar.bz2
[##########################################################################]100%
Extracting sbcl-bin-2.3.0-x86-64-openbsd.tar.bz2 to /var/germinal/.roswell/src/sbcl-2.3.0-x86-64-openbsd/
Building sbcl-bin/2.3.0... Done.
ld.so: sbcl: can't load library 'libutil.so.16.0'
Killed 
Segmentation fault (core dumped) 
```

**Comment by snmsts** [comment]
I'm currently on travel and my laptop's architecture is arm64 Darwin so difficult to prepare environment to emulate openbsd x8664 on it.
and I'm not so into openbsd... so sorry in advance that I don't have eagerness.

* Can you solve the problem the lack of 'libutil.so.16.0' on 7.5?
* do you have sbcl on openbsd 7.5?

**Comment by ssh3** [comment]
> I'm currently on travel and my laptop's architecture is arm64 Darwin so difficult to prepare environment to emulate openbsd x8664 on it. and I'm not so into openbsd... so sorry in advance that I don't have eagerness.

Anyway, I'm grateful for your time.
 
>     * Can you solve the problem the lack of 'libutil.so.16.0' on 7.5?

Actual OpenBSD release has libutil.so.18.0 and libc.so.99.0.

>     * do you have sbcl on openbsd 7.5?

Yes, my system has SBCL 2.4.1, installed from the package.

**Comment by snmsts** [comment]
on library versions I completely not knowlegeable but making symlink wouldn't work?

roswell install sbcl under ``~/.roswell`` my case ``/Users/snmsts/.roswell/impls/arm64/darwin/sbcl-bin/2.4.4`` is actual path (on darwin)
I believe you have installed sbcl somewhere like that on your box. and you have sbcl so try replace roswell installed sbcl with symlink of openbsd official sbcl will be quick fix for setup roswell on your box.

**Comment by ssh3** [comment]
> on library versions I completely not knowlegeable but making symlink wouldn't work?

No, this workaround didn't work. :) I got the message:

```
$ ros       
failed to allocate 1048576 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
Making core for Roswell...             
failed to allocate 1048576 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
failed to allocate 1048576 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
```

> roswell install sbcl under `~/.roswell` my case `/Users/snmsts/.roswell/impls/arm64/darwin/sbcl-bin/2.4.4` is actual path (on darwin) I believe you have installed sbcl somewhere like that on your box. and you have sbcl so try replace roswell installed sbcl with symlink of openbsd official sbcl will be quick fix for setup roswell on your box.

Yes, it's working:

```
ln -s /usr/local/bin/sbcl ~/.roswell/impls/x86-64/openbsd/sbcl-bin/2.3.0/bin/
ln -s /usr/local/lib/sbcl ~/.roswell/impls/x86-64/openbsd/sbcl-bin/2.3.0/lib/
```

Thank you for an advice. Should I close this issue or will you research this problem later?

**Comment by snmsts** [comment]
no research. just knowing it's obsolate.
I'm not serious openbsd user so thinking about how to build openbsd's binary up to date is the question.
