### ISSUE TITLE
Support for ECL version 24.5.10

### ISSUE THREAD

**Issue by ak-coram** [roswell/roswell#589]
The new version was released on 2024-05-10, is there anything preventing Roswell from using it by default? Please let me know if I can help in any way. Thanks!

**Comment by snmsts** [comment]
thanks to notify. it happend because https://github.com/roswell/ecl is not mirrored and update is depend on github action on https://github.com/roswell/daily_maintenance.
I guess it's ok for you for now.
can you try?

**Comment by ak-coram** [comment]
> I guess it's ok for you for now.
> can you try?

Works perfectly, thank you!
