### ISSUE TITLE
More easily accessible documentation

### ISSUE THREAD

**Issue by fare** [roswell/roswell#62]
eudoxia recommends killing cl-launch and consolidating to use roswell. But I can't easily find a manual, API description, or anything from either the README.md or documents/ros.html.

How can I find out what makes roswell so much better than cl-launch?

**Comment by KeenS** [comment]
:+1: 
Kill CIM too, please.

**Comment by fukamachi** [comment]
Thank you for killing Shelly, btw. :+1:

**Comment by macdavid313** [comment]
What about killing [*ScriptL*](https://github.com/rpav/ScriptL)? :scream_cat:

**Comment by snmsts** [comment]
@fare as I mentioned on twitter. I should say I'm sorry for lacking documents.I'll take more effort on that later.
@KeenS If you start using roswell I'll feel CIM is dead.I'll improve roswell until the day :)
@fukamachi btw Shelly is my favorite English tutor's name. :cry: 
@macdavid313 I think it's not roswell's responsibility. Now I'm thinking about how to distribute ros scripts easily. so someone will make alternative on top of it might be possible.

**Comment by fare** [comment]
Can you start by stating:

1- what are the source platforms required for bootstrap (looks like C (ouch) — any libraries required? Does it work on Linux? BSD? MacOSX? Windows?)

2- what are the target platforms supported?

3- where to dig for more information regarding, e.g. a list of invocation arguments?

Seeing that it's C, I don't see it displacing cl-launch, which is a no-installation-required shell script that supports 12 different targets (sbcl ccl clisp abcl allegro lispworks scl cmucl ecl mkcl gcl xcl) on all platforms (except it's not native on Windows).

Now that CCL is stable on Windows and UIOP offers a portable run-program and *command-line-arguments*, I could see a pure CL replacement for all of cl-launch, roswell, etc. Distribute precompiled CCL executable images on Windows, and a bootstrap script (generated from CL) on Unix. Actually, it could also handle parallel building, etc. — what XCVB ought to have been if I hadn't betrayed it to do ASDF2 & 3.

**Comment by dkochmanski** [comment]
I'm still curious about reasoning behind deprecating cl-launch in favour of something new. It's really nifty utility

**Comment by snmsts** [comment]
1. I notice,I have to install automake libcurl4-gnutls-dev build-essential for ubuntu box before start ./bootstrap. 
2. installable lisp is sbcl,ccl and partially clisp(on going).in addition to them only launch support lisps are cmucl,allegro,ecl,abcl.
3. I just add invocation arguments... https://github.com/snmsts/roswell/blob/master/README.md

I 100% agree with your opinion It is not displacing cl-launch.I think why I chose C is I'd like to support all minor CPUs and OSs.It's painful but worth.
