### ISSUE TITLE
completion for shell.

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#86]

**Comment by snmsts** [comment]
bash zsh

**Comment by guicho271828** [comment]
asking permission to @i-kiwamu at https://gist.github.com/i-kiwamu/b21a9dc57ba7d2d7c40d

**Comment by guicho271828** [comment]
work in progress: https://github.com/roswell/roswell/tree/completion

**Comment by snmsts** [comment]
:+1:

**Comment by guicho271828** [comment]
imported the zsh completion script from https://gist.github.com/i-kiwamu/b21a9dc57ba7d2d7c40d at 9842343d53e98a7f99f019e49b4cf56ee2686da6

**Comment by guicho271828** [comment]
remaining task:
+ [ ] current installation/uninstallation script does not manage subdirectory etc/. 
+ [ ] zsh completion quality might not be as good as in bash completion.

**Comment by snmsts** [comment]
I'd like to move files. how about
etc/zsh/functions/_ros -> scripts/completion/ros-completion.zsh
etc/bash-completion.d/ros -> scripts/completion/ros-completion.bash

**Comment by guicho271828** [comment]
They are the directories zsh/bash (resp.) search for completion scripts by default, at least on linux systems. Wouldn't it be the same for OSX? They wouldn't affect Windows users, either.

I am not familiar with autotools, so Id like someone to write the rules for copying them in Makefile.am.

**Comment by snmsts** [comment]
I think there are no relationship between where it placed in repository and where it installed on system.
Just I prefer how it placed like git project.
https://github.com/git/git/tree/master/contrib/completion

> I am not familiar with autotools, so Id like someone to write the rules for copying them in Makefile.am.

Sure. I will.

**Comment by snmsts** [comment]
done.

**Comment by guicho271828** [comment]
thanks
